package com.scor.global;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.6
 * 2014-10-22T13:55:56.637+02:00
 * Generated source version: 2.6.6
 * 
 */
@WebService(targetNamespace = "http://services/", name = "AnnotatedSecureService")
@XmlSeeAlso({ObjectFactory.class})
public interface AnnotatedSecureService {

    @WebResult(name = "simpleResult", targetNamespace = "")
    @RequestWrapper(localName = "simpleMethod", targetNamespace = "http://services/", className = "com.scor.global.SimpleMethod")
    @WebMethod
    @ResponseWrapper(localName = "simpleMethodResponse", targetNamespace = "http://services/", className = "com.scor.global.SimpleMethodResponse")
    public com.scor.global.Compania simpleMethod(
        @WebParam(name = "compania", targetNamespace = "")
        com.scor.global.Compania compania
    );
}
