package com.scor.global;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.6
 * 2014-10-22T13:55:56.720+02:00
 * Generated source version: 2.6.6
 * 
 */
@WebServiceClient(name = "AnnotatedSecureServiceService", 
                  wsdlLocation = "http://localhost:8080/scorWebservice/services/annotatedSecure?wsdl",
                  targetNamespace = "http://services/") 
public class AnnotatedSecureServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://services/", "AnnotatedSecureServiceService");
    public final static QName AnnotatedSecureServicePort = new QName("http://services/", "AnnotatedSecureServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/scorWebservice/services/annotatedSecure?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(AnnotatedSecureServiceService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/scorWebservice/services/annotatedSecure?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public AnnotatedSecureServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AnnotatedSecureServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AnnotatedSecureServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns AnnotatedSecureService
     */
    @WebEndpoint(name = "AnnotatedSecureServicePort")
    public AnnotatedSecureService getAnnotatedSecureServicePort() {
        return super.getPort(AnnotatedSecureServicePort, AnnotatedSecureService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AnnotatedSecureService
     */
    @WebEndpoint(name = "AnnotatedSecureServicePort")
    public AnnotatedSecureService getAnnotatedSecureServicePort(WebServiceFeature... features) {
        return super.getPort(AnnotatedSecureServicePort, AnnotatedSecureService.class, features);
    }

}
