package com.scortelemed.schemas.psn;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.6
 * 2017-02-20T13:39:05.455+01:00
 * Generated source version: 2.6.6
 * 
 */
@WebServiceClient(name = "GestionReconocimientosMedicosServiceService", 
                  wsdlLocation = "file:/D:/Documentacion/Cias/PSN/psn.wsdl",
                  targetNamespace = "http://www.scortelemed.com/schemas/psn") 
public class GestionReconocimientosMedicosServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.scortelemed.com/schemas/psn", "GestionReconocimientosMedicosServiceService");
    public final static QName GestionReconocimientosMedicosServicePort = new QName("http://www.scortelemed.com/schemas/psn", "GestionReconocimientosMedicosServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/Documentacion/Cias/PSN/psn.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(GestionReconocimientosMedicosServiceService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/D:/Documentacion/Cias/PSN/psn.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public GestionReconocimientosMedicosServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public GestionReconocimientosMedicosServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GestionReconocimientosMedicosServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public GestionReconocimientosMedicosServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public GestionReconocimientosMedicosServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public GestionReconocimientosMedicosServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns GestionReconocimientosMedicosService
     */
    @WebEndpoint(name = "GestionReconocimientosMedicosServicePort")
    public GestionReconocimientosMedicosService getGestionReconocimientosMedicosServicePort() {
        return super.getPort(GestionReconocimientosMedicosServicePort, GestionReconocimientosMedicosService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GestionReconocimientosMedicosService
     */
    @WebEndpoint(name = "GestionReconocimientosMedicosServicePort")
    public GestionReconocimientosMedicosService getGestionReconocimientosMedicosServicePort(WebServiceFeature... features) {
        return super.getPort(GestionReconocimientosMedicosServicePort, GestionReconocimientosMedicosService.class, features);
    }

}
