package com.scortelemed.schemas.psn;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.6
 * 2017-02-20T13:39:05.449+01:00
 * Generated source version: 2.6.6
 * 
 */
@WebService(targetNamespace = "http://www.scortelemed.com/schemas/psn", name = "GestionReconocimientosMedicosService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface GestionReconocimientosMedicosService {

    @WebResult(name = "GestionReconocimientoMedicoResponse", targetNamespace = "http://www.scortelemed.com/schemas/psn", partName = "GestionReconocimientoMedicoResponse")
    @WebMethod(operationName = "GestionReconocimientosMedico")
    public GestionReconocimientoMedicoResponse gestionReconocimientosMedico(
        @WebParam(partName = "GestionReconocimientoMedicoRequest", name = "GestionReconocimientoMedicoRequest", targetNamespace = "http://www.scortelemed.com/schemas/psn")
        GestionReconocimientoMedicoRequest gestionReconocimientoMedicoRequest
    );

    @WebResult(name = "ResultadoReconocimientoMedicoResponse", targetNamespace = "http://www.scortelemed.com/schemas/psn", partName = "ResultadoReconocimientoMedicoResponse")
    @WebMethod(operationName = "ResuladoReconocimientoMedico")
    public ResultadoReconocimientoMedicoResponse resuladoReconocimientoMedico(
        @WebParam(partName = "ResultadoReconocimientoMedicoRequest", name = "ResultadoReconocimientoMedicoRequest", targetNamespace = "http://www.scortelemed.com/schemas/psn")
        ResultadoReconocimientoMedicoRequest resultadoReconocimientoMedicoRequest
    );
}
