
package com.scortelemed.schemas.psn;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 2.1
 * Tue Feb 05 14:21:32 CET 2019
 * Generated source version: 2.1
 * 
 */

@WebServiceClient(name = "PsnUnderwrittingCaseManagementServiceService", targetNamespace = "http://www.scortelemed.com/schemas/psn", wsdlLocation = "http://localhost:8080/scorWebservice/services/psn/PsnUnderwrittingCaseManagement?wsdl")
public class PsnUnderwrittingCaseManagementServiceService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://www.scortelemed.com/schemas/psn", "PsnUnderwrittingCaseManagementServiceService");
    public final static QName PsnUnderwrittingCaseManagementServicePort = new QName("http://www.scortelemed.com/schemas/psn", "PsnUnderwrittingCaseManagementServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/scorWebservice/services/psn/PsnUnderwrittingCaseManagement?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://localhost:8080/scorWebservice/services/psn/PsnUnderwrittingCaseManagement?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public PsnUnderwrittingCaseManagementServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PsnUnderwrittingCaseManagementServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PsnUnderwrittingCaseManagementServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns PsnUnderwrittingCaseManagementService
     */
    @WebEndpoint(name = "PsnUnderwrittingCaseManagementServicePort")
    public PsnUnderwrittingCaseManagementService getPsnUnderwrittingCaseManagementServicePort() {
        return super.getPort(PsnUnderwrittingCaseManagementServicePort, PsnUnderwrittingCaseManagementService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PsnUnderwrittingCaseManagementService
     */
    @WebEndpoint(name = "PsnUnderwrittingCaseManagementServicePort")
    public PsnUnderwrittingCaseManagementService getPsnUnderwrittingCaseManagementServicePort(WebServiceFeature... features) {
        return super.getPort(PsnUnderwrittingCaseManagementServicePort, PsnUnderwrittingCaseManagementService.class, features);
    }

}
