
package com.scortelemed.schemas.psn;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.1
 * Tue Feb 05 14:21:32 CET 2019
 * Generated source version: 2.1
 * 
 */

public final class PsnUnderwrittingCaseManagementService_PsnUnderwrittingCaseManagementServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://www.scortelemed.com/schemas/psn", "PsnUnderwrittingCaseManagementServiceService");

    private PsnUnderwrittingCaseManagementService_PsnUnderwrittingCaseManagementServicePort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = PsnUnderwrittingCaseManagementServiceService.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        PsnUnderwrittingCaseManagementServiceService ss = new PsnUnderwrittingCaseManagementServiceService(wsdlURL, SERVICE_NAME);
        PsnUnderwrittingCaseManagementService port = ss.getPsnUnderwrittingCaseManagementServicePort();  
        
        {
        System.out.println("Invoking resultadoReconocimientoMedico...");
        ResultadoReconocimientoMedicoRequest _resultadoReconocimientoMedico_resultadoReconocimientoMedicoRequest = new ResultadoReconocimientoMedicoRequest();
        _resultadoReconocimientoMedico_resultadoReconocimientoMedicoRequest.setNumSolicitud("NumSolicitud1150570192");
        ResultadoReconocimientoMedicoResponse _resultadoReconocimientoMedico__return = port.resultadoReconocimientoMedico(_resultadoReconocimientoMedico_resultadoReconocimientoMedicoRequest);
        System.out.println("resultadoReconocimientoMedico.result=" + _resultadoReconocimientoMedico__return);


        }
        {
        System.out.println("Invoking gestionReconocimientoMedico...");
        GestionReconocimientoMedicoRequest _gestionReconocimientoMedico_gestionReconocimientoMedicoRequest = new GestionReconocimientoMedicoRequest();
        GestionReconocimientoMedicoRequest.CandidateInformation _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformation = new GestionReconocimientoMedicoRequest.CandidateInformation();
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformation.setProductCode("ProductCode441666596");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformation.setRequestNumber("RequestNumber940135168");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformation.setOperation("Operation-1693801333");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformation.setPolicyNumber("PolicyNumber-2083062429");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformation.setCertificateNumber("CertificateNumber-1069958714");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformation.setRequestDate("RequestDate-266320457");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformation.setPassword("Password-186899300");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformation.setRequestState("RequestState158430266");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformation.setName("Name348839089");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformation.setSurname("Surname1199128667");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformation.setAddress("Address2114238852");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformation.setPostalCode("PostalCode-1613404303");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformation.setCity("City-1632531559");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformation.setProvince("Province-1251233918");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformation.setCountry("Country905897250");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformation.setPhoneNumber1("PhoneNumber11651752285");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformation.setPhoneNumber2("PhoneNumber2-1736360984");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformation.setMobileNumber("MobileNumber1630071440");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformation.setEmail("Email2008648249");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformation.setBirthDate("BirthDate1849863940");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformation.setActuarialAge("ActuarialAge501877545");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformation.setBirthCity("BirthCity-2122052792");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformation.setFiscalIdentificationNumber("FiscalIdentificationNumber1640869490");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformation.setAgency("Agency-526320689");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformation.setAgent("Agent-1797686615");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformation.setAgentPhone("AgentPhone-1146672474");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformation.setAgentEmail("AgentEmail-373303129");
        GenderType _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformationGender = GenderType.M;
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformation.setGender(_gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformationGender);
        CivilStateType _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformationCivilState = CivilStateType.C;
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformation.setCivilState(_gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformationCivilState);
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformation.setCustomerType("CustomerType-1356917011");
        ContactTimeType _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformationContactTime = ContactTimeType.M;
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformation.setContactTime(_gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformationContactTime);
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformation.setComments("Comments-1425350309");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformation.setEUWReferenceCode("EUWReferenceCode1336137724");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequest.setCandidateInformation(_gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformation);
        java.util.List<GestionReconocimientoMedicoRequest.PreviousQuestions> _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestPreviousQuestions = new java.util.ArrayList<GestionReconocimientoMedicoRequest.PreviousQuestions>();
        GestionReconocimientoMedicoRequest.PreviousQuestions _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestPreviousQuestionsVal1 = new GestionReconocimientoMedicoRequest.PreviousQuestions();
        QuestionDataType _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestPreviousQuestionsVal1DataType = QuestionDataType.STRING;
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestPreviousQuestionsVal1.setDataType(_gestionReconocimientoMedico_gestionReconocimientoMedicoRequestPreviousQuestionsVal1DataType);
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestPreviousQuestionsVal1.setAnswerCode("AnswerCode-1983661165");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestPreviousQuestionsVal1.setQuestion("Question135022513");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestPreviousQuestionsVal1.setAnswer("Answer478323574");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestPreviousQuestions.add(_gestionReconocimientoMedico_gestionReconocimientoMedicoRequestPreviousQuestionsVal1);
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequest.getPreviousQuestions().addAll(_gestionReconocimientoMedico_gestionReconocimientoMedicoRequestPreviousQuestions);
        java.util.List<GestionReconocimientoMedicoRequest.Services> _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestServices = new java.util.ArrayList<GestionReconocimientoMedicoRequest.Services>();
        GestionReconocimientoMedicoRequest.Services _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestServicesVal1 = new GestionReconocimientoMedicoRequest.Services();
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestServicesVal1.setServiceType("ServiceType1687523043");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestServicesVal1.setServiceCode("ServiceCode-1712917574");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestServicesVal1.setServiceDescription("ServiceDescription1410290303");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestServices.add(_gestionReconocimientoMedico_gestionReconocimientoMedicoRequestServicesVal1);
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequest.getServices().addAll(_gestionReconocimientoMedico_gestionReconocimientoMedicoRequestServices);
        java.util.List<BenefitsType> _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestBenefits = new java.util.ArrayList<BenefitsType>();
        BenefitsType _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestBenefitsVal1 = new BenefitsType();
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestBenefitsVal1.setBenefictName("BenefictName161472905");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestBenefitsVal1.setBenefictCode("BenefictCode831166909");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestBenefitsVal1.setBenefictCapital("BenefictCapital539685635");
        BenefictResultType _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestBenefitsVal1BenefictResult = new BenefictResultType();
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestBenefitsVal1BenefictResult.setDescResult("DescResult770556521");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestBenefitsVal1BenefictResult.setResultCode("ResultCode-999310424");
        BenefictNameType _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestBenefitsVal1BenefictResultResult = BenefictNameType.DEPENDENCY;
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestBenefitsVal1BenefictResult.setResult(_gestionReconocimientoMedico_gestionReconocimientoMedicoRequestBenefitsVal1BenefictResultResult);
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestBenefitsVal1BenefictResult.setPremiumLoading("PremiumLoading1385742559");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestBenefitsVal1BenefictResult.setCapitalLoading("CapitalLoading-1235187473");
        java.util.List<String> _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestBenefitsVal1BenefictResultTemporalLoading = new java.util.ArrayList<String>();
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestBenefitsVal1BenefictResult.getTemporalLoading().addAll(_gestionReconocimientoMedico_gestionReconocimientoMedicoRequestBenefitsVal1BenefictResultTemporalLoading);
        java.util.List<String> _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestBenefitsVal1BenefictResultExclusions = new java.util.ArrayList<String>();
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestBenefitsVal1BenefictResult.getExclusions().addAll(_gestionReconocimientoMedico_gestionReconocimientoMedicoRequestBenefitsVal1BenefictResultExclusions);
        java.util.List<String> _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestBenefitsVal1BenefictResultMedicalReports = new java.util.ArrayList<String>();
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestBenefitsVal1BenefictResult.getMedicalReports().addAll(_gestionReconocimientoMedico_gestionReconocimientoMedicoRequestBenefitsVal1BenefictResultMedicalReports);
        java.util.List<String> _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestBenefitsVal1BenefictResultNotes = new java.util.ArrayList<String>();
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestBenefitsVal1BenefictResult.getNotes().addAll(_gestionReconocimientoMedico_gestionReconocimientoMedicoRequestBenefitsVal1BenefictResultNotes);
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestBenefitsVal1.setBenefictResult(_gestionReconocimientoMedico_gestionReconocimientoMedicoRequestBenefitsVal1BenefictResult);
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestBenefits.add(_gestionReconocimientoMedico_gestionReconocimientoMedicoRequestBenefitsVal1);
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequest.getBenefits().addAll(_gestionReconocimientoMedico_gestionReconocimientoMedicoRequestBenefits);
        GestionReconocimientoMedicoResponse _gestionReconocimientoMedico__return = port.gestionReconocimientoMedico(_gestionReconocimientoMedico_gestionReconocimientoMedicoRequest);
        System.out.println("gestionReconocimientoMedico.result=" + _gestionReconocimientoMedico__return);


        }
        {
        System.out.println("Invoking consultaDocumento...");
        ConsultaDocumentoRequest _consultaDocumento_consultaDocumentoRequest = new ConsultaDocumentoRequest();
        _consultaDocumento_consultaDocumentoRequest.setCodigoSt("CodigoSt938615840");
        _consultaDocumento_consultaDocumentoRequest.setDocumentacionId("DocumentacionId-1657661584");
        _consultaDocumento_consultaDocumentoRequest.setNodoAlfresco("NodoAlfresco-499168062");
        ConsultaDocumentoResponse _consultaDocumento__return = port.consultaDocumento(_consultaDocumento_consultaDocumentoRequest);
        System.out.println("consultaDocumento.result=" + _consultaDocumento__return);


        }
        {
        System.out.println("Invoking consolidacionPoliza...");
        ConsolidacionPolizaRequest _consolidacionPoliza_consolidacionPolizaRequest = new ConsolidacionPolizaRequest();
        _consolidacionPoliza_consolidacionPolizaRequest.setProductCode("ProductCode-1853672736");
        _consolidacionPoliza_consolidacionPolizaRequest.setRequestNumber("RequestNumber-29662849");
        _consolidacionPoliza_consolidacionPolizaRequest.setPolicyNumber("PolicyNumber-1543867003");
        _consolidacionPoliza_consolidacionPolizaRequest.setCertificateNumber("CertificateNumber1999012394");
        _consolidacionPoliza_consolidacionPolizaRequest.setRequestDate("RequestDate-50395632");
        ConsolidacionPolizaResponse _consolidacionPoliza__return = port.consolidacionPoliza(_consolidacionPoliza_consolidacionPolizaRequest);
        System.out.println("consolidacionPoliza.result=" + _consolidacionPoliza__return);


        }
        {
        System.out.println("Invoking consultaExpediente...");
        ConsultaExpedienteRequest _consultaExpediente_consultaExpedienteRequest = new ConsultaExpedienteRequest();
        _consultaExpediente_consultaExpedienteRequest.setNumSolicitud("NumSolicitud124742707");
        _consultaExpediente_consultaExpedienteRequest.setNumExpediente("NumExpediente-858167957");
        _consultaExpediente_consultaExpedienteRequest.setNumSumplemento("NumSumplemento1821448416");
        ConsultaExpedienteResponse _consultaExpediente__return = port.consultaExpediente(_consultaExpediente_consultaExpedienteRequest);
        System.out.println("consultaExpediente.result=" + _consultaExpediente__return);


        }

        System.exit(0);
    }

}
