
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.scortelemed.schemas.psn;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.1
 * Tue Feb 05 14:21:32 CET 2019
 * Generated source version: 2.1
 * 
 */

@WebService(name = "PsnUnderwrittingCaseManagementService",
                      serviceName = "PsnUnderwrittingCaseManagementServiceService",
                      portName = "PsnUnderwrittingCaseManagementServicePort",
                      targetNamespace = "http://www.scortelemed.com/schemas/psn", 
                      wsdlLocation = "http://localhost:8080/scorWebservice/services/psn/PsnUnderwrittingCaseManagement?wsdl",
                      endpointInterface = "com.scortelemed.schemas.psn.PsnUnderwrittingCaseManagementService")
                      
public class PsnUnderwrittingCaseManagementServiceImpl implements PsnUnderwrittingCaseManagementService {

    private static final Logger LOG = Logger.getLogger(PsnUnderwrittingCaseManagementServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see com.scortelemed.schemas.psn.PsnUnderwrittingCaseManagementService#resultadoReconocimientoMedico(com.scortelemed.schemas.psn.ResultadoReconocimientoMedicoRequest  resultadoReconocimientoMedicoRequest )*
     */
    public ResultadoReconocimientoMedicoResponse resultadoReconocimientoMedico(ResultadoReconocimientoMedicoRequest resultadoReconocimientoMedicoRequest) {
        LOG.info("Executing operation resultadoReconocimientoMedico");
        System.out.println(resultadoReconocimientoMedicoRequest);
        try {
            ResultadoReconocimientoMedicoResponse _return = new ResultadoReconocimientoMedicoResponse();
            _return.setDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2019-02-05T14:21:32.574+01:00"));
            StatusType _returnStatus = StatusType.OK;
            _return.setStatus(_returnStatus);
            _return.setMessage("Message1281557105");
            _return.setCode(-675178370);
            java.util.List<ResultadoReconocimientoMedicoResponse.Expediente> _returnExpediente = new java.util.ArrayList<ResultadoReconocimientoMedicoResponse.Expediente>();
            ResultadoReconocimientoMedicoResponse.Expediente _returnExpedienteVal1 = new ResultadoReconocimientoMedicoResponse.Expediente();
            _returnExpedienteVal1.setRequestDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2019-02-05T14:21:32.604+01:00"));
            _returnExpedienteVal1.setRequestNumber("RequestNumber626304382");
            RequestStateType _returnExpedienteVal1RequestState = RequestStateType.CLOSED;
            _returnExpedienteVal1.setRequestState(_returnExpedienteVal1RequestState);
            _returnExpedienteVal1.setProductCode("ProductCode-656435625");
            _returnExpedienteVal1.setPolicyNumber("PolicyNumber-1343369126");
            _returnExpedienteVal1.setCertificateNumber("CertificateNumber-2038190544");
            _returnExpedienteVal1.setFiscalIdentificationNumber("FiscalIdentificationNumber-1901288635");
            _returnExpedienteVal1.setMobilePhone("MobilePhone1505065556");
            _returnExpedienteVal1.setPhoneNumber1("PhoneNumber1-508584599");
            _returnExpedienteVal1.setPhoneNumber2("PhoneNumber2-400701506");
            java.util.List<BenefitsType> _returnExpedienteVal1BenefitsList = new java.util.ArrayList<BenefitsType>();
            _returnExpedienteVal1.getBenefitsList().addAll(_returnExpedienteVal1BenefitsList);
            byte[] _returnExpedienteVal1Zip = new byte[] {};
            _returnExpedienteVal1.setZip(_returnExpedienteVal1Zip);
            _returnExpedienteVal1.setNotes("Notes1739956102");
            _returnExpediente.add(_returnExpedienteVal1);
            _return.getExpediente().addAll(_returnExpediente);
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.scortelemed.schemas.psn.PsnUnderwrittingCaseManagementService#gestionReconocimientoMedico(com.scortelemed.schemas.psn.GestionReconocimientoMedicoRequest  gestionReconocimientoMedicoRequest )*
     */
    public GestionReconocimientoMedicoResponse gestionReconocimientoMedico(GestionReconocimientoMedicoRequest gestionReconocimientoMedicoRequest) {
        LOG.info("Executing operation gestionReconocimientoMedico");
        System.out.println(gestionReconocimientoMedicoRequest);
        try {
            GestionReconocimientoMedicoResponse _return = new GestionReconocimientoMedicoResponse();
            StatusType _returnStatus = StatusType.OK;
            _return.setStatus(_returnStatus);
            _return.setDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2019-02-05T14:21:32.604+01:00"));
            _return.setMessage("Message-1286409539");
            _return.setCode(1144389321);
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.scortelemed.schemas.psn.PsnUnderwrittingCaseManagementService#consultaDocumento(com.scortelemed.schemas.psn.ConsultaDocumentoRequest  consultaDocumentoRequest )*
     */
    public ConsultaDocumentoResponse consultaDocumento(ConsultaDocumentoRequest consultaDocumentoRequest) {
        LOG.info("Executing operation consultaDocumento");
        System.out.println(consultaDocumentoRequest);
        try {
            ConsultaDocumentoResponse _return = new ConsultaDocumentoResponse();
            StatusType _returnStatus = StatusType.OK;
            _return.setStatus(_returnStatus);
            _return.setDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2019-02-05T14:21:32.604+01:00"));
            _return.setMessage("Message-1484456986");
            ConsultaDocumentoResponse.Documento _returnDocumento = new ConsultaDocumentoResponse.Documento();
            _returnDocumento.setCodigoSt("CodigoSt881238816");
            _returnDocumento.setDocumentacionId("DocumentacionId1296044372");
            _returnDocumento.setNodoAlfresco("NodoAlfresco325127084");
            byte[] _returnDocumentoContenido = new byte[] {};
            _returnDocumento.setContenido(_returnDocumentoContenido);
            _return.setDocumento(_returnDocumento);
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.scortelemed.schemas.psn.PsnUnderwrittingCaseManagementService#consolidacionPoliza(com.scortelemed.schemas.psn.ConsolidacionPolizaRequest  consolidacionPolizaRequest )*
     */
    public ConsolidacionPolizaResponse consolidacionPoliza(ConsolidacionPolizaRequest consolidacionPolizaRequest) {
        LOG.info("Executing operation consolidacionPoliza");
        System.out.println(consolidacionPolizaRequest);
        try {
            ConsolidacionPolizaResponse _return = new ConsolidacionPolizaResponse();
            StatusType _returnStatus = StatusType.OK;
            _return.setStatus(_returnStatus);
            _return.setDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2019-02-05T14:21:32.604+01:00"));
            _return.setMessage("Message-702080152");
            _return.setCode(-801555322);
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.scortelemed.schemas.psn.PsnUnderwrittingCaseManagementService#consultaExpediente(com.scortelemed.schemas.psn.ConsultaExpedienteRequest  consultaExpedienteRequest )*
     */
    public ConsultaExpedienteResponse consultaExpediente(ConsultaExpedienteRequest consultaExpedienteRequest) {
        LOG.info("Executing operation consultaExpediente");
        System.out.println(consultaExpedienteRequest);
        try {
            ConsultaExpedienteResponse _return = new ConsultaExpedienteResponse();
            _return.setDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2019-02-05T14:21:32.604+01:00"));
            StatusType _returnStatus = StatusType.OK;
            _return.setStatus(_returnStatus);
            _return.setMessage("Message469600582");
            _return.setCode(-867570162);
            java.util.List<ConsultaExpedienteResponse.Expediente> _returnExpediente = new java.util.ArrayList<ConsultaExpedienteResponse.Expediente>();
            ConsultaExpedienteResponse.Expediente _returnExpedienteVal1 = new ConsultaExpedienteResponse.Expediente();
            CandidateInformationType _returnExpedienteVal1CandidateInformation = new CandidateInformationType();
            _returnExpedienteVal1CandidateInformation.setCodigoSt("CodigoSt-680942931");
            _returnExpedienteVal1CandidateInformation.setFiscalIdentificationNumber("FiscalIdentificationNumber-1288637657");
            _returnExpedienteVal1CandidateInformation.setName("Name-293287002");
            _returnExpedienteVal1CandidateInformation.setSurname("Surname-1556216831");
            _returnExpedienteVal1CandidateInformation.setAddress("Address583503238");
            _returnExpedienteVal1CandidateInformation.setCity("City-1528917899");
            _returnExpedienteVal1CandidateInformation.setProvince("Province-90047367");
            _returnExpedienteVal1CandidateInformation.setCountry("Country656246456");
            _returnExpedienteVal1CandidateInformation.setPostalCode("PostalCode-69857093");
            _returnExpedienteVal1CandidateInformation.setEmail("Email-1050811552");
            GenderType _returnExpedienteVal1CandidateInformationGender = GenderType.M;
            _returnExpedienteVal1CandidateInformation.setGender(_returnExpedienteVal1CandidateInformationGender);
            CivilStateType _returnExpedienteVal1CandidateInformationCivilState = CivilStateType.V;
            _returnExpedienteVal1CandidateInformation.setCivilState(_returnExpedienteVal1CandidateInformationCivilState);
            _returnExpedienteVal1CandidateInformation.setMobileNumber("MobileNumber812437676");
            _returnExpedienteVal1CandidateInformation.setPhoneNumber1("PhoneNumber1-747724091");
            _returnExpedienteVal1CandidateInformation.setPhoneNumber2("PhoneNumber21328652262");
            _returnExpedienteVal1CandidateInformation.setPassword("Password-1509218255");
            _returnExpedienteVal1CandidateInformation.setProductCode("ProductCode577696114");
            _returnExpedienteVal1CandidateInformation.setBirthDate("BirthDate-925863817");
            _returnExpedienteVal1.setCandidateInformation(_returnExpedienteVal1CandidateInformation);
            PolicyHolderInformationType _returnExpedienteVal1PolicyHolderInformation = new PolicyHolderInformationType();
            _returnExpedienteVal1PolicyHolderInformation.setDossierNumber("DossierNumber-593495694");
            _returnExpedienteVal1PolicyHolderInformation.setPolicyNumber("PolicyNumber1694140612");
            _returnExpedienteVal1PolicyHolderInformation.setCertificateNumber("CertificateNumber-1504480736");
            _returnExpedienteVal1PolicyHolderInformation.setSuplementNumber("SuplementNumber251710765");
            _returnExpedienteVal1PolicyHolderInformation.setRequestDate("RequestDate-646424870");
            _returnExpedienteVal1PolicyHolderInformation.setRequestState("RequestState1325825700");
            _returnExpedienteVal1PolicyHolderInformation.setRequestNumber("RequestNumber-1346275253");
            _returnExpedienteVal1.setPolicyHolderInformation(_returnExpedienteVal1PolicyHolderInformation);
            java.util.List<BenefitsType> _returnExpedienteVal1Benefits = new java.util.ArrayList<BenefitsType>();
            _returnExpedienteVal1.getBenefits().addAll(_returnExpedienteVal1Benefits);
            java.util.List<AppointmentsType> _returnExpedienteVal1Appointments = new java.util.ArrayList<AppointmentsType>();
            _returnExpedienteVal1.getAppointments().addAll(_returnExpedienteVal1Appointments);
            java.util.List<ActivitiesType> _returnExpedienteVal1Activities = new java.util.ArrayList<ActivitiesType>();
            _returnExpedienteVal1.getActivities().addAll(_returnExpedienteVal1Activities);
            java.util.List<DocumentType> _returnExpedienteVal1Documents = new java.util.ArrayList<DocumentType>();
            _returnExpedienteVal1.getDocuments().addAll(_returnExpedienteVal1Documents);
            _returnExpediente.add(_returnExpedienteVal1);
            _return.getExpediente().addAll(_returnExpediente);
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
