
package com.scortelemed.schemas.psn;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.1
 * Tue Feb 05 14:21:32 CET 2019
 * Generated source version: 2.1
 * 
 */

@WebService(targetNamespace = "http://www.scortelemed.com/schemas/psn", name = "PsnUnderwrittingCaseManagementService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = ParameterStyle.BARE)

public interface PsnUnderwrittingCaseManagementService {

    @SOAPBinding(parameterStyle = ParameterStyle.BARE)
    @WebResult(name = "ResultadoReconocimientoMedicoResponse", targetNamespace = "http://www.scortelemed.com/schemas/psn", partName = "ResultadoReconocimientoMedicoResponse")
    @WebMethod
    public ResultadoReconocimientoMedicoResponse resultadoReconocimientoMedico(
            @WebParam(partName = "ResultadoReconocimientoMedicoRequest", name = "ResultadoReconocimientoMedicoRequest", targetNamespace = "http://www.scortelemed.com/schemas/psn")
                    ResultadoReconocimientoMedicoRequest resultadoReconocimientoMedicoRequest
    );

    @SOAPBinding(parameterStyle = ParameterStyle.BARE)
    @WebResult(name = "GestionReconocimientoMedicoResponse", targetNamespace = "http://www.scortelemed.com/schemas/psn", partName = "GestionReconocimientoMedicoResponse")
    @WebMethod
    public GestionReconocimientoMedicoResponse gestionReconocimientoMedico(
            @WebParam(partName = "GestionReconocimientoMedicoRequest", name = "GestionReconocimientoMedicoRequest", targetNamespace = "http://www.scortelemed.com/schemas/psn")
                    GestionReconocimientoMedicoRequest gestionReconocimientoMedicoRequest
    );

    @SOAPBinding(parameterStyle = ParameterStyle.BARE)
    @WebResult(name = "ConsultaDocumento", targetNamespace = "http://www.scortelemed.com/schemas/psn", partName = "ConsultaDocumento")
    @WebMethod
    public ConsultaDocumentoResponse consultaDocumento(
            @WebParam(partName = "ConsultaDocumentoRequest", name = "ConsultaDocumentoRequest", targetNamespace = "http://www.scortelemed.com/schemas/psn")
                    ConsultaDocumentoRequest consultaDocumentoRequest
    );

    @SOAPBinding(parameterStyle = ParameterStyle.BARE)
    @WebResult(name = "ConsolidacionPolizaResponse", targetNamespace = "http://www.scortelemed.com/schemas/psn", partName = "ConsolidacionPolizaResponse")
    @WebMethod
    public ConsolidacionPolizaResponse consolidacionPoliza(
            @WebParam(partName = "ConsolidacionPolizaRequest", name = "ConsolidacionPolizaRequest", targetNamespace = "http://www.scortelemed.com/schemas/psn")
                    ConsolidacionPolizaRequest consolidacionPolizaRequest
    );

    @SOAPBinding(parameterStyle = ParameterStyle.BARE)
    @WebResult(name = "ConsultaExpediente", targetNamespace = "http://www.scortelemed.com/schemas/psn", partName = "ConsultaExpediente")
    @WebMethod
    public ConsultaExpedienteResponse consultaExpediente(
            @WebParam(partName = "ConsultaExpedienteRequest", name = "ConsultaExpedienteRequest", targetNamespace = "http://www.scortelemed.com/schemas/psn")
                    ConsultaExpedienteRequest consultaExpedienteRequest
    );
}
