
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.scortelemed.schemas.simplefr;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebParam.Mode;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.1
 * Tue Nov 07 16:41:11 CET 2017
 * Generated source version: 2.1
 * 
 */

@javax.jws.WebService(name = "SimplefrUnderwrittingCaseManagementService",
                      serviceName = "SimplefrUnderwrittingCaseManagementServiceService",
                      portName = "SimplefrUnderwrittingCaseManagementServicePort",
                      targetNamespace = "http://www.scortelemed.com/schemas/simplefr", 
                      wsdlLocation = "http://localhost:8080/scorWebservice/services/simplefr/SimplefrUnderwrittingCaseManagement?wsdl",
                      endpointInterface = "com.scortelemed.schemas.simplefr.SimplefrUnderwrittingCaseManagementService")
                      
public class SimplefrUnderwrittingCaseManagementServiceImpl implements SimplefrUnderwrittingCaseManagementService {

    private static final Logger LOG = Logger.getLogger(SimplefrUnderwrittingCaseManagementServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see com.scortelemed.schemas.simplefr.SimplefrUnderwrittingCaseManagementService#simplefrUnderwrittingCaseManagementRequest(com.scortelemed.schemas.simplefr.SimplefrUnderwrittingCaseManagementRequest  simplefrUnderwrittingCaseManagementRequest )*
     */
    public void simplefrUnderwrittingCaseManagementRequest(javax.xml.ws.Holder<SimplefrUnderwrittingCaseManagementRequest> simplefrUnderwrittingCaseManagementRequest) { 
        LOG.info("Executing operation simplefrUnderwrittingCaseManagementRequest");
        System.out.println(simplefrUnderwrittingCaseManagementRequest.value);
        try {
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.scortelemed.schemas.simplefr.SimplefrUnderwrittingCaseManagementService#simplefrUnderwrittingCasesResultsRequest(com.scortelemed.schemas.simplefr.SimplefrUnderwrittingCasesResultsRequest  simplefrUnderwrittingCasesResultsRequest )*
     */
    public com.scortelemed.schemas.simplefr.SimplefrUnderwrittingCasesResultsResponse simplefrUnderwrittingCasesResultsRequest(SimplefrUnderwrittingCasesResultsRequest simplefrUnderwrittingCasesResultsRequest) { 
        LOG.info("Executing operation simplefrUnderwrittingCasesResultsRequest");
        System.out.println(simplefrUnderwrittingCasesResultsRequest);
        try {
            com.scortelemed.schemas.simplefr.SimplefrUnderwrittingCasesResultsResponse _return = new com.scortelemed.schemas.simplefr.SimplefrUnderwrittingCasesResultsResponse();
            com.scortelemed.schemas.simplefr.StatusType _returnStatus = com.scortelemed.schemas.simplefr.StatusType.OK;
            _return.setStatus(_returnStatus);
            _return.setDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-11-07T16:41:11.575+01:00"));
            _return.setNotes("Notes-649813381");
            java.util.List<com.scortelemed.schemas.simplefr.ResultsBasicType> _returnResults = new java.util.ArrayList<com.scortelemed.schemas.simplefr.ResultsBasicType>();
            com.scortelemed.schemas.simplefr.ResultsBasicType _returnResultsVal1 = new com.scortelemed.schemas.simplefr.ResultsBasicType();
            _returnResultsVal1.setProductCode("ProductCode-1548578812");
            _returnResultsVal1.setRequestNumber("RequestNumber230565320");
            _returnResultsVal1.setPolicyNumber("PolicyNumber53448652");
            _returnResultsVal1.setCertificateNumber("CertificateNumber-941934858");
            _returnResultsVal1.setRequestDate("RequestDate-1528730467");
            com.scortelemed.schemas.simplefr.RequestStateType _returnResultsVal1RequestState = com.scortelemed.schemas.simplefr.RequestStateType.CANCELLED;
            _returnResultsVal1.setRequestState(_returnResultsVal1RequestState);
            _returnResultsVal1.setFiscalIdentificationNumber("FiscalIdentificationNumber-216202248");
            com.scortelemed.schemas.simplefr.BenefitsType _returnResultsVal1UnderwritingResults = new com.scortelemed.schemas.simplefr.BenefitsType();
            com.scortelemed.schemas.simplefr.BenefictNameType _returnResultsVal1UnderwritingResultsBenefictName = com.scortelemed.schemas.simplefr.BenefictNameType.DEAD;
            _returnResultsVal1UnderwritingResults.setBenefictName(_returnResultsVal1UnderwritingResultsBenefictName);
            _returnResultsVal1UnderwritingResults.setBenefictCode("BenefictCode-1977302665");
            _returnResultsVal1UnderwritingResults.setBenefictCapital("BenefictCapital162799210");
            com.scortelemed.schemas.simplefr.BenefictResultType _returnResultsVal1UnderwritingResultsBenefictResult = new com.scortelemed.schemas.simplefr.BenefictResultType();
            com.scortelemed.schemas.simplefr.BenefictNameType _returnResultsVal1UnderwritingResultsBenefictResultResult = com.scortelemed.schemas.simplefr.BenefictNameType.DISABILITY_90;
            _returnResultsVal1UnderwritingResultsBenefictResult.setResult(_returnResultsVal1UnderwritingResultsBenefictResultResult);
            _returnResultsVal1UnderwritingResultsBenefictResult.setPremiumLoading("PremiumLoading-1978014937");
            _returnResultsVal1UnderwritingResultsBenefictResult.setCapitalLoading("CapitalLoading-2000846414");
            java.util.List<java.lang.String> _returnResultsVal1UnderwritingResultsBenefictResultTemporalLoading = new java.util.ArrayList<java.lang.String>();
            _returnResultsVal1UnderwritingResultsBenefictResult.getTemporalLoading().addAll(_returnResultsVal1UnderwritingResultsBenefictResultTemporalLoading);
            java.util.List<java.lang.String> _returnResultsVal1UnderwritingResultsBenefictResultExclusions = new java.util.ArrayList<java.lang.String>();
            _returnResultsVal1UnderwritingResultsBenefictResult.getExclusions().addAll(_returnResultsVal1UnderwritingResultsBenefictResultExclusions);
            java.util.List<java.lang.String> _returnResultsVal1UnderwritingResultsBenefictResultMedicalReports = new java.util.ArrayList<java.lang.String>();
            _returnResultsVal1UnderwritingResultsBenefictResult.getMedicalReports().addAll(_returnResultsVal1UnderwritingResultsBenefictResultMedicalReports);
            java.util.List<java.lang.String> _returnResultsVal1UnderwritingResultsBenefictResultNotes = new java.util.ArrayList<java.lang.String>();
            _returnResultsVal1UnderwritingResultsBenefictResult.getNotes().addAll(_returnResultsVal1UnderwritingResultsBenefictResultNotes);
            _returnResultsVal1UnderwritingResults.setBenefictResult(_returnResultsVal1UnderwritingResultsBenefictResult);
            _returnResultsVal1.setUnderwritingResults(_returnResultsVal1UnderwritingResults);
            _returnResultsVal1.setZip("Zip-1101686071");
            _returnResults.add(_returnResultsVal1);
            _return.getResults().addAll(_returnResults);
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
