
package com.scortelemed.schemas.simplefr;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebParam.Mode;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.1
 * Tue Nov 07 16:41:11 CET 2017
 * Generated source version: 2.1
 * 
 */

@WebService(targetNamespace = "http://www.scortelemed.com/schemas/simplefr", name = "SimplefrUnderwrittingCaseManagementService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)

public interface SimplefrUnderwrittingCaseManagementService {

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebMethod
    public void simplefrUnderwrittingCaseManagementRequest(
        @WebParam(partName = "SimplefrUnderwrittingCaseManagementRequest", mode = WebParam.Mode.INOUT, name = "SimplefrUnderwrittingCaseManagementRequest", targetNamespace = "http://www.scortelemed.com/schemas/simplefr")
        javax.xml.ws.Holder<SimplefrUnderwrittingCaseManagementRequest> simplefrUnderwrittingCaseManagementRequest
    );

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "SimplefrUnderwrittingCasesResultsResponse", targetNamespace = "http://www.scortelemed.com/schemas/simplefr", partName = "SimplefrUnderwrittingCasesResultsResponse")
    @WebMethod
    public SimplefrUnderwrittingCasesResultsResponse simplefrUnderwrittingCasesResultsRequest(
        @WebParam(partName = "SimplefrUnderwrittingCasesResultsRequest", name = "SimplefrUnderwrittingCasesResultsRequest", targetNamespace = "http://www.scortelemed.com/schemas/simplefr")
        SimplefrUnderwrittingCasesResultsRequest simplefrUnderwrittingCasesResultsRequest
    );
}
