
package com.scortelemed.schemas.simplefr;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 2.1
 * Tue Nov 07 16:41:11 CET 2017
 * Generated source version: 2.1
 * 
 */

@WebServiceClient(name = "SimplefrUnderwrittingCaseManagementServiceService", targetNamespace = "http://www.scortelemed.com/schemas/simplefr", wsdlLocation = "http://localhost:8080/scorWebservice/services/simplefr/SimplefrUnderwrittingCaseManagement?wsdl")
public class SimplefrUnderwrittingCaseManagementServiceService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://www.scortelemed.com/schemas/simplefr", "SimplefrUnderwrittingCaseManagementServiceService");
    public final static QName SimplefrUnderwrittingCaseManagementServicePort = new QName("http://www.scortelemed.com/schemas/simplefr", "SimplefrUnderwrittingCaseManagementServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/scorWebservice/services/simplefr/SimplefrUnderwrittingCaseManagement?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://localhost:8080/scorWebservice/services/simplefr/SimplefrUnderwrittingCaseManagement?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public SimplefrUnderwrittingCaseManagementServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SimplefrUnderwrittingCaseManagementServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SimplefrUnderwrittingCaseManagementServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns SimplefrUnderwrittingCaseManagementService
     */
    @WebEndpoint(name = "SimplefrUnderwrittingCaseManagementServicePort")
    public SimplefrUnderwrittingCaseManagementService getSimplefrUnderwrittingCaseManagementServicePort() {
        return super.getPort(SimplefrUnderwrittingCaseManagementServicePort, SimplefrUnderwrittingCaseManagementService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SimplefrUnderwrittingCaseManagementService
     */
    @WebEndpoint(name = "SimplefrUnderwrittingCaseManagementServicePort")
    public SimplefrUnderwrittingCaseManagementService getSimplefrUnderwrittingCaseManagementServicePort(WebServiceFeature... features) {
        return super.getPort(SimplefrUnderwrittingCaseManagementServicePort, SimplefrUnderwrittingCaseManagementService.class, features);
    }

}
