
package com.scortelemed.schemas.simplefr;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebParam.Mode;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.1
 * Tue Nov 07 16:41:11 CET 2017
 * Generated source version: 2.1
 * 
 */

public final class SimplefrUnderwrittingCaseManagementService_SimplefrUnderwrittingCaseManagementServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://www.scortelemed.com/schemas/simplefr", "SimplefrUnderwrittingCaseManagementServiceService");

    private SimplefrUnderwrittingCaseManagementService_SimplefrUnderwrittingCaseManagementServicePort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = SimplefrUnderwrittingCaseManagementServiceService.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        SimplefrUnderwrittingCaseManagementServiceService ss = new SimplefrUnderwrittingCaseManagementServiceService(wsdlURL, SERVICE_NAME);
        SimplefrUnderwrittingCaseManagementService port = ss.getSimplefrUnderwrittingCaseManagementServicePort();  
        
        {
        System.out.println("Invoking simplefrUnderwrittingCaseManagementRequest...");
        com.scortelemed.schemas.simplefr.SimplefrUnderwrittingCaseManagementRequest _simplefrUnderwrittingCaseManagementRequest_simplefrUnderwrittingCaseManagementRequestVal = new com.scortelemed.schemas.simplefr.SimplefrUnderwrittingCaseManagementRequest();
        com.scortelemed.schemas.simplefr.SimplefrUnderwrittingCaseManagementRequest.CandidateInformation _simplefrUnderwrittingCaseManagementRequest_simplefrUnderwrittingCaseManagementRequestValCandidateInformation = new com.scortelemed.schemas.simplefr.SimplefrUnderwrittingCaseManagementRequest.CandidateInformation();
        _simplefrUnderwrittingCaseManagementRequest_simplefrUnderwrittingCaseManagementRequestValCandidateInformation.setProductCode("ProductCode191580825");
        _simplefrUnderwrittingCaseManagementRequest_simplefrUnderwrittingCaseManagementRequestValCandidateInformation.setRequestNumber("RequestNumber833964584");
        _simplefrUnderwrittingCaseManagementRequest_simplefrUnderwrittingCaseManagementRequestValCandidateInformation.setPolicyNumber("PolicyNumber-1525623100");
        _simplefrUnderwrittingCaseManagementRequest_simplefrUnderwrittingCaseManagementRequestValCandidateInformation.setCertificateNumber("CertificateNumber-912780562");
        _simplefrUnderwrittingCaseManagementRequest_simplefrUnderwrittingCaseManagementRequestValCandidateInformation.setRequestDate("RequestDate227884470");
        _simplefrUnderwrittingCaseManagementRequest_simplefrUnderwrittingCaseManagementRequestValCandidateInformation.setPassword("Password1074803493");
        _simplefrUnderwrittingCaseManagementRequest_simplefrUnderwrittingCaseManagementRequestValCandidateInformation.setRequestState("RequestState-1521548993");
        _simplefrUnderwrittingCaseManagementRequest_simplefrUnderwrittingCaseManagementRequestValCandidateInformation.setName("Name-2025040089");
        _simplefrUnderwrittingCaseManagementRequest_simplefrUnderwrittingCaseManagementRequestValCandidateInformation.setSurname("Surname-1517086941");
        _simplefrUnderwrittingCaseManagementRequest_simplefrUnderwrittingCaseManagementRequestValCandidateInformation.setAddress("Address-2007849907");
        _simplefrUnderwrittingCaseManagementRequest_simplefrUnderwrittingCaseManagementRequestValCandidateInformation.setPostalCode("PostalCode1989882902");
        _simplefrUnderwrittingCaseManagementRequest_simplefrUnderwrittingCaseManagementRequestValCandidateInformation.setCity("City-938654602");
        _simplefrUnderwrittingCaseManagementRequest_simplefrUnderwrittingCaseManagementRequestValCandidateInformation.setProvince("Province347351020");
        _simplefrUnderwrittingCaseManagementRequest_simplefrUnderwrittingCaseManagementRequestValCandidateInformation.setCountry("Country398399119");
        _simplefrUnderwrittingCaseManagementRequest_simplefrUnderwrittingCaseManagementRequestValCandidateInformation.setPhoneNumber1("PhoneNumber1-444092973");
        _simplefrUnderwrittingCaseManagementRequest_simplefrUnderwrittingCaseManagementRequestValCandidateInformation.setPhoneNumber2("PhoneNumber2-167689413");
        _simplefrUnderwrittingCaseManagementRequest_simplefrUnderwrittingCaseManagementRequestValCandidateInformation.setMobileNumber("MobileNumber-1592720233");
        _simplefrUnderwrittingCaseManagementRequest_simplefrUnderwrittingCaseManagementRequestValCandidateInformation.setEmail("Email1898949882");
        _simplefrUnderwrittingCaseManagementRequest_simplefrUnderwrittingCaseManagementRequestValCandidateInformation.setBirthDate("BirthDate541988412");
        _simplefrUnderwrittingCaseManagementRequest_simplefrUnderwrittingCaseManagementRequestValCandidateInformation.setActuarialAge("ActuarialAge474006931");
        _simplefrUnderwrittingCaseManagementRequest_simplefrUnderwrittingCaseManagementRequestValCandidateInformation.setBirthCity("BirthCity1203813240");
        _simplefrUnderwrittingCaseManagementRequest_simplefrUnderwrittingCaseManagementRequestValCandidateInformation.setFiscalIdentificationNumber("FiscalIdentificationNumber704499329");
        _simplefrUnderwrittingCaseManagementRequest_simplefrUnderwrittingCaseManagementRequestValCandidateInformation.setAgency("Agency1380060872");
        _simplefrUnderwrittingCaseManagementRequest_simplefrUnderwrittingCaseManagementRequestValCandidateInformation.setAgent("Agent-950665032");
        _simplefrUnderwrittingCaseManagementRequest_simplefrUnderwrittingCaseManagementRequestValCandidateInformation.setAgentPhone("AgentPhone-1275421630");
        _simplefrUnderwrittingCaseManagementRequest_simplefrUnderwrittingCaseManagementRequestValCandidateInformation.setAgentEmail("AgentEmail-786229250");
        com.scortelemed.schemas.simplefr.GenderType _simplefrUnderwrittingCaseManagementRequest_simplefrUnderwrittingCaseManagementRequestValCandidateInformationGender = com.scortelemed.schemas.simplefr.GenderType.H;
        _simplefrUnderwrittingCaseManagementRequest_simplefrUnderwrittingCaseManagementRequestValCandidateInformation.setGender(_simplefrUnderwrittingCaseManagementRequest_simplefrUnderwrittingCaseManagementRequestValCandidateInformationGender);
        com.scortelemed.schemas.simplefr.CivilStateType _simplefrUnderwrittingCaseManagementRequest_simplefrUnderwrittingCaseManagementRequestValCandidateInformationCivilState = com.scortelemed.schemas.simplefr.CivilStateType.C;
        _simplefrUnderwrittingCaseManagementRequest_simplefrUnderwrittingCaseManagementRequestValCandidateInformation.setCivilState(_simplefrUnderwrittingCaseManagementRequest_simplefrUnderwrittingCaseManagementRequestValCandidateInformationCivilState);
        _simplefrUnderwrittingCaseManagementRequest_simplefrUnderwrittingCaseManagementRequestValCandidateInformation.setCustomerType("CustomerType1255433441");
        com.scortelemed.schemas.simplefr.ContactTimeType _simplefrUnderwrittingCaseManagementRequest_simplefrUnderwrittingCaseManagementRequestValCandidateInformationContactTime = com.scortelemed.schemas.simplefr.ContactTimeType.N;
        _simplefrUnderwrittingCaseManagementRequest_simplefrUnderwrittingCaseManagementRequestValCandidateInformation.setContactTime(_simplefrUnderwrittingCaseManagementRequest_simplefrUnderwrittingCaseManagementRequestValCandidateInformationContactTime);
        _simplefrUnderwrittingCaseManagementRequest_simplefrUnderwrittingCaseManagementRequestValCandidateInformation.setComments("Comments1199895551");
        _simplefrUnderwrittingCaseManagementRequest_simplefrUnderwrittingCaseManagementRequestValCandidateInformation.setEUWReferenceCode("EUWReferenceCode-691510782");
        _simplefrUnderwrittingCaseManagementRequest_simplefrUnderwrittingCaseManagementRequestVal.setCandidateInformation(_simplefrUnderwrittingCaseManagementRequest_simplefrUnderwrittingCaseManagementRequestValCandidateInformation);
        java.util.List<com.scortelemed.schemas.simplefr.SimplefrUnderwrittingCaseManagementRequest.PreviousQuestions> _simplefrUnderwrittingCaseManagementRequest_simplefrUnderwrittingCaseManagementRequestValPreviousQuestions = new java.util.ArrayList<com.scortelemed.schemas.simplefr.SimplefrUnderwrittingCaseManagementRequest.PreviousQuestions>();
        com.scortelemed.schemas.simplefr.SimplefrUnderwrittingCaseManagementRequest.PreviousQuestions _simplefrUnderwrittingCaseManagementRequest_simplefrUnderwrittingCaseManagementRequestValPreviousQuestionsVal1 = new com.scortelemed.schemas.simplefr.SimplefrUnderwrittingCaseManagementRequest.PreviousQuestions();
        com.scortelemed.schemas.simplefr.QuestionDataType _simplefrUnderwrittingCaseManagementRequest_simplefrUnderwrittingCaseManagementRequestValPreviousQuestionsVal1DataType = com.scortelemed.schemas.simplefr.QuestionDataType.DATE;
        _simplefrUnderwrittingCaseManagementRequest_simplefrUnderwrittingCaseManagementRequestValPreviousQuestionsVal1.setDataType(_simplefrUnderwrittingCaseManagementRequest_simplefrUnderwrittingCaseManagementRequestValPreviousQuestionsVal1DataType);
        _simplefrUnderwrittingCaseManagementRequest_simplefrUnderwrittingCaseManagementRequestValPreviousQuestionsVal1.setAnswerCode("AnswerCode-452191831");
        _simplefrUnderwrittingCaseManagementRequest_simplefrUnderwrittingCaseManagementRequestValPreviousQuestionsVal1.setQuestion("Question1814830486");
        _simplefrUnderwrittingCaseManagementRequest_simplefrUnderwrittingCaseManagementRequestValPreviousQuestionsVal1.setAnswer("Answer-773087689");
        _simplefrUnderwrittingCaseManagementRequest_simplefrUnderwrittingCaseManagementRequestValPreviousQuestions.add(_simplefrUnderwrittingCaseManagementRequest_simplefrUnderwrittingCaseManagementRequestValPreviousQuestionsVal1);
        _simplefrUnderwrittingCaseManagementRequest_simplefrUnderwrittingCaseManagementRequestVal.getPreviousQuestions().addAll(_simplefrUnderwrittingCaseManagementRequest_simplefrUnderwrittingCaseManagementRequestValPreviousQuestions);
        java.util.List<com.scortelemed.schemas.simplefr.SimplefrUnderwrittingCaseManagementRequest.Services> _simplefrUnderwrittingCaseManagementRequest_simplefrUnderwrittingCaseManagementRequestValServices = new java.util.ArrayList<com.scortelemed.schemas.simplefr.SimplefrUnderwrittingCaseManagementRequest.Services>();
        com.scortelemed.schemas.simplefr.SimplefrUnderwrittingCaseManagementRequest.Services _simplefrUnderwrittingCaseManagementRequest_simplefrUnderwrittingCaseManagementRequestValServicesVal1 = new com.scortelemed.schemas.simplefr.SimplefrUnderwrittingCaseManagementRequest.Services();
        _simplefrUnderwrittingCaseManagementRequest_simplefrUnderwrittingCaseManagementRequestValServicesVal1.setServiceType("ServiceType-73892347");
        _simplefrUnderwrittingCaseManagementRequest_simplefrUnderwrittingCaseManagementRequestValServicesVal1.setServiceCode("ServiceCode1905163962");
        _simplefrUnderwrittingCaseManagementRequest_simplefrUnderwrittingCaseManagementRequestValServicesVal1.setServiceDescription("ServiceDescription1814351053");
        _simplefrUnderwrittingCaseManagementRequest_simplefrUnderwrittingCaseManagementRequestValServices.add(_simplefrUnderwrittingCaseManagementRequest_simplefrUnderwrittingCaseManagementRequestValServicesVal1);
        _simplefrUnderwrittingCaseManagementRequest_simplefrUnderwrittingCaseManagementRequestVal.getServices().addAll(_simplefrUnderwrittingCaseManagementRequest_simplefrUnderwrittingCaseManagementRequestValServices);
        com.scortelemed.schemas.simplefr.BenefitsType _simplefrUnderwrittingCaseManagementRequest_simplefrUnderwrittingCaseManagementRequestValBenefits = new com.scortelemed.schemas.simplefr.BenefitsType();
        com.scortelemed.schemas.simplefr.BenefictNameType _simplefrUnderwrittingCaseManagementRequest_simplefrUnderwrittingCaseManagementRequestValBenefitsBenefictName = com.scortelemed.schemas.simplefr.BenefictNameType.ACCIDENTAL_DEAD;
        _simplefrUnderwrittingCaseManagementRequest_simplefrUnderwrittingCaseManagementRequestValBenefits.setBenefictName(_simplefrUnderwrittingCaseManagementRequest_simplefrUnderwrittingCaseManagementRequestValBenefitsBenefictName);
        _simplefrUnderwrittingCaseManagementRequest_simplefrUnderwrittingCaseManagementRequestValBenefits.setBenefictCode("BenefictCode-793125285");
        _simplefrUnderwrittingCaseManagementRequest_simplefrUnderwrittingCaseManagementRequestValBenefits.setBenefictCapital("BenefictCapital432567120");
        com.scortelemed.schemas.simplefr.BenefictResultType _simplefrUnderwrittingCaseManagementRequest_simplefrUnderwrittingCaseManagementRequestValBenefitsBenefictResult = new com.scortelemed.schemas.simplefr.BenefictResultType();
        com.scortelemed.schemas.simplefr.BenefictNameType _simplefrUnderwrittingCaseManagementRequest_simplefrUnderwrittingCaseManagementRequestValBenefitsBenefictResultResult = com.scortelemed.schemas.simplefr.BenefictNameType.DEPENDENCY;
        _simplefrUnderwrittingCaseManagementRequest_simplefrUnderwrittingCaseManagementRequestValBenefitsBenefictResult.setResult(_simplefrUnderwrittingCaseManagementRequest_simplefrUnderwrittingCaseManagementRequestValBenefitsBenefictResultResult);
        _simplefrUnderwrittingCaseManagementRequest_simplefrUnderwrittingCaseManagementRequestValBenefitsBenefictResult.setPremiumLoading("PremiumLoading919876975");
        _simplefrUnderwrittingCaseManagementRequest_simplefrUnderwrittingCaseManagementRequestValBenefitsBenefictResult.setCapitalLoading("CapitalLoading-2133908334");
        java.util.List<java.lang.String> _simplefrUnderwrittingCaseManagementRequest_simplefrUnderwrittingCaseManagementRequestValBenefitsBenefictResultTemporalLoading = new java.util.ArrayList<java.lang.String>();
        _simplefrUnderwrittingCaseManagementRequest_simplefrUnderwrittingCaseManagementRequestValBenefitsBenefictResult.getTemporalLoading().addAll(_simplefrUnderwrittingCaseManagementRequest_simplefrUnderwrittingCaseManagementRequestValBenefitsBenefictResultTemporalLoading);
        java.util.List<java.lang.String> _simplefrUnderwrittingCaseManagementRequest_simplefrUnderwrittingCaseManagementRequestValBenefitsBenefictResultExclusions = new java.util.ArrayList<java.lang.String>();
        _simplefrUnderwrittingCaseManagementRequest_simplefrUnderwrittingCaseManagementRequestValBenefitsBenefictResult.getExclusions().addAll(_simplefrUnderwrittingCaseManagementRequest_simplefrUnderwrittingCaseManagementRequestValBenefitsBenefictResultExclusions);
        java.util.List<java.lang.String> _simplefrUnderwrittingCaseManagementRequest_simplefrUnderwrittingCaseManagementRequestValBenefitsBenefictResultMedicalReports = new java.util.ArrayList<java.lang.String>();
        _simplefrUnderwrittingCaseManagementRequest_simplefrUnderwrittingCaseManagementRequestValBenefitsBenefictResult.getMedicalReports().addAll(_simplefrUnderwrittingCaseManagementRequest_simplefrUnderwrittingCaseManagementRequestValBenefitsBenefictResultMedicalReports);
        java.util.List<java.lang.String> _simplefrUnderwrittingCaseManagementRequest_simplefrUnderwrittingCaseManagementRequestValBenefitsBenefictResultNotes = new java.util.ArrayList<java.lang.String>();
        _simplefrUnderwrittingCaseManagementRequest_simplefrUnderwrittingCaseManagementRequestValBenefitsBenefictResult.getNotes().addAll(_simplefrUnderwrittingCaseManagementRequest_simplefrUnderwrittingCaseManagementRequestValBenefitsBenefictResultNotes);
        _simplefrUnderwrittingCaseManagementRequest_simplefrUnderwrittingCaseManagementRequestValBenefits.setBenefictResult(_simplefrUnderwrittingCaseManagementRequest_simplefrUnderwrittingCaseManagementRequestValBenefitsBenefictResult);
        _simplefrUnderwrittingCaseManagementRequest_simplefrUnderwrittingCaseManagementRequestVal.setBenefits(_simplefrUnderwrittingCaseManagementRequest_simplefrUnderwrittingCaseManagementRequestValBenefits);
        javax.xml.ws.Holder<com.scortelemed.schemas.simplefr.SimplefrUnderwrittingCaseManagementRequest> _simplefrUnderwrittingCaseManagementRequest_simplefrUnderwrittingCaseManagementRequest = new javax.xml.ws.Holder<com.scortelemed.schemas.simplefr.SimplefrUnderwrittingCaseManagementRequest>(_simplefrUnderwrittingCaseManagementRequest_simplefrUnderwrittingCaseManagementRequestVal);
        port.simplefrUnderwrittingCaseManagementRequest(_simplefrUnderwrittingCaseManagementRequest_simplefrUnderwrittingCaseManagementRequest);

        System.out.println("simplefrUnderwrittingCaseManagementRequest._simplefrUnderwrittingCaseManagementRequest_simplefrUnderwrittingCaseManagementRequest=" + _simplefrUnderwrittingCaseManagementRequest_simplefrUnderwrittingCaseManagementRequest.value);

        }
        {
        System.out.println("Invoking simplefrUnderwrittingCasesResultsRequest...");
        com.scortelemed.schemas.simplefr.SimplefrUnderwrittingCasesResultsRequest _simplefrUnderwrittingCasesResultsRequest_simplefrUnderwrittingCasesResultsRequest = new com.scortelemed.schemas.simplefr.SimplefrUnderwrittingCasesResultsRequest();
        _simplefrUnderwrittingCasesResultsRequest_simplefrUnderwrittingCasesResultsRequest.setDateStart(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-11-07T16:41:11.543+01:00"));
        _simplefrUnderwrittingCasesResultsRequest_simplefrUnderwrittingCasesResultsRequest.setDateEnd(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-11-07T16:41:11.559+01:00"));
        com.scortelemed.schemas.simplefr.SimplefrUnderwrittingCasesResultsResponse _simplefrUnderwrittingCasesResultsRequest__return = port.simplefrUnderwrittingCasesResultsRequest(_simplefrUnderwrittingCasesResultsRequest_simplefrUnderwrittingCasesResultsRequest);
        System.out.println("simplefrUnderwrittingCasesResultsRequest.result=" + _simplefrUnderwrittingCasesResultsRequest__return);


        }

        System.exit(0);
    }

}
