
package com.scortelemed.schemas.nn;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.1
 * Wed Nov 28 13:10:27 CET 2018
 * Generated source version: 2.1
 * 
 */

@WebService(targetNamespace = "http://www.scortelemed.com/schemas/nn", name = "NnUnderwrittingCaseManagementService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = ParameterStyle.BARE)

public interface NnUnderwrittingCaseManagementService {

    @SOAPBinding(parameterStyle = ParameterStyle.BARE)
    @WebResult(name = "ResultadoReconocimientoMedicoResponse", targetNamespace = "http://www.scortelemed.com/schemas/nn", partName = "ResultadoReconocimientoMedicoResponse")
    @WebMethod
    public ResultadoReconocimientoMedicoResponse resultadoReconocimientoMedico(
            @WebParam(partName = "ResultadoReconocimientoMedicoRequest", name = "ResultadoReconocimientoMedicoRequest", targetNamespace = "http://www.scortelemed.com/schemas/nn")
                    ResultadoReconocimientoMedicoRequest resultadoReconocimientoMedicoRequest
    );

    @SOAPBinding(parameterStyle = ParameterStyle.BARE)
    @WebResult(name = "GestionReconocimientoMedicoResponse", targetNamespace = "http://www.scortelemed.com/schemas/nn", partName = "GestionReconocimientoMedicoResponse")
    @WebMethod
    public GestionReconocimientoMedicoResponse gestionReconocimientoMedico(
            @WebParam(partName = "GestionReconocimientoMedicoRequest", name = "GestionReconocimientoMedicoRequest", targetNamespace = "http://www.scortelemed.com/schemas/nn")
                    GestionReconocimientoMedicoRequest gestionReconocimientoMedicoRequest
    );
}
