
package com.scortelemed.schemas.nn;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 2.1
 * Wed Nov 28 13:10:27 CET 2018
 * Generated source version: 2.1
 * 
 */

@WebServiceClient(name = "NnUnderwrittingCaseManagementServiceService", targetNamespace = "http://www.scortelemed.com/schemas/nn", wsdlLocation = "http://172.28.0.1:9095/webservicessoap/services/nn/NnUnderwrittingCaseManagement?wsdl")
public class NnUnderwrittingCaseManagementServiceService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://www.scortelemed.com/schemas/nn", "NnUnderwrittingCaseManagementServiceService");
    public final static QName NnUnderwrittingCaseManagementServicePort = new QName("http://www.scortelemed.com/schemas/nn", "NnUnderwrittingCaseManagementServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://172.28.0.1:9095/webservicessoap/services/nn/NnUnderwrittingCaseManagement?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://172.28.0.1:9095/webservicessoap/services/nn/NnUnderwrittingCaseManagement?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public NnUnderwrittingCaseManagementServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public NnUnderwrittingCaseManagementServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NnUnderwrittingCaseManagementServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns NnUnderwrittingCaseManagementService
     */
    @WebEndpoint(name = "NnUnderwrittingCaseManagementServicePort")
    public NnUnderwrittingCaseManagementService getNnUnderwrittingCaseManagementServicePort() {
        return super.getPort(NnUnderwrittingCaseManagementServicePort, NnUnderwrittingCaseManagementService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns NnUnderwrittingCaseManagementService
     */
    @WebEndpoint(name = "NnUnderwrittingCaseManagementServicePort")
    public NnUnderwrittingCaseManagementService getNnUnderwrittingCaseManagementServicePort(WebServiceFeature... features) {
        return super.getPort(NnUnderwrittingCaseManagementServicePort, NnUnderwrittingCaseManagementService.class, features);
    }

}
