
package com.scortelemed.schemas.nn;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.1
 * Wed Nov 28 13:10:27 CET 2018
 * Generated source version: 2.1
 * 
 */

public final class NnUnderwrittingCaseManagementService_NnUnderwrittingCaseManagementServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://www.scortelemed.com/schemas/nn", "NnUnderwrittingCaseManagementServiceService");

    private NnUnderwrittingCaseManagementService_NnUnderwrittingCaseManagementServicePort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = NnUnderwrittingCaseManagementServiceService.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        NnUnderwrittingCaseManagementServiceService ss = new NnUnderwrittingCaseManagementServiceService(wsdlURL, SERVICE_NAME);
        NnUnderwrittingCaseManagementService port = ss.getNnUnderwrittingCaseManagementServicePort();  
        
        {
        System.out.println("Invoking resultadoReconocimientoMedico...");
        com.scortelemed.schemas.nn.ResultadoReconocimientoMedicoRequest _resultadoReconocimientoMedico_resultadoReconocimientoMedicoRequest = new com.scortelemed.schemas.nn.ResultadoReconocimientoMedicoRequest();
        _resultadoReconocimientoMedico_resultadoReconocimientoMedicoRequest.setDateStart(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-11-28T13:10:27.525+01:00"));
        _resultadoReconocimientoMedico_resultadoReconocimientoMedicoRequest.setDateEnd(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-11-28T13:10:27.525+01:00"));
        ResultadoReconocimientoMedicoResponse _resultadoReconocimientoMedico__return = port.resultadoReconocimientoMedico(_resultadoReconocimientoMedico_resultadoReconocimientoMedicoRequest);
        System.out.println("resultadoReconocimientoMedico.result=" + _resultadoReconocimientoMedico__return);


        }
        {
        System.out.println("Invoking gestionReconocimientoMedico...");
        GestionReconocimientoMedicoRequest _gestionReconocimientoMedico_gestionReconocimientoMedicoRequest = new GestionReconocimientoMedicoRequest();
        GestionReconocimientoMedicoRequest.CandidateInformation _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformation = new GestionReconocimientoMedicoRequest.CandidateInformation();
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformation.setProductCode("ProductCode-1272422830");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformation.setRequestNumber("RequestNumber1804505989");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformation.setPolicyNumber("PolicyNumber-1899497675");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformation.setCertificateNumber("CertificateNumber1076345177");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformation.setRequestDate("RequestDate1265413763");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformation.setPassword("Password374441186");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformation.setRequestState("RequestState853431144");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformation.setName("Name131974314");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformation.setSurname("Surname-1159351692");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformation.setAddress("Address-1332153111");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformation.setPostalCode("PostalCode-782951269");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformation.setCity("City599735685");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformation.setProvince("Province1459186122");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformation.setCountry("Country950031173");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformation.setPhoneNumber1("PhoneNumber1-1214634956");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformation.setPhoneNumber2("PhoneNumber21522473142");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformation.setMobileNumber("MobileNumber-374856562");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformation.setEmail("Email-795904671");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformation.setBirthDate("BirthDate1690440907");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformation.setActuarialAge("ActuarialAge697802292");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformation.setBirthCity("BirthCity64314911");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformation.setFiscalIdentificationNumber("FiscalIdentificationNumber1076299857");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformation.setAgency("Agency1685571653");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformation.setAgent("Agent-1267202138");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformation.setAgentPhone("AgentPhone2051986281");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformation.setAgentEmail("AgentEmail514309362");
        com.scortelemed.schemas.nn.GenderType _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformationGender = com.scortelemed.schemas.nn.GenderType.M;
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformation.setGender(_gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformationGender);
        CivilStateType _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformationCivilState = CivilStateType.V;
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformation.setCivilState(_gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformationCivilState);
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformation.setCustomerType("CustomerType1366444118");
        com.scortelemed.schemas.nn.ContactTimeType _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformationContactTime = com.scortelemed.schemas.nn.ContactTimeType.T;
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformation.setContactTime(_gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformationContactTime);
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformation.setComments("Comments-1061551855");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformation.setEUWReferenceCode("EUWReferenceCode527703630");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequest.setCandidateInformation(_gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformation);
        java.util.List<GestionReconocimientoMedicoRequest.PreviousQuestions> _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestPreviousQuestions = new java.util.ArrayList<GestionReconocimientoMedicoRequest.PreviousQuestions>();
        GestionReconocimientoMedicoRequest.PreviousQuestions _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestPreviousQuestionsVal1 = new GestionReconocimientoMedicoRequest.PreviousQuestions();
        com.scortelemed.schemas.nn.QuestionDataType _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestPreviousQuestionsVal1DataType = com.scortelemed.schemas.nn.QuestionDataType.DATE;
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestPreviousQuestionsVal1.setDataType(_gestionReconocimientoMedico_gestionReconocimientoMedicoRequestPreviousQuestionsVal1DataType);
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestPreviousQuestionsVal1.setAnswerCode("AnswerCode-1091902906");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestPreviousQuestionsVal1.setQuestion("Question1973886668");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestPreviousQuestionsVal1.setAnswer("Answer2081316200");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestPreviousQuestions.add(_gestionReconocimientoMedico_gestionReconocimientoMedicoRequestPreviousQuestionsVal1);
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequest.getPreviousQuestions().addAll(_gestionReconocimientoMedico_gestionReconocimientoMedicoRequestPreviousQuestions);
        java.util.List<GestionReconocimientoMedicoRequest.Services> _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestServices = new java.util.ArrayList<GestionReconocimientoMedicoRequest.Services>();
        GestionReconocimientoMedicoRequest.Services _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestServicesVal1 = new GestionReconocimientoMedicoRequest.Services();
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestServicesVal1.setServiceType("ServiceType735883065");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestServicesVal1.setServiceCode("ServiceCode-1165683605");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestServicesVal1.setServiceDescription("ServiceDescription-1232868062");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestServices.add(_gestionReconocimientoMedico_gestionReconocimientoMedicoRequestServicesVal1);
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequest.getServices().addAll(_gestionReconocimientoMedico_gestionReconocimientoMedicoRequestServices);
        java.util.List<com.scortelemed.schemas.nn.BenefitsType> _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestBenefits = new java.util.ArrayList<com.scortelemed.schemas.nn.BenefitsType>();
        com.scortelemed.schemas.nn.BenefitsType _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestBenefitsVal1 = new com.scortelemed.schemas.nn.BenefitsType();
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestBenefitsVal1.setBenefictName("BenefictName2042004231");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestBenefitsVal1.setBenefictCode("BenefictCode1688314515");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestBenefitsVal1.setBenefictCapital("BenefictCapital-334554325");
        BenefictResultType _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestBenefitsVal1BenefictResult = new BenefictResultType();
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestBenefitsVal1BenefictResult.setDescResult("DescResult799131984");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestBenefitsVal1BenefictResult.setResultCode("ResultCode1480051648");
        BenefictNameType _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestBenefitsVal1BenefictResultResult = BenefictNameType.DISABILITY_90;
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestBenefitsVal1BenefictResult.setResult(_gestionReconocimientoMedico_gestionReconocimientoMedicoRequestBenefitsVal1BenefictResultResult);
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestBenefitsVal1BenefictResult.setPremiumLoading("PremiumLoading1071390516");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestBenefitsVal1BenefictResult.setCapitalLoading("CapitalLoading681055893");
        java.util.List<String> _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestBenefitsVal1BenefictResultTemporalLoading = new java.util.ArrayList<String>();
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestBenefitsVal1BenefictResult.getTemporalLoading().addAll(_gestionReconocimientoMedico_gestionReconocimientoMedicoRequestBenefitsVal1BenefictResultTemporalLoading);
        java.util.List<String> _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestBenefitsVal1BenefictResultExclusions = new java.util.ArrayList<String>();
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestBenefitsVal1BenefictResult.getExclusions().addAll(_gestionReconocimientoMedico_gestionReconocimientoMedicoRequestBenefitsVal1BenefictResultExclusions);
        java.util.List<String> _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestBenefitsVal1BenefictResultMedicalReports = new java.util.ArrayList<String>();
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestBenefitsVal1BenefictResult.getMedicalReports().addAll(_gestionReconocimientoMedico_gestionReconocimientoMedicoRequestBenefitsVal1BenefictResultMedicalReports);
        java.util.List<String> _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestBenefitsVal1BenefictResultNotes = new java.util.ArrayList<String>();
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestBenefitsVal1BenefictResult.getNotes().addAll(_gestionReconocimientoMedico_gestionReconocimientoMedicoRequestBenefitsVal1BenefictResultNotes);
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestBenefitsVal1.setBenefictResult(_gestionReconocimientoMedico_gestionReconocimientoMedicoRequestBenefitsVal1BenefictResult);
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestBenefits.add(_gestionReconocimientoMedico_gestionReconocimientoMedicoRequestBenefitsVal1);
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequest.getBenefits().addAll(_gestionReconocimientoMedico_gestionReconocimientoMedicoRequestBenefits);
        GestionReconocimientoMedicoResponse _gestionReconocimientoMedico__return = port.gestionReconocimientoMedico(_gestionReconocimientoMedico_gestionReconocimientoMedicoRequest);
        System.out.println("gestionReconocimientoMedico.result=" + _gestionReconocimientoMedico__return);


        }

        System.exit(0);
    }

}
