
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.scortelemed.schemas.nn;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.1
 * Wed Nov 28 13:10:27 CET 2018
 * Generated source version: 2.1
 * 
 */

@WebService(name = "NnUnderwrittingCaseManagementService",
                      serviceName = "NnUnderwrittingCaseManagementServiceService",
                      portName = "NnUnderwrittingCaseManagementServicePort",
                      targetNamespace = "http://www.scortelemed.com/schemas/nn", 
                      wsdlLocation = "http://172.28.0.1:9095/webservicessoap/services/nn/NnUnderwrittingCaseManagement?wsdl",
                      endpointInterface = "com.scortelemed.schemas.nn.NnUnderwrittingCaseManagementService")
                      
public class NnUnderwrittingCaseManagementServiceImpl implements NnUnderwrittingCaseManagementService {

    private static final Logger LOG = Logger.getLogger(NnUnderwrittingCaseManagementServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see com.scortelemed.schemas.nn.NnUnderwrittingCaseManagementService#resultadoReconocimientoMedico(com.scortelemed.schemas.nn.ResultadoReconocimientoMedicoRequest  resultadoReconocimientoMedicoRequest )*
     */
    public ResultadoReconocimientoMedicoResponse resultadoReconocimientoMedico(ResultadoReconocimientoMedicoRequest resultadoReconocimientoMedicoRequest) {
        LOG.info("Executing operation resultadoReconocimientoMedico");
        System.out.println(resultadoReconocimientoMedicoRequest);
        try {
            ResultadoReconocimientoMedicoResponse _return = new ResultadoReconocimientoMedicoResponse();
            _return.setDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-11-28T13:10:27.541+01:00"));
            com.scortelemed.schemas.nn.StatusType _returnStatus = com.scortelemed.schemas.nn.StatusType.OK;
            _return.setStatus(_returnStatus);
            _return.setMessage("Message-1731299332");
            _return.setCode(799472916);
            java.util.List<ResultadoReconocimientoMedicoResponse.Expediente> _returnExpediente = new java.util.ArrayList<ResultadoReconocimientoMedicoResponse.Expediente>();
            ResultadoReconocimientoMedicoResponse.Expediente _returnExpedienteVal1 = new ResultadoReconocimientoMedicoResponse.Expediente();
            _returnExpedienteVal1.setRequestDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-11-28T13:10:27.541+01:00"));
            _returnExpedienteVal1.setRequestNumber("RequestNumber-1848240891");
            com.scortelemed.schemas.nn.RequestStateType _returnExpedienteVal1RequestState = com.scortelemed.schemas.nn.RequestStateType.REJECTED;
            _returnExpedienteVal1.setRequestState(_returnExpedienteVal1RequestState);
            _returnExpedienteVal1.setProductCode("ProductCode22515430");
            _returnExpedienteVal1.setPolicyNumber("PolicyNumber-344884960");
            _returnExpedienteVal1.setCertificateNumber("CertificateNumber-2105880164");
            _returnExpedienteVal1.setFiscalIdentificationNumber("FiscalIdentificationNumber-663033177");
            _returnExpedienteVal1.setMobilePhone("MobilePhone462989656");
            _returnExpedienteVal1.setPhoneNumber1("PhoneNumber1-876065386");
            _returnExpedienteVal1.setPhoneNumber2("PhoneNumber21161003925");
            java.util.List<BenefitsType> _returnExpedienteVal1BenefitsList = new java.util.ArrayList<BenefitsType>();
            _returnExpedienteVal1.getBenefitsList().addAll(_returnExpedienteVal1BenefitsList);
            byte[] _returnExpedienteVal1Zip = new byte[] {};
            _returnExpedienteVal1.setZip(_returnExpedienteVal1Zip);
            _returnExpedienteVal1.setNotes("Notes-1321201738");
            _returnExpediente.add(_returnExpedienteVal1);
            _return.getExpediente().addAll(_returnExpediente);
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.scortelemed.schemas.nn.NnUnderwrittingCaseManagementService#gestionReconocimientoMedico(com.scortelemed.schemas.nn.GestionReconocimientoMedicoRequest  gestionReconocimientoMedicoRequest )*
     */
    public GestionReconocimientoMedicoResponse gestionReconocimientoMedico(GestionReconocimientoMedicoRequest gestionReconocimientoMedicoRequest) {
        LOG.info("Executing operation gestionReconocimientoMedico");
        System.out.println(gestionReconocimientoMedicoRequest);
        try {
            GestionReconocimientoMedicoResponse _return = new GestionReconocimientoMedicoResponse();
            com.scortelemed.schemas.nn.StatusType _returnStatus = com.scortelemed.schemas.nn.StatusType.ERROR;
            _return.setStatus(_returnStatus);
            _return.setDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-11-28T13:10:27.541+01:00"));
            _return.setMessage("Message1404532485");
            _return.setCode(-837686532);
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
