
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.scortelemed.schemas.caser;

import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 2.1
 * Mon Sep 10 18:22:38 CEST 2018
 * Generated source version: 2.1
 */

@javax.jws.WebService(name = "CaserUnderwrittingCaseManagementService",
        serviceName = "CaserUnderwrittingCaseManagementServiceService",
        portName = "CaserUnderwrittingCaseManagementServicePort",
        targetNamespace = "http://www.scortelemed.com/schemas/caser",
        wsdlLocation = "https://www.scortelemed.com:9090/webservicessoap/services/caser/CaserUnderwrittingCaseManagement?wsdl",
        endpointInterface = "com.scortelemed.schemas.caser.CaserUnderwrittingCaseManagementService")

public class CaserUnderwrittingCaseManagementServiceImpl implements CaserUnderwrittingCaseManagementService {

    private static final Logger LOG = Logger.getLogger(CaserUnderwrittingCaseManagementServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see com.scortelemed.schemas.caser.CaserUnderwrittingCaseManagementService#consultaExpedienteResponse(com.scortelemed.schemas.caser.ConsultaExpedienteRequest  consultaExpedienteRequest )*
     */
    public com.scortelemed.schemas.caser.ConsultaExpedienteResponse consultaExpedienteResponse(ConsultaExpedienteRequest consultaExpedienteRequest) {
        LOG.info("Executing operation consultaExpedienteResponse");
        System.out.println(consultaExpedienteRequest);
        try {
            com.scortelemed.schemas.caser.ConsultaExpedienteResponse _return = new com.scortelemed.schemas.caser.ConsultaExpedienteResponse();
            _return.setDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-09-10T18:22:38.616+02:00"));
            com.scortelemed.schemas.caser.StatusType _returnStatus = com.scortelemed.schemas.caser.StatusType.ERROR;
            _return.setStatus(_returnStatus);
            _return.setNotes("Notes1398808252");
            java.util.List<com.scortelemed.schemas.caser.ConsultaExpedienteResponse.ExpedienteConsulta> _returnExpedienteConsulta = new java.util.ArrayList<com.scortelemed.schemas.caser.ConsultaExpedienteResponse.ExpedienteConsulta>();
            com.scortelemed.schemas.caser.ConsultaExpedienteResponse.ExpedienteConsulta _returnExpedienteConsultaVal1 = new com.scortelemed.schemas.caser.ConsultaExpedienteResponse.ExpedienteConsulta();
            _returnExpedienteConsultaVal1.setRequestDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-09-10T18:22:38.616+02:00"));
            _returnExpedienteConsultaVal1.setRequestNumber("RequestNumber791385111");
            _returnExpedienteConsultaVal1.setRequestState("RequestState1591513232");
            _returnExpedienteConsultaVal1.setProductCode("ProductCode-1583124040");
            _returnExpedienteConsultaVal1.setPolicyNumber("PolicyNumber-1534968207");
            _returnExpedienteConsultaVal1.setCertificateNumber("CertificateNumber98720716");
            _returnExpedienteConsultaVal1.setFiscalIdentificationNumber("FiscalIdentificationNumber-1457374697");
            _returnExpedienteConsultaVal1.setMobilePhone("MobilePhone1590564223");
            _returnExpedienteConsultaVal1.setPhoneNumber1("PhoneNumber1-1518773030");
            _returnExpedienteConsultaVal1.setPhoneNumber2("PhoneNumber216909505");
            _returnExpedienteConsultaVal1.setDomicilio("Paseo de la castellana 135");
            _returnExpedienteConsultaVal1.setCodPostal("028004");
            _returnExpedienteConsultaVal1.setLocalidad("Madrid");
            _returnExpedienteConsultaVal1.setProvincia("Madrid");
            java.util.List<com.scortelemed.schemas.caser.BenefitsType> _returnExpedienteConsultaVal1BenefitsList = new java.util.ArrayList<com.scortelemed.schemas.caser.BenefitsType>();
            _returnExpedienteConsultaVal1.getBenefitsList().addAll(_returnExpedienteConsultaVal1BenefitsList);
            byte[] _returnExpedienteConsultaVal1Zip = new byte[]{};
            _returnExpedienteConsultaVal1.setZip(_returnExpedienteConsultaVal1Zip);
            _returnExpedienteConsultaVal1.setNotes("Notes80426081");
            _returnExpedienteConsulta.add(_returnExpedienteConsultaVal1);
            _return.getExpedienteConsulta().addAll(_returnExpedienteConsulta);
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.scortelemed.schemas.caser.CaserUnderwrittingCaseManagementService#consolidacionPoliza(com.scortelemed.schemas.caser.ConsolidacionPolizaRequest  consolidacionPolizaRequest )*
     */
    public com.scortelemed.schemas.caser.ConsolidacionPolizaResponse consolidacionPoliza(ConsolidacionPolizaRequest consolidacionPolizaRequest) {
        LOG.info("Executing operation consolidacionPoliza");
        System.out.println(consolidacionPolizaRequest);
        try {
            com.scortelemed.schemas.caser.ConsolidacionPolizaResponse _return = new com.scortelemed.schemas.caser.ConsolidacionPolizaResponse();
            com.scortelemed.schemas.caser.StatusType _returnStatus = com.scortelemed.schemas.caser.StatusType.ERROR;
            _return.setStatus(_returnStatus);
            _return.setDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-09-10T18:22:38.616+02:00"));
            _return.setMessage("Message-2132290640");
            _return.setCodigo(1649073248);
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.scortelemed.schemas.caser.CaserUnderwrittingCaseManagementService#gestionReconocimientoMedico(com.scortelemed.schemas.caser.GestionReconocimientoMedicoRequest  gestionReconocimientoMedicoRequest )*
     */
    public com.scortelemed.schemas.caser.GestionReconocimientoMedicoResponse gestionReconocimientoMedico(GestionReconocimientoMedicoRequest gestionReconocimientoMedicoRequest) {
        LOG.info("Executing operation gestionReconocimientoMedico");
        System.out.println(gestionReconocimientoMedicoRequest);
        try {
            com.scortelemed.schemas.caser.GestionReconocimientoMedicoResponse _return = new com.scortelemed.schemas.caser.GestionReconocimientoMedicoResponse();
            com.scortelemed.schemas.caser.StatusType _returnStatus = com.scortelemed.schemas.caser.StatusType.ERROR;
            _return.setStatus(_returnStatus);
            _return.setDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-09-10T18:22:38.616+02:00"));
            _return.setNotes("Notes-633581689");
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    public GestionReconocimientoMedicoInfantilResponse gestionReconocimientoMedicoInfantil(GestionReconocimientoMedicoInfantilRequest gestionReconocimientoMedicoInfantilRequest) {
        LOG.info("Executing operation gestionReconocimientoMedicoInfantil");
        System.out.println(gestionReconocimientoMedicoInfantilRequest);
        try {
            com.scortelemed.schemas.caser.GestionReconocimientoMedicoInfantilResponse _return = new com.scortelemed.schemas.caser.GestionReconocimientoMedicoInfantilResponse();
            com.scortelemed.schemas.caser.StatusType _returnStatus = com.scortelemed.schemas.caser.StatusType.ERROR;
            _return.setStatus(_returnStatus);
            _return.setDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-09-10T18:22:38.616+02:00"));
            _return.setNotes("Notes-633581689");
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.scortelemed.schemas.caser.CaserUnderwrittingCaseManagementService#resultadoReconocimientoMedico(com.scortelemed.schemas.caser.ResultadoReconocimientoMedicoRequest  resultadoReconocimientoMedicoRequest )*
     */
    public com.scortelemed.schemas.caser.ResultadoReconocimientoMedicoResponse resultadoReconocimientoMedico(ResultadoReconocimientoMedicoRequest resultadoReconocimientoMedicoRequest) {
        LOG.info("Executing operation resultadoReconocimientoMedico");
        System.out.println(resultadoReconocimientoMedicoRequest);
        try {
            com.scortelemed.schemas.caser.ResultadoReconocimientoMedicoResponse _return = new com.scortelemed.schemas.caser.ResultadoReconocimientoMedicoResponse();
            _return.setDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-09-10T18:22:38.616+02:00"));
            com.scortelemed.schemas.caser.StatusType _returnStatus = com.scortelemed.schemas.caser.StatusType.ERROR;
            _return.setStatus(_returnStatus);
            _return.setNotes("Notes1425027890");
            java.util.List<com.scortelemed.schemas.caser.ResultadoReconocimientoMedicoResponse.Expediente> _returnExpediente = new java.util.ArrayList<com.scortelemed.schemas.caser.ResultadoReconocimientoMedicoResponse.Expediente>();
            com.scortelemed.schemas.caser.ResultadoReconocimientoMedicoResponse.Expediente _returnExpedienteVal1 = new com.scortelemed.schemas.caser.ResultadoReconocimientoMedicoResponse.Expediente();
            _returnExpedienteVal1.setRequestDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-09-10T18:22:38.616+02:00"));
            _returnExpedienteVal1.setRequestNumber("RequestNumber-1317461903");
            com.scortelemed.schemas.caser.RequestStateType _returnExpedienteVal1RequestState = com.scortelemed.schemas.caser.RequestStateType.CANCELLED;
            _returnExpedienteVal1.setRequestState(_returnExpedienteVal1RequestState);
            _returnExpedienteVal1.setProductCode("ProductCode1275126635");
            _returnExpedienteVal1.setPolicyNumber("PolicyNumber347564401");
            _returnExpedienteVal1.setCertificateNumber("CertificateNumber-350131401");
            _returnExpedienteVal1.setFiscalIdentificationNumber("FiscalIdentificationNumber-252679582");
            _returnExpedienteVal1.setMobilePhone("MobilePhone1085274888");
            _returnExpedienteVal1.setPhoneNumber1("PhoneNumber135827931");
            _returnExpedienteVal1.setPhoneNumber2("PhoneNumber2221383432");
            _returnExpedienteVal1.setDomicilio("Paseo de la castellana 135");
            _returnExpedienteVal1.setCodPostal("028004");
            _returnExpedienteVal1.setLocalidad("Madrid");
            _returnExpedienteVal1.setProvincia("Madrid");
            java.util.List<com.scortelemed.schemas.caser.BenefitsType> _returnExpedienteVal1BenefitsList = new java.util.ArrayList<com.scortelemed.schemas.caser.BenefitsType>();
            _returnExpedienteVal1.getBenefitsList().addAll(_returnExpedienteVal1BenefitsList);
            byte[] _returnExpedienteVal1Zip = new byte[]{};
            _returnExpedienteVal1.setZip(_returnExpedienteVal1Zip);
            _returnExpedienteVal1.setNotes("Notes638212144");
            _returnExpediente.add(_returnExpedienteVal1);
            _return.getExpediente().addAll(_returnExpediente);
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
