
package com.scortelemed.schemas.caser;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 2.1
 * Mon Sep 10 18:22:38 CEST 2018
 * Generated source version: 2.1
 * 
 */

@WebServiceClient(name = "CaserUnderwrittingCaseManagementServiceService", targetNamespace = "http://www.scortelemed.com/schemas/caser", wsdlLocation = "https://www.scortelemed.com:9090/webservicessoap/services/caser/CaserUnderwrittingCaseManagement?wsdl")
public class CaserUnderwrittingCaseManagementServiceService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://www.scortelemed.com/schemas/caser", "CaserUnderwrittingCaseManagementServiceService");
    public final static QName CaserUnderwrittingCaseManagementServicePort = new QName("http://www.scortelemed.com/schemas/caser", "CaserUnderwrittingCaseManagementServicePort");
    static {
        URL url = null;
        try {
            url = new URL("https://www.scortelemed.com:9090/webservicessoap/services/caser/CaserUnderwrittingCaseManagement?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from https://www.scortelemed.com:9090/webservicessoap/services/caser/CaserUnderwrittingCaseManagement?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public CaserUnderwrittingCaseManagementServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CaserUnderwrittingCaseManagementServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CaserUnderwrittingCaseManagementServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns CaserUnderwrittingCaseManagementService
     */
    @WebEndpoint(name = "CaserUnderwrittingCaseManagementServicePort")
    public CaserUnderwrittingCaseManagementService getCaserUnderwrittingCaseManagementServicePort() {
        return super.getPort(CaserUnderwrittingCaseManagementServicePort, CaserUnderwrittingCaseManagementService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CaserUnderwrittingCaseManagementService
     */
    @WebEndpoint(name = "CaserUnderwrittingCaseManagementServicePort")
    public CaserUnderwrittingCaseManagementService getCaserUnderwrittingCaseManagementServicePort(WebServiceFeature... features) {
        return super.getPort(CaserUnderwrittingCaseManagementServicePort, CaserUnderwrittingCaseManagementService.class, features);
    }

}
