
package com.scortelemed.schemas.caser;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.1
 * Mon Sep 10 18:22:38 CEST 2018
 * Generated source version: 2.1
 * 
 */

@WebService(targetNamespace = "http://www.scortelemed.com/schemas/caser", name = "CaserUnderwrittingCaseManagementService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)

public interface CaserUnderwrittingCaseManagementService {

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "ConsultaExpedienteResponse", targetNamespace = "http://www.scortelemed.com/schemas/caser", partName = "ConsultaExpedienteResponse")
    @WebMethod
    public ConsultaExpedienteResponse consultaExpedienteResponse(
        @WebParam(partName = "ConsultaExpedienteRequest", name = "ConsultaExpedienteRequest", targetNamespace = "http://www.scortelemed.com/schemas/caser")
        ConsultaExpedienteRequest consultaExpedienteRequest
    );

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "ConsolidacionPolizaResponse", targetNamespace = "http://www.scortelemed.com/schemas/caser", partName = "ConsolidacionPolizaResponse")
    @WebMethod
    public ConsolidacionPolizaResponse consolidacionPoliza(
        @WebParam(partName = "ConsolidacionPolizaRequest", name = "ConsolidacionPolizaRequest", targetNamespace = "http://www.scortelemed.com/schemas/caser")
        ConsolidacionPolizaRequest consolidacionPolizaRequest
    );

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "GestionReconocimientoMedicoResponse", targetNamespace = "http://www.scortelemed.com/schemas/caser", partName = "GestionReconocimientoMedicoResponse")
    @WebMethod
    public GestionReconocimientoMedicoResponse gestionReconocimientoMedico(
        @WebParam(partName = "GestionReconocimientoMedicoRequest", name = "GestionReconocimientoMedicoRequest", targetNamespace = "http://www.scortelemed.com/schemas/caser")
        GestionReconocimientoMedicoRequest gestionReconocimientoMedicoRequest
    );

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "ResultadoReconocimientoMedicoResponse", targetNamespace = "http://www.scortelemed.com/schemas/caser", partName = "ResultadoReconocimientoMedicoResponse")
    @WebMethod
    public ResultadoReconocimientoMedicoResponse resultadoReconocimientoMedico(
        @WebParam(partName = "ResultadoReconocimientoMedicoRequest", name = "ResultadoReconocimientoMedicoRequest", targetNamespace = "http://www.scortelemed.com/schemas/caser")
        ResultadoReconocimientoMedicoRequest resultadoReconocimientoMedicoRequest
    );
}
