
package com.scortelemed.schemas.caser;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.1
 * Mon Sep 10 18:22:38 CEST 2018
 * Generated source version: 2.1
 * 
 */

public final class CaserUnderwrittingCaseManagementService_CaserUnderwrittingCaseManagementServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://www.scortelemed.com/schemas/caser", "CaserUnderwrittingCaseManagementServiceService");

    private CaserUnderwrittingCaseManagementService_CaserUnderwrittingCaseManagementServicePort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = CaserUnderwrittingCaseManagementServiceService.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        CaserUnderwrittingCaseManagementServiceService ss = new CaserUnderwrittingCaseManagementServiceService(wsdlURL, SERVICE_NAME);
        CaserUnderwrittingCaseManagementService port = ss.getCaserUnderwrittingCaseManagementServicePort();  
        
        {
        System.out.println("Invoking consultaExpedienteResponse...");
        com.scortelemed.schemas.caser.ConsultaExpedienteRequest _consultaExpedienteResponse_consultaExpedienteRequest = new com.scortelemed.schemas.caser.ConsultaExpedienteRequest();
        _consultaExpedienteResponse_consultaExpedienteRequest.setCodExpediente("CodExpediente1614416407");
        com.scortelemed.schemas.caser.ConsultaExpedienteResponse _consultaExpedienteResponse__return = port.consultaExpedienteResponse(_consultaExpedienteResponse_consultaExpedienteRequest);
        System.out.println("consultaExpedienteResponse.result=" + _consultaExpedienteResponse__return);


        }
        {
        System.out.println("Invoking consolidacionPoliza...");
        com.scortelemed.schemas.caser.ConsolidacionPolizaRequest _consolidacionPoliza_consolidacionPolizaRequest = new com.scortelemed.schemas.caser.ConsolidacionPolizaRequest();
        _consolidacionPoliza_consolidacionPolizaRequest.setCiaCode("CiaCode-1771251155");
        _consolidacionPoliza_consolidacionPolizaRequest.setProductCode("ProductCode1514884398");
        _consolidacionPoliza_consolidacionPolizaRequest.setRequestNumber("RequestNumber-296130033");
        _consolidacionPoliza_consolidacionPolizaRequest.setPolicyNumber("PolicyNumber-1929248476");
        _consolidacionPoliza_consolidacionPolizaRequest.setCertificateNumber("CertificateNumber955571973");
        _consolidacionPoliza_consolidacionPolizaRequest.setRequestDate("RequestDate-1542130654");
        com.scortelemed.schemas.caser.ConsolidacionPolizaResponse _consolidacionPoliza__return = port.consolidacionPoliza(_consolidacionPoliza_consolidacionPolizaRequest);
        System.out.println("consolidacionPoliza.result=" + _consolidacionPoliza__return);


        }
        {
        System.out.println("Invoking gestionReconocimientoMedico...");
        com.scortelemed.schemas.caser.GestionReconocimientoMedicoRequest _gestionReconocimientoMedico_gestionReconocimientoMedicoRequest = new com.scortelemed.schemas.caser.GestionReconocimientoMedicoRequest();
        com.scortelemed.schemas.caser.GestionReconocimientoMedicoRequest.CandidateInformation _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformation = new com.scortelemed.schemas.caser.GestionReconocimientoMedicoRequest.CandidateInformation();
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformation.setFiscalIdentificationNumber("FiscalIdentificationNumber642087568");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformation.setName("Name-1110344521");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformation.setSurname("Surname1241550343");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformation.setAddress("Address-1986894848");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformation.setCity("City1415369730");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformation.setProvince("Province-1126729997");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformation.setCountry("Country-1349307773");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformation.setPostalCode("PostalCode145299418");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformation.setEmail("Email895483464");
        com.scortelemed.schemas.caser.GenderType _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformationGender = com.scortelemed.schemas.caser.GenderType.H;
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformation.setGender(_gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformationGender);
        com.scortelemed.schemas.caser.CivilStateType _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformationCivilState = com.scortelemed.schemas.caser.CivilStateType.V;
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformation.setCivilState(_gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformationCivilState);
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformation.setMobileNumber("MobileNumber-868249385");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformation.setPhoneNumber1("PhoneNumber11678585805");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformation.setPhoneNumber2("PhoneNumber2-1577186249");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformation.setPassword("Password-308051011");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformation.setIgp("Igp167156298");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformation.setAgente("Agente1318863377");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformation.setProductCode("ProductCode-1726956057");
        java.lang.Object _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformationBirthDate = null;
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformation.setBirthDate(_gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformationBirthDate);
        com.scortelemed.schemas.caser.OperationType _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformationOperationType = com.scortelemed.schemas.caser.OperationType.N;
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformation.setOperationType(_gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformationOperationType);
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequest.setCandidateInformation(_gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformation);
        com.scortelemed.schemas.caser.GestionReconocimientoMedicoRequest.PolicyHolderInformation _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestPolicyHolderInformation = new com.scortelemed.schemas.caser.GestionReconocimientoMedicoRequest.PolicyHolderInformation();
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestPolicyHolderInformation.setFiscalIdentificationNumber("FiscalIdentificationNumber-81118464");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestPolicyHolderInformation.setName("Name-429462941");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestPolicyHolderInformation.setSurname1("Surname12142507830");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestPolicyHolderInformation.setSurname2("Surname2211550634");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestPolicyHolderInformation.setPolicyNumber("PolicyNumber-973084711");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestPolicyHolderInformation.setCertificateNumber("CertificateNumber-1797965073");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestPolicyHolderInformation.setRequestDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-09-10T18:22:38.606+02:00"));
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestPolicyHolderInformation.setRequestNumber("RequestNumber-105039969");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestPolicyHolderInformation.setComments("Comments-446270116");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequest.setPolicyHolderInformation(_gestionReconocimientoMedico_gestionReconocimientoMedicoRequestPolicyHolderInformation);
        java.util.List<com.scortelemed.schemas.caser.GestionReconocimientoMedicoRequest.ServiceInformation> _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestServiceInformation = new java.util.ArrayList<com.scortelemed.schemas.caser.GestionReconocimientoMedicoRequest.ServiceInformation>();
        com.scortelemed.schemas.caser.GestionReconocimientoMedicoRequest.ServiceInformation _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestServiceInformationVal1 = new com.scortelemed.schemas.caser.GestionReconocimientoMedicoRequest.ServiceInformation();
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestServiceInformationVal1.setServiceType("ServiceType-1181955175");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestServiceInformationVal1.setServiceCode("ServiceCode1268953083");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestServiceInformationVal1.setServiceDescription("ServiceDescription962979367");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestServiceInformation.add(_gestionReconocimientoMedico_gestionReconocimientoMedicoRequestServiceInformationVal1);
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequest.getServiceInformation().addAll(_gestionReconocimientoMedico_gestionReconocimientoMedicoRequestServiceInformation);
        java.util.List<com.scortelemed.schemas.caser.GestionReconocimientoMedicoRequest.BenefitsType> _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestBenefitsType = new java.util.ArrayList<com.scortelemed.schemas.caser.GestionReconocimientoMedicoRequest.BenefitsType>();
        com.scortelemed.schemas.caser.GestionReconocimientoMedicoRequest.BenefitsType _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestBenefitsTypeVal1 = new com.scortelemed.schemas.caser.GestionReconocimientoMedicoRequest.BenefitsType();
        com.scortelemed.schemas.caser.BenefictNameType _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestBenefitsTypeVal1BenefictName = com.scortelemed.schemas.caser.BenefictNameType.DISABILITY_30_90;
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestBenefitsTypeVal1.setBenefictName(_gestionReconocimientoMedico_gestionReconocimientoMedicoRequestBenefitsTypeVal1BenefictName);
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestBenefitsTypeVal1.setBenefictCode("BenefictCode1702377472");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestBenefitsTypeVal1.setBenefictCapital("BenefictCapital487607661");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestBenefitsType.add(_gestionReconocimientoMedico_gestionReconocimientoMedicoRequestBenefitsTypeVal1);
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequest.getBenefitsType().addAll(_gestionReconocimientoMedico_gestionReconocimientoMedicoRequestBenefitsType);
        com.scortelemed.schemas.caser.GestionReconocimientoMedicoResponse _gestionReconocimientoMedico__return = port.gestionReconocimientoMedico(_gestionReconocimientoMedico_gestionReconocimientoMedicoRequest);
        System.out.println("gestionReconocimientoMedico.result=" + _gestionReconocimientoMedico__return);


        }
        {
        System.out.println("Invoking resultadoReconocimientoMedico...");
        com.scortelemed.schemas.caser.ResultadoReconocimientoMedicoRequest _resultadoReconocimientoMedico_resultadoReconocimientoMedicoRequest = new com.scortelemed.schemas.caser.ResultadoReconocimientoMedicoRequest();
        _resultadoReconocimientoMedico_resultadoReconocimientoMedicoRequest.setDateStart(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-09-10T18:22:38.606+02:00"));
        _resultadoReconocimientoMedico_resultadoReconocimientoMedicoRequest.setDateEnd(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-09-10T18:22:38.606+02:00"));
        com.scortelemed.schemas.caser.ResultadoReconocimientoMedicoResponse _resultadoReconocimientoMedico__return = port.resultadoReconocimientoMedico(_resultadoReconocimientoMedico_resultadoReconocimientoMedicoRequest);
        System.out.println("resultadoReconocimientoMedico.result=" + _resultadoReconocimientoMedico__return);


        }

        System.exit(0);
    }

}
