
package com.scortelemed.schemas.ama;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.1
 * Mon Sep 10 16:52:15 CEST 2018
 * Generated source version: 2.1
 * 
 */

public final class AmaUnderwrittingCaseManagementService_AmaUnderwrittingCaseManagementServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://www.scortelemed.com/schemas/ama", "AmaUnderwrittingCaseManagementServiceService");

    private AmaUnderwrittingCaseManagementService_AmaUnderwrittingCaseManagementServicePort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = AmaUnderwrittingCaseManagementServiceService.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        AmaUnderwrittingCaseManagementServiceService ss = new AmaUnderwrittingCaseManagementServiceService(wsdlURL, SERVICE_NAME);
        AmaUnderwrittingCaseManagementService port = ss.getAmaUnderwrittingCaseManagementServicePort();  
        
        {
        System.out.println("Invoking resultadoSiniestro...");
        com.scortelemed.schemas.ama.ResultadoSiniestroRequest _resultadoSiniestro_resultadoSiniestroRequest = new com.scortelemed.schemas.ama.ResultadoSiniestroRequest();
        _resultadoSiniestro_resultadoSiniestroRequest.setDateStart(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-09-10T16:52:15.842+02:00"));
        _resultadoSiniestro_resultadoSiniestroRequest.setDateEnd(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-09-10T16:52:15.842+02:00"));
        com.scortelemed.schemas.ama.ResultadoSiniestroResponse _resultadoSiniestro__return = port.resultadoSiniestro(_resultadoSiniestro_resultadoSiniestroRequest);
        System.out.println("resultadoSiniestro.result=" + _resultadoSiniestro__return);


        }
        {
        System.out.println("Invoking gestionReconocimientoMedico...");
        com.scortelemed.schemas.ama.GestionReconocimientoMedicoRequest _gestionReconocimientoMedico_gestionReconocimientoMedicoRequest = new com.scortelemed.schemas.ama.GestionReconocimientoMedicoRequest();
        com.scortelemed.schemas.ama.GestionReconocimientoMedicoRequest.CandidateInformation _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformation = new com.scortelemed.schemas.ama.GestionReconocimientoMedicoRequest.CandidateInformation();
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformation.setCiaCode("CiaCode-859015079");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformation.setProductCode("ProductCode1562928577");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformation.setRequestNumber("RequestNumber53316633");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformation.setPolicyNumber("PolicyNumber-1541385849");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformation.setCertificateNumber("CertificateNumber653499041");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformation.setOperacion("Operacion-1767958801");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformation.setRequestDate("RequestDate-1459923843");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformation.setPassword("Password-1013171969");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformation.setRequestState("RequestState-725714111");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformation.setName("Name-870066070");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformation.setSurname("Surname950450582");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformation.setAddress("Address544934031");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformation.setPostalCode("PostalCode198478485");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformation.setCity("City1099211613");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformation.setProvince("Province1719264943");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformation.setCountry("Country1601116966");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformation.setPhoneNumber1("PhoneNumber11659370610");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformation.setPhoneNumber2("PhoneNumber2-232934236");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformation.setMobileNumber("MobileNumber-102504986");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformation.setEmail("Email1768001724");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformation.setBirthDate("BirthDate525770598");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformation.setActuarialAge("ActuarialAge-1972613946");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformation.setBirthCity("BirthCity1985581839");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformation.setFiscalIdentificationNumber("FiscalIdentificationNumber262312289");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformation.setAgency("Agency-1469422524");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformation.setAgent("Agent-637994206");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformation.setAgentPhone("AgentPhone-2020058920");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformation.setAgentEmail("AgentEmail-1351471725");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformation.setGender("Gender-946054690");
        com.scortelemed.schemas.ama.CivilStateType _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformationCivilState = com.scortelemed.schemas.ama.CivilStateType.V;
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformation.setCivilState(_gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformationCivilState);
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformation.setCustomerType("CustomerType880090157");
        com.scortelemed.schemas.ama.ContactTimeType _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformationContactTime = com.scortelemed.schemas.ama.ContactTimeType.C;
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformation.setContactTime(_gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformationContactTime);
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformation.setComments("Comments707076372");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformation.setEUWReferenceCode("EUWReferenceCode-208087991");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformation.setRentaDiaria(new java.math.BigDecimal("-494276806406802582.7156814700298353265"));
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequest.setCandidateInformation(_gestionReconocimientoMedico_gestionReconocimientoMedicoRequestCandidateInformation);
        java.util.List<com.scortelemed.schemas.ama.GestionReconocimientoMedicoRequest.PreviousQuestions> _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestPreviousQuestions = new java.util.ArrayList<com.scortelemed.schemas.ama.GestionReconocimientoMedicoRequest.PreviousQuestions>();
        com.scortelemed.schemas.ama.GestionReconocimientoMedicoRequest.PreviousQuestions _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestPreviousQuestionsVal1 = new com.scortelemed.schemas.ama.GestionReconocimientoMedicoRequest.PreviousQuestions();
        com.scortelemed.schemas.ama.QuestionDataType _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestPreviousQuestionsVal1DataType = com.scortelemed.schemas.ama.QuestionDataType.DATE;
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestPreviousQuestionsVal1.setDataType(_gestionReconocimientoMedico_gestionReconocimientoMedicoRequestPreviousQuestionsVal1DataType);
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestPreviousQuestionsVal1.setAnswerCode("AnswerCode-2134141792");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestPreviousQuestionsVal1.setQuestion("Question-1731796028");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestPreviousQuestionsVal1.setAnswer("Answer1435652788");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestPreviousQuestions.add(_gestionReconocimientoMedico_gestionReconocimientoMedicoRequestPreviousQuestionsVal1);
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequest.getPreviousQuestions().addAll(_gestionReconocimientoMedico_gestionReconocimientoMedicoRequestPreviousQuestions);
        java.util.List<com.scortelemed.schemas.ama.GestionReconocimientoMedicoRequest.Services> _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestServices = new java.util.ArrayList<com.scortelemed.schemas.ama.GestionReconocimientoMedicoRequest.Services>();
        com.scortelemed.schemas.ama.GestionReconocimientoMedicoRequest.Services _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestServicesVal1 = new com.scortelemed.schemas.ama.GestionReconocimientoMedicoRequest.Services();
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestServicesVal1.setServiceType("ServiceType939663500");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestServicesVal1.setServiceCode("ServiceCode866061805");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestServicesVal1.setServiceDescription("ServiceDescription-297356602");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestServices.add(_gestionReconocimientoMedico_gestionReconocimientoMedicoRequestServicesVal1);
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequest.getServices().addAll(_gestionReconocimientoMedico_gestionReconocimientoMedicoRequestServices);
        java.util.List<com.scortelemed.schemas.ama.GestionReconocimientoMedicoRequest.BenefitsType> _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestBenefitsType = new java.util.ArrayList<com.scortelemed.schemas.ama.GestionReconocimientoMedicoRequest.BenefitsType>();
        com.scortelemed.schemas.ama.GestionReconocimientoMedicoRequest.BenefitsType _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestBenefitsTypeVal1 = new com.scortelemed.schemas.ama.GestionReconocimientoMedicoRequest.BenefitsType();
        com.scortelemed.schemas.ama.BenefictNameType _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestBenefitsTypeVal1BenefictName = com.scortelemed.schemas.ama.BenefictNameType.INCAPACIDAD_PERMANENTE_ABSOLUTA_IPA;
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestBenefitsTypeVal1.setBenefictName(_gestionReconocimientoMedico_gestionReconocimientoMedicoRequestBenefitsTypeVal1BenefictName);
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestBenefitsTypeVal1.setBenefictCode("BenefictCode1123841240");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestBenefitsTypeVal1.setBenefictCapital("BenefictCapital1397462683");
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequestBenefitsType.add(_gestionReconocimientoMedico_gestionReconocimientoMedicoRequestBenefitsTypeVal1);
        _gestionReconocimientoMedico_gestionReconocimientoMedicoRequest.getBenefitsType().addAll(_gestionReconocimientoMedico_gestionReconocimientoMedicoRequestBenefitsType);
        com.scortelemed.schemas.ama.GestionReconocimientoMedicoResponse _gestionReconocimientoMedico__return = port.gestionReconocimientoMedico(_gestionReconocimientoMedico_gestionReconocimientoMedicoRequest);
        System.out.println("gestionReconocimientoMedico.result=" + _gestionReconocimientoMedico__return);


        }
        {
        System.out.println("Invoking consultaExpediente...");
        com.scortelemed.schemas.ama.ConsultaExpedienteRequest _consultaExpediente_consultaExpedienteRequest = new com.scortelemed.schemas.ama.ConsultaExpedienteRequest();
        _consultaExpediente_consultaExpedienteRequest.setNumSolicitud("NumSolicitud-1642468295");
        _consultaExpediente_consultaExpedienteRequest.setNumExpediente("NumExpediente962856370");
        _consultaExpediente_consultaExpedienteRequest.setNumSumplemento("NumSumplemento-552471265");
        com.scortelemed.schemas.ama.ConsultaExpedienteResponse _consultaExpediente__return = port.consultaExpediente(_consultaExpediente_consultaExpedienteRequest);
        System.out.println("consultaExpediente.result=" + _consultaExpediente__return);


        }
        {
        System.out.println("Invoking consultaDocumento...");
        com.scortelemed.schemas.ama.ConsultaDocumentoRequest _consultaDocumento_consultaDocumentoRequest = new com.scortelemed.schemas.ama.ConsultaDocumentoRequest();
        _consultaDocumento_consultaDocumentoRequest.setCodigoSt("CodigoSt-963389796");
        _consultaDocumento_consultaDocumentoRequest.setDocumentacionId("DocumentacionId-1713381344");
        _consultaDocumento_consultaDocumentoRequest.setNodoAlfresco("NodoAlfresco1702923332");
        com.scortelemed.schemas.ama.ConsultaDocumentoResponse _consultaDocumento__return = port.consultaDocumento(_consultaDocumento_consultaDocumentoRequest);
        System.out.println("consultaDocumento.result=" + _consultaDocumento__return);


        }
        {
        System.out.println("Invoking consolidacionPoliza...");
        com.scortelemed.schemas.ama.ConsolidacionPolizaRequest _consolidacionPoliza_consolidacionPolizaRequest = new com.scortelemed.schemas.ama.ConsolidacionPolizaRequest();
        _consolidacionPoliza_consolidacionPolizaRequest.setCiaCode("CiaCode2019821816");
        _consolidacionPoliza_consolidacionPolizaRequest.setProductCode("ProductCode-2002271335");
        _consolidacionPoliza_consolidacionPolizaRequest.setRequestNumber("RequestNumber1172137436");
        _consolidacionPoliza_consolidacionPolizaRequest.setPolicyNumber("PolicyNumber790453190");
        _consolidacionPoliza_consolidacionPolizaRequest.setCertificateNumber("CertificateNumber1767530739");
        _consolidacionPoliza_consolidacionPolizaRequest.setRequestDate("RequestDate-1201128630");
        com.scortelemed.schemas.ama.ConsolidacionPolizaResponse _consolidacionPoliza__return = port.consolidacionPoliza(_consolidacionPoliza_consolidacionPolizaRequest);
        System.out.println("consolidacionPoliza.result=" + _consolidacionPoliza__return);


        }

        System.exit(0);
    }

}
