
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.scortelemed.schemas.ama;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.1
 * Mon Sep 10 16:52:15 CEST 2018
 * Generated source version: 2.1
 * 
 */

@javax.jws.WebService(name = "AmaUnderwrittingCaseManagementService",
                      serviceName = "AmaUnderwrittingCaseManagementServiceService",
                      portName = "AmaUnderwrittingCaseManagementServicePort",
                      targetNamespace = "http://www.scortelemed.com/schemas/ama", 
                      wsdlLocation = "https://www.scortelemed.com:9090/webservicessoap/services/ama/AmaUnderwrittingCaseManagement?wsdl",
                      endpointInterface = "com.scortelemed.schemas.ama.AmaUnderwrittingCaseManagementService")
                      
public class AmaUnderwrittingCaseManagementServiceImpl implements AmaUnderwrittingCaseManagementService {

    private static final Logger LOG = Logger.getLogger(AmaUnderwrittingCaseManagementServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see com.scortelemed.schemas.ama.AmaUnderwrittingCaseManagementService#resultadoSiniestro(com.scortelemed.schemas.ama.ResultadoSiniestroRequest  resultadoSiniestroRequest )*
     */
    public com.scortelemed.schemas.ama.ResultadoSiniestroResponse resultadoSiniestro(ResultadoSiniestroRequest resultadoSiniestroRequest) { 
        LOG.info("Executing operation resultadoSiniestro");
        System.out.println(resultadoSiniestroRequest);
        try {
            com.scortelemed.schemas.ama.ResultadoSiniestroResponse _return = new com.scortelemed.schemas.ama.ResultadoSiniestroResponse();
            _return.setFecha(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-09-10T16:52:15.852+02:00"));
            com.scortelemed.schemas.ama.StatusType _returnEstado = com.scortelemed.schemas.ama.StatusType.ERROR;
            _return.setEstado(_returnEstado);
            _return.setNotas("Notas-1796338253");
            java.util.List<com.scortelemed.schemas.ama.ResultadoSiniestroResponse.Expediente> _returnExpediente = new java.util.ArrayList<com.scortelemed.schemas.ama.ResultadoSiniestroResponse.Expediente>();
            com.scortelemed.schemas.ama.ResultadoSiniestroResponse.Expediente _returnExpedienteVal1 = new com.scortelemed.schemas.ama.ResultadoSiniestroResponse.Expediente();
            java.util.List<com.scortelemed.schemas.ama.Interviniente> _returnExpedienteVal1Interviniente = new java.util.ArrayList<com.scortelemed.schemas.ama.Interviniente>();
            _returnExpedienteVal1.getInterviniente().addAll(_returnExpedienteVal1Interviniente);
            _returnExpedienteVal1.setCodigoST("CodigoST-1830853633");
            _returnExpedienteVal1.setEstado("Estado1150906120");
            _returnExpedienteVal1.setFechaDeEstado(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-09-10T16:52:15.852+02:00"));
            _returnExpedienteVal1.setMotivoEstado("MotivoEstado1623053338");
            _returnExpedienteVal1.setSituacionPoliza("SituacionPoliza2023740710");
            _returnExpedienteVal1.setIdOperacionConsultaPoliza("IdOperacionConsultaPoliza774606604");
            _returnExpedienteVal1.setNumeroPoliza("NumeroPoliza1519907999");
            _returnExpedienteVal1.setNumeroSuplemento("NumeroSuplemento706341222");
            _returnExpedienteVal1.setNumeroCertificado("NumeroCertificado2034609621");
            _returnExpedienteVal1.setFechaAltaPoliza(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-09-10T16:52:15.862+02:00"));
            _returnExpedienteVal1.setFechaSolicitudPoliza(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-09-10T16:52:15.862+02:00"));
            _returnExpedienteVal1.setProducto("Producto-537613583");
            com.scortelemed.schemas.ama.ResultadoSiniestroResponse.Expediente.Siniestro _returnExpedienteVal1Siniestro = new com.scortelemed.schemas.ama.ResultadoSiniestroResponse.Expediente.Siniestro();
            _returnExpedienteVal1Siniestro.setCodigoST("CodigoST1645056105");
            _returnExpedienteVal1Siniestro.setNumeroSiniestro("NumeroSiniestro-1069642012");
            _returnExpedienteVal1Siniestro.setCausa("Causa400819774");
            _returnExpedienteVal1Siniestro.setCoberturaSiniestrada("CoberturaSiniestrada-1027605362");
            _returnExpedienteVal1Siniestro.setLimitacionFuncional("LimitacionFuncional-765457257");
            _returnExpedienteVal1Siniestro.setFechaOcurrencia(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-09-10T16:52:15.862+02:00"));
            _returnExpedienteVal1Siniestro.setFechaDeclaracion(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-09-10T16:52:15.862+02:00"));
            _returnExpedienteVal1Siniestro.setRentaCapital(new java.math.BigDecimal("-2719241422291052257.7465610059575873071"));
            _returnExpedienteVal1Siniestro.setDescripcionSiniestro("DescripcionSiniestro1923501872");
            _returnExpedienteVal1Siniestro.setTextoBeneficiarios("TextoBeneficiarios1592551978");
            _returnExpedienteVal1Siniestro.setFechaBajaMedica(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-09-10T16:52:15.862+02:00"));
            _returnExpedienteVal1Siniestro.setFechaAltaMedica(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-09-10T16:52:15.862+02:00"));
            _returnExpedienteVal1Siniestro.setFechaInicioDerecho(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-09-10T16:52:15.862+02:00"));
            _returnExpedienteVal1Siniestro.setDiasBajaEstimados(new java.math.BigDecimal("8916873569473934594.3508301811881351673"));
            _returnExpedienteVal1Siniestro.setOficinaGestora("OficinaGestora157797144");
            java.util.List<com.scortelemed.schemas.ama.ResultadoSiniestroResponse.Expediente.Siniestro.Pago> _returnExpedienteVal1SiniestroPago = new java.util.ArrayList<com.scortelemed.schemas.ama.ResultadoSiniestroResponse.Expediente.Siniestro.Pago>();
            _returnExpedienteVal1Siniestro.getPago().addAll(_returnExpedienteVal1SiniestroPago);
            java.util.List<com.scortelemed.schemas.ama.ResultadoSiniestroResponse.Expediente.Siniestro.Provision> _returnExpedienteVal1SiniestroProvision = new java.util.ArrayList<com.scortelemed.schemas.ama.ResultadoSiniestroResponse.Expediente.Siniestro.Provision>();
            _returnExpedienteVal1Siniestro.getProvision().addAll(_returnExpedienteVal1SiniestroProvision);
            _returnExpedienteVal1.setSiniestro(_returnExpedienteVal1Siniestro);
            _returnExpediente.add(_returnExpedienteVal1);
            _return.getExpediente().addAll(_returnExpediente);
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.scortelemed.schemas.ama.AmaUnderwrittingCaseManagementService#gestionReconocimientoMedico(com.scortelemed.schemas.ama.GestionReconocimientoMedicoRequest  gestionReconocimientoMedicoRequest )*
     */
    public com.scortelemed.schemas.ama.GestionReconocimientoMedicoResponse gestionReconocimientoMedico(GestionReconocimientoMedicoRequest gestionReconocimientoMedicoRequest) { 
        LOG.info("Executing operation gestionReconocimientoMedico");
        System.out.println(gestionReconocimientoMedicoRequest);
        try {
            com.scortelemed.schemas.ama.GestionReconocimientoMedicoResponse _return = new com.scortelemed.schemas.ama.GestionReconocimientoMedicoResponse();
            com.scortelemed.schemas.ama.StatusType _returnStatus = com.scortelemed.schemas.ama.StatusType.OK;
            _return.setStatus(_returnStatus);
            _return.setDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-09-10T16:52:15.862+02:00"));
            _return.setMessage("Message910216054");
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.scortelemed.schemas.ama.AmaUnderwrittingCaseManagementService#consultaExpediente(com.scortelemed.schemas.ama.ConsultaExpedienteRequest  consultaExpedienteRequest )*
     */
    public com.scortelemed.schemas.ama.ConsultaExpedienteResponse consultaExpediente(ConsultaExpedienteRequest consultaExpedienteRequest) { 
        LOG.info("Executing operation consultaExpediente");
        System.out.println(consultaExpedienteRequest);
        try {
            com.scortelemed.schemas.ama.ConsultaExpedienteResponse _return = new com.scortelemed.schemas.ama.ConsultaExpedienteResponse();
            _return.setDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-09-10T16:52:15.862+02:00"));
            com.scortelemed.schemas.ama.StatusType _returnStatus = com.scortelemed.schemas.ama.StatusType.OK;
            _return.setStatus(_returnStatus);
            _return.setNotes("Notes-213682146");
            java.util.List<com.scortelemed.schemas.ama.ConsultaExpedienteResponse.Expediente> _returnExpediente = new java.util.ArrayList<com.scortelemed.schemas.ama.ConsultaExpedienteResponse.Expediente>();
            com.scortelemed.schemas.ama.ConsultaExpedienteResponse.Expediente _returnExpedienteVal1 = new com.scortelemed.schemas.ama.ConsultaExpedienteResponse.Expediente();
            com.scortelemed.schemas.ama.CandidateInformationType _returnExpedienteVal1CandidateInformation = new com.scortelemed.schemas.ama.CandidateInformationType();
            _returnExpedienteVal1CandidateInformation.setCodigoSt("CodigoSt-1564447230");
            _returnExpedienteVal1CandidateInformation.setFiscalIdentificationNumber("FiscalIdentificationNumber-204504306");
            _returnExpedienteVal1CandidateInformation.setName("Name439247680");
            _returnExpedienteVal1CandidateInformation.setSurname("Surname-1659555255");
            _returnExpedienteVal1CandidateInformation.setAddress("Address1776926966");
            _returnExpedienteVal1CandidateInformation.setCity("City864511027");
            _returnExpedienteVal1CandidateInformation.setProvince("Province176609154");
            _returnExpedienteVal1CandidateInformation.setCountry("Country-1438216276");
            _returnExpedienteVal1CandidateInformation.setPostalCode("PostalCode-1121649521");
            _returnExpedienteVal1CandidateInformation.setEmail("Email-35571982");
            com.scortelemed.schemas.ama.GenderType _returnExpedienteVal1CandidateInformationGender = com.scortelemed.schemas.ama.GenderType.H;
            _returnExpedienteVal1CandidateInformation.setGender(_returnExpedienteVal1CandidateInformationGender);
            com.scortelemed.schemas.ama.CivilStateType _returnExpedienteVal1CandidateInformationCivilState = com.scortelemed.schemas.ama.CivilStateType.S;
            _returnExpedienteVal1CandidateInformation.setCivilState(_returnExpedienteVal1CandidateInformationCivilState);
            _returnExpedienteVal1CandidateInformation.setMobileNumber("MobileNumber247095872");
            _returnExpedienteVal1CandidateInformation.setPhoneNumber1("PhoneNumber1-1375543191");
            _returnExpedienteVal1CandidateInformation.setPhoneNumber2("PhoneNumber22137136943");
            _returnExpedienteVal1CandidateInformation.setPassword("Password378800804");
            _returnExpedienteVal1CandidateInformation.setProductCode("ProductCode-243617546");
            _returnExpedienteVal1CandidateInformation.setBirthDate("BirthDate-1494926455");
            _returnExpedienteVal1.setCandidateInformation(_returnExpedienteVal1CandidateInformation);
            com.scortelemed.schemas.ama.PolicyHolderInformationType _returnExpedienteVal1PolicyHolderInformation = new com.scortelemed.schemas.ama.PolicyHolderInformationType();
            _returnExpedienteVal1PolicyHolderInformation.setDossierNumber("DossierNumber1309725643");
            _returnExpedienteVal1PolicyHolderInformation.setPolicyNumber("PolicyNumber1747486542");
            _returnExpedienteVal1PolicyHolderInformation.setCertificateNumber("CertificateNumber1377793969");
            _returnExpedienteVal1PolicyHolderInformation.setSuplementNumber("SuplementNumber-1007142371");
            _returnExpedienteVal1PolicyHolderInformation.setRequestDate("RequestDate73034548");
            _returnExpedienteVal1PolicyHolderInformation.setRequestState("RequestState-1331255199");
            _returnExpedienteVal1PolicyHolderInformation.setRequestNumber("RequestNumber46497110");
            _returnExpedienteVal1.setPolicyHolderInformation(_returnExpedienteVal1PolicyHolderInformation);
            java.util.List<com.scortelemed.schemas.ama.BenefitsType> _returnExpedienteVal1Benefits = new java.util.ArrayList<com.scortelemed.schemas.ama.BenefitsType>();
            _returnExpedienteVal1.getBenefits().addAll(_returnExpedienteVal1Benefits);
            java.util.List<com.scortelemed.schemas.ama.AppointmentsType> _returnExpedienteVal1Appointments = new java.util.ArrayList<com.scortelemed.schemas.ama.AppointmentsType>();
            _returnExpedienteVal1.getAppointments().addAll(_returnExpedienteVal1Appointments);
            java.util.List<com.scortelemed.schemas.ama.ActivitiesType> _returnExpedienteVal1Activities = new java.util.ArrayList<com.scortelemed.schemas.ama.ActivitiesType>();
            _returnExpedienteVal1.getActivities().addAll(_returnExpedienteVal1Activities);
            java.util.List<com.scortelemed.schemas.ama.DocumentType> _returnExpedienteVal1Documents = new java.util.ArrayList<com.scortelemed.schemas.ama.DocumentType>();
            _returnExpedienteVal1.getDocuments().addAll(_returnExpedienteVal1Documents);
            _returnExpediente.add(_returnExpedienteVal1);
            _return.getExpediente().addAll(_returnExpediente);
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.scortelemed.schemas.ama.AmaUnderwrittingCaseManagementService#consultaDocumento(com.scortelemed.schemas.ama.ConsultaDocumentoRequest  consultaDocumentoRequest )*
     */
    public com.scortelemed.schemas.ama.ConsultaDocumentoResponse consultaDocumento(ConsultaDocumentoRequest consultaDocumentoRequest) { 
        LOG.info("Executing operation consultaDocumento");
        System.out.println(consultaDocumentoRequest);
        try {
            com.scortelemed.schemas.ama.ConsultaDocumentoResponse _return = new com.scortelemed.schemas.ama.ConsultaDocumentoResponse();
            com.scortelemed.schemas.ama.StatusType _returnStatus = com.scortelemed.schemas.ama.StatusType.OK;
            _return.setStatus(_returnStatus);
            _return.setDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-09-10T16:52:15.862+02:00"));
            _return.setMessage("Message-357504628");
            com.scortelemed.schemas.ama.ConsultaDocumentoResponse.Documento _returnDocumento = new com.scortelemed.schemas.ama.ConsultaDocumentoResponse.Documento();
            _returnDocumento.setCodigoSt("CodigoSt472025078");
            _returnDocumento.setDocumentacionId("DocumentacionId-821734974");
            _returnDocumento.setNodoAlfresco("NodoAlfresco-2060289320");
            byte[] _returnDocumentoContenido = new byte[] {};
            _returnDocumento.setContenido(_returnDocumentoContenido);
            _return.setDocumento(_returnDocumento);
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.scortelemed.schemas.ama.AmaUnderwrittingCaseManagementService#consolidacionPoliza(com.scortelemed.schemas.ama.ConsolidacionPolizaRequest  consolidacionPolizaRequest )*
     */
    public com.scortelemed.schemas.ama.ConsolidacionPolizaResponse consolidacionPoliza(ConsolidacionPolizaRequest consolidacionPolizaRequest) { 
        LOG.info("Executing operation consolidacionPoliza");
        System.out.println(consolidacionPolizaRequest);
        try {
            com.scortelemed.schemas.ama.ConsolidacionPolizaResponse _return = new com.scortelemed.schemas.ama.ConsolidacionPolizaResponse();
            com.scortelemed.schemas.ama.StatusType _returnStatus = com.scortelemed.schemas.ama.StatusType.OK;
            _return.setStatus(_returnStatus);
            _return.setDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-09-10T16:52:15.862+02:00"));
            _return.setMessage("Message-552555167");
            _return.setCodigo(719019042);
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
