
package com.scortelemed.schemas.ama;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.1
 * Mon Sep 10 16:52:15 CEST 2018
 * Generated source version: 2.1
 * 
 */

@WebService(targetNamespace = "http://www.scortelemed.com/schemas/ama", name = "AmaUnderwrittingCaseManagementService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)

public interface AmaUnderwrittingCaseManagementService {

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "ResultadoSiniestroResponse", targetNamespace = "http://www.scortelemed.com/schemas/ama", partName = "ResultadoSiniestroResponse")
    @WebMethod
    public ResultadoSiniestroResponse resultadoSiniestro(
        @WebParam(partName = "ResultadoSiniestroRequest", name = "ResultadoSiniestroRequest", targetNamespace = "http://www.scortelemed.com/schemas/ama")
        ResultadoSiniestroRequest resultadoSiniestroRequest
    );

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "GestionReconocimientoMedicoResponse", targetNamespace = "http://www.scortelemed.com/schemas/ama", partName = "GestionReconocimientoMedicoResponse")
    @WebMethod
    public GestionReconocimientoMedicoResponse gestionReconocimientoMedico(
        @WebParam(partName = "GestionReconocimientoMedicoRequest", name = "GestionReconocimientoMedicoRequest", targetNamespace = "http://www.scortelemed.com/schemas/ama")
        GestionReconocimientoMedicoRequest gestionReconocimientoMedicoRequest
    );

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "ConsultaExpediente", targetNamespace = "http://www.scortelemed.com/schemas/ama", partName = "ConsultaExpediente")
    @WebMethod
    public ConsultaExpedienteResponse consultaExpediente(
        @WebParam(partName = "ConsultaExpedienteRequest", name = "ConsultaExpedienteRequest", targetNamespace = "http://www.scortelemed.com/schemas/ama")
        ConsultaExpedienteRequest consultaExpedienteRequest
    );

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "ConsultaDocumento", targetNamespace = "http://www.scortelemed.com/schemas/ama", partName = "ConsultaDocumento")
    @WebMethod
    public ConsultaDocumentoResponse consultaDocumento(
        @WebParam(partName = "ConsultaDocumentoRequest", name = "ConsultaDocumentoRequest", targetNamespace = "http://www.scortelemed.com/schemas/ama")
        ConsultaDocumentoRequest consultaDocumentoRequest
    );

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "ConsolidacionPolizaResponse", targetNamespace = "http://www.scortelemed.com/schemas/ama", partName = "ConsolidacionPolizaResponse")
    @WebMethod
    public ConsolidacionPolizaResponse consolidacionPoliza(
        @WebParam(partName = "ConsolidacionPolizaRequest", name = "ConsolidacionPolizaRequest", targetNamespace = "http://www.scortelemed.com/schemas/ama")
        ConsolidacionPolizaRequest consolidacionPolizaRequest
    );
}
