
package com.scortelemed.schemas.ama;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 2.1
 * Mon Sep 10 16:52:15 CEST 2018
 * Generated source version: 2.1
 * 
 */

@WebServiceClient(name = "AmaUnderwrittingCaseManagementServiceService", targetNamespace = "http://www.scortelemed.com/schemas/ama", wsdlLocation = "https://www.scortelemed.com:9090/webservicessoap/services/ama/AmaUnderwrittingCaseManagement?wsdl")
public class AmaUnderwrittingCaseManagementServiceService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://www.scortelemed.com/schemas/ama", "AmaUnderwrittingCaseManagementServiceService");
    public final static QName AmaUnderwrittingCaseManagementServicePort = new QName("http://www.scortelemed.com/schemas/ama", "AmaUnderwrittingCaseManagementServicePort");
    static {
        URL url = null;
        try {
            url = new URL("https://www.scortelemed.com:9090/webservicessoap/services/ama/AmaUnderwrittingCaseManagement?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from https://www.scortelemed.com:9090/webservicessoap/services/ama/AmaUnderwrittingCaseManagement?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public AmaUnderwrittingCaseManagementServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AmaUnderwrittingCaseManagementServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AmaUnderwrittingCaseManagementServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns AmaUnderwrittingCaseManagementService
     */
    @WebEndpoint(name = "AmaUnderwrittingCaseManagementServicePort")
    public AmaUnderwrittingCaseManagementService getAmaUnderwrittingCaseManagementServicePort() {
        return super.getPort(AmaUnderwrittingCaseManagementServicePort, AmaUnderwrittingCaseManagementService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AmaUnderwrittingCaseManagementService
     */
    @WebEndpoint(name = "AmaUnderwrittingCaseManagementServicePort")
    public AmaUnderwrittingCaseManagementService getAmaUnderwrittingCaseManagementServicePort(WebServiceFeature... features) {
        return super.getPort(AmaUnderwrittingCaseManagementServicePort, AmaUnderwrittingCaseManagementService.class, features);
    }

}
