
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.scortelemed.schemas.cbpita;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.1
 * Tue Mar 19 16:43:31 CET 2019
 * Generated source version: 2.1
 * 
 */

@WebService(name = "CbpitaUnderwrittingCaseManagementService",
                      serviceName = "CbpitaUnderwrittingCaseManagementServiceService",
                      portName = "CbpitaUnderwrittingCaseManagementServicePort",
                      targetNamespace = "http://www.scortelemed.com/schemas/cbpita", 
                      wsdlLocation = "http://localhost:8080/scorWebservice/services/cbpita/CbpitaUnderwrittingCaseManagement?wsdl",
                      endpointInterface = "com.scortelemed.schemas.cbpita.CbpitaUnderwrittingCaseManagementService")
                      
public class CbpitaUnderwrittingCaseManagementServiceImpl implements CbpitaUnderwrittingCaseManagementService {

    private static final Logger LOG = Logger.getLogger(CbpitaUnderwrittingCaseManagementServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see com.scortelemed.schemas.cbpita.CbpitaUnderwrittingCaseManagementService#netInsuranteUnderwrittingCasesResults(com.scortelemed.schemas.cbpita.CbpitaUnderwrittingCasesResultsRequest  caseManagementResultsRequest )*
     */
    public com.scortelemed.schemas.cbpita.CbpitaUnderwrittingCasesResultsResponse netInsuranteUnderwrittingCasesResults(CbpitaUnderwrittingCasesResultsRequest caseManagementResultsRequest) { 
        LOG.info("Executing operation netInsuranteUnderwrittingCasesResults");
        System.out.println(caseManagementResultsRequest);
        try {
            com.scortelemed.schemas.cbpita.CbpitaUnderwrittingCasesResultsResponse _return = new com.scortelemed.schemas.cbpita.CbpitaUnderwrittingCasesResultsResponse();
            _return.setDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2019-03-19T16:43:31.665+01:00"));
            com.scortelemed.schemas.cbpita.StatusType _returnStatus = com.scortelemed.schemas.cbpita.StatusType.ERROR;
            _return.setStatus(_returnStatus);
            _return.setMessage("Message-1910477700");
            _return.setCode(-946918528);
            java.util.List<com.scortelemed.schemas.cbpita.CbpitaUnderwrittingCasesResultsResponse.Expediente> _returnExpediente = new java.util.ArrayList<com.scortelemed.schemas.cbpita.CbpitaUnderwrittingCasesResultsResponse.Expediente>();
            com.scortelemed.schemas.cbpita.CbpitaUnderwrittingCasesResultsResponse.Expediente _returnExpedienteVal1 = new com.scortelemed.schemas.cbpita.CbpitaUnderwrittingCasesResultsResponse.Expediente();
            _returnExpedienteVal1.setRequestDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2019-03-19T16:43:31.665+01:00"));
            _returnExpedienteVal1.setRequestNumber("RequestNumber1493210397");
            com.scortelemed.schemas.cbpita.RequestStateType _returnExpedienteVal1RequestState = com.scortelemed.schemas.cbpita.RequestStateType.CLOSED;
            _returnExpedienteVal1.setRequestState(_returnExpedienteVal1RequestState);
            _returnExpedienteVal1.setProductCode("ProductCode1979009399");
            _returnExpedienteVal1.setPolicyNumber("PolicyNumber-1984610315");
            _returnExpedienteVal1.setCertificateNumber("CertificateNumber1893722762");
            _returnExpedienteVal1.setFiscalIdentificationNumber("FiscalIdentificationNumber-1712285345");
            _returnExpedienteVal1.setMobilePhone("MobilePhone-254231297");
            _returnExpedienteVal1.setPhoneNumber1("PhoneNumber11350375597");
            _returnExpedienteVal1.setPhoneNumber2("PhoneNumber2330652216");
            java.util.List<com.scortelemed.schemas.cbpita.BenefitsType> _returnExpedienteVal1BenefitsList = new java.util.ArrayList<com.scortelemed.schemas.cbpita.BenefitsType>();
            _returnExpedienteVal1.getBenefitsList().addAll(_returnExpedienteVal1BenefitsList);
            byte[] _returnExpedienteVal1Zip = new byte[] {};
            _returnExpedienteVal1.setZip(_returnExpedienteVal1Zip);
            _returnExpedienteVal1.setNotes("Notes2129419396");
            _returnExpediente.add(_returnExpedienteVal1);
            _return.getExpediente().addAll(_returnExpediente);
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.scortelemed.schemas.cbpita.CbpitaUnderwrittingCaseManagementService#netInsuranteUnderwrittingCaseManagement(com.scortelemed.schemas.cbpita.CbpitaUnderwrittingCaseManagementRequest  caseManagementRequest )*
     */
    public com.scortelemed.schemas.cbpita.CbpitaUnderwrittingCaseManagementResponse netInsuranteUnderwrittingCaseManagement(CbpitaUnderwrittingCaseManagementRequest caseManagementRequest) { 
        LOG.info("Executing operation netInsuranteUnderwrittingCaseManagement");
        System.out.println(caseManagementRequest);
        try {
            com.scortelemed.schemas.cbpita.CbpitaUnderwrittingCaseManagementResponse _return = new com.scortelemed.schemas.cbpita.CbpitaUnderwrittingCaseManagementResponse();
            com.scortelemed.schemas.cbpita.StatusType _returnStatus = com.scortelemed.schemas.cbpita.StatusType.ERROR;
            _return.setStatus(_returnStatus);
            _return.setDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2019-03-19T16:43:31.666+01:00"));
            _return.setMessage("Message-672231183");
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
