
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.scortelemed.schemas.cbpita;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.1
 * Tue Nov 06 11:23:53 CET 2018
 * Generated source version: 2.1
 * 
 */

@WebService(name = "CbpitaUnderwrittingCaseManagementService",
                      serviceName = "CbpitaUnderwrittingCaseManagementServiceService",
                      portName = "CbpitaUnderwrittingCaseManagementServicePort",
                      targetNamespace = "http://www.scortelemed.com/schemas/cbpita", 
                      wsdlLocation = "http://localhost:8080/scorWebservice/services/cbpita/CbpitaUnderwrittingCaseManagement?wsdl",
                      endpointInterface = "com.scortelemed.schemas.cbpita.CbpitaUnderwrittingCaseManagementService")
                      
public class CbpitaUnderwrittingCaseManagementServiceImpl implements CbpitaUnderwrittingCaseManagementService {

    private static final Logger LOG = Logger.getLogger(CbpitaUnderwrittingCaseManagementServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see com.scortelemed.schemas.cbpita.CbpitaUnderwrittingCaseManagementService#cbpitaUnderwrittingCaseManagement(com.scortelemed.schemas.cbpita.CbpitaUnderwrittingCaseManagementRequest  caseManagementRequest )*
     */
    public CbpitaUnderwrittingCaseManagementResponse cbpitaUnderwrittingCaseManagement(CbpitaUnderwrittingCaseManagementRequest caseManagementRequest) {
        LOG.info("Executing operation cbpitaUnderwrittingCaseManagement");
        System.out.println(caseManagementRequest);
        try {
            CbpitaUnderwrittingCaseManagementResponse _return = new CbpitaUnderwrittingCaseManagementResponse();
            StatusType _returnStatus = StatusType.OK;
            _return.setStatus(_returnStatus);
            _return.setDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-11-06T11:23:53.747+01:00"));
            _return.setMessage("Message1284073650");
            _return.setCode("Code-429599722");
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
