
package com.scortelemed.schemas.cbpita;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.1
 * Tue Nov 06 11:23:53 CET 2018
 * Generated source version: 2.1
 * 
 */

@WebService(targetNamespace = "http://www.scortelemed.com/schemas/cbpita", name = "CbpitaUnderwrittingCaseManagementService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = ParameterStyle.BARE)

public interface CbpitaUnderwrittingCaseManagementService {

    @SOAPBinding(parameterStyle = ParameterStyle.BARE)
    @WebResult(name = "caseManagementResponse", targetNamespace = "http://www.scortelemed.com/schemas/cbpita", partName = "caseManagementResponse")
    @WebMethod
    public CbpitaUnderwrittingCaseManagementResponse cbpitaUnderwrittingCaseManagement(
            @WebParam(partName = "CaseManagementRequest", name = "CaseManagementRequest", targetNamespace = "http://www.scortelemed.com/schemas/cbpita")
                    CbpitaUnderwrittingCaseManagementRequest caseManagementRequest
    );
}
