
package com.scortelemed.schemas.cbpita;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.1
 * Tue Mar 19 16:43:31 CET 2019
 * Generated source version: 2.1
 * 
 */

public final class CbpitaUnderwrittingCaseManagementService_CbpitaUnderwrittingCaseManagementServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://www.scortelemed.com/schemas/cbpita", "CbpitaUnderwrittingCaseManagementServiceService");

    private CbpitaUnderwrittingCaseManagementService_CbpitaUnderwrittingCaseManagementServicePort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = CbpitaUnderwrittingCaseManagementServiceService.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        CbpitaUnderwrittingCaseManagementServiceService ss = new CbpitaUnderwrittingCaseManagementServiceService(wsdlURL, SERVICE_NAME);
        CbpitaUnderwrittingCaseManagementService port = ss.getCbpitaUnderwrittingCaseManagementServicePort();  
        
        {
        System.out.println("Invoking netInsuranteUnderwrittingCasesResults...");
        com.scortelemed.schemas.cbpita.CbpitaUnderwrittingCasesResultsRequest _netInsuranteUnderwrittingCasesResults_caseManagementResultsRequest = new com.scortelemed.schemas.cbpita.CbpitaUnderwrittingCasesResultsRequest();
        _netInsuranteUnderwrittingCasesResults_caseManagementResultsRequest.setDateStart(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2019-03-19T16:43:31.650+01:00"));
        _netInsuranteUnderwrittingCasesResults_caseManagementResultsRequest.setDateEnd(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2019-03-19T16:43:31.658+01:00"));
        CbpitaUnderwrittingCasesResultsResponse _netInsuranteUnderwrittingCasesResults__return = port.netInsuranteUnderwrittingCasesResults(_netInsuranteUnderwrittingCasesResults_caseManagementResultsRequest);
        System.out.println("netInsuranteUnderwrittingCasesResults.result=" + _netInsuranteUnderwrittingCasesResults__return);


        }
        {
        System.out.println("Invoking netInsuranteUnderwrittingCaseManagement...");
        CbpitaUnderwrittingCaseManagementRequest _netInsuranteUnderwrittingCaseManagement_caseManagementRequest = new CbpitaUnderwrittingCaseManagementRequest();
        CbpitaUnderwrittingCaseManagementRequest.CandidateInformation _netInsuranteUnderwrittingCaseManagement_caseManagementRequestCandidateInformation = new CbpitaUnderwrittingCaseManagementRequest.CandidateInformation();
        _netInsuranteUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setProductCode("ProductCode1109526450");
        _netInsuranteUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setRequestNumber("RequestNumber-10814661");
        _netInsuranteUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setPolicyNumber("PolicyNumber-189542370");
        _netInsuranteUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setCertificateNumber("CertificateNumber-1298290374");
        _netInsuranteUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setRequestDate("RequestDate198019783");
        _netInsuranteUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setPassword("Password97151837");
        _netInsuranteUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setRequestState("RequestState121032571");
        _netInsuranteUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setName("Name-1708802169");
        _netInsuranteUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setSurname("Surname1885601824");
        _netInsuranteUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setAddress("Address-1898211233");
        _netInsuranteUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setPostalCode("PostalCode-1993798851");
        _netInsuranteUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setCity("City-1463032788");
        _netInsuranteUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setProvince("Province1087383895");
        _netInsuranteUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setCountry("Country661562684");
        _netInsuranteUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setPhoneNumber1("PhoneNumber1165639238");
        _netInsuranteUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setPhoneNumber2("PhoneNumber2-932068821");
        _netInsuranteUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setMobileNumber("MobileNumber150545082");
        _netInsuranteUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setEmail("Email34758338");
        _netInsuranteUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setBirthDate("BirthDate-1309462659");
        _netInsuranteUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setActuarialAge("ActuarialAge773251654");
        _netInsuranteUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setBirthCity("BirthCity247436094");
        _netInsuranteUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setFiscalIdentificationNumber("FiscalIdentificationNumber-824779148");
        _netInsuranteUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setAgency("Agency1215940834");
        _netInsuranteUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setAgent("Agent2132435580");
        _netInsuranteUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setAgentPhone("AgentPhone-544643149");
        _netInsuranteUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setAgentEmail("AgentEmail904722354");
        GenderType _netInsuranteUnderwrittingCaseManagement_caseManagementRequestCandidateInformationGender = GenderType.H;
        _netInsuranteUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setGender(_netInsuranteUnderwrittingCaseManagement_caseManagementRequestCandidateInformationGender);
        CivilStateType _netInsuranteUnderwrittingCaseManagement_caseManagementRequestCandidateInformationCivilState = CivilStateType.D;
        _netInsuranteUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setCivilState(_netInsuranteUnderwrittingCaseManagement_caseManagementRequestCandidateInformationCivilState);
        _netInsuranteUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setCustomerType("CustomerType-370045639");
        ContactTimeType _netInsuranteUnderwrittingCaseManagement_caseManagementRequestCandidateInformationContactTime = ContactTimeType.T;
        _netInsuranteUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setContactTime(_netInsuranteUnderwrittingCaseManagement_caseManagementRequestCandidateInformationContactTime);
        _netInsuranteUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setComments("Comments991878381");
        _netInsuranteUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setEUWReferenceCode("EUWReferenceCode-1696439208");
        _netInsuranteUnderwrittingCaseManagement_caseManagementRequest.setCandidateInformation(_netInsuranteUnderwrittingCaseManagement_caseManagementRequestCandidateInformation);
        java.util.List<CbpitaUnderwrittingCaseManagementRequest.PreviousQuestions> _netInsuranteUnderwrittingCaseManagement_caseManagementRequestPreviousQuestions = new java.util.ArrayList<CbpitaUnderwrittingCaseManagementRequest.PreviousQuestions>();
        CbpitaUnderwrittingCaseManagementRequest.PreviousQuestions _netInsuranteUnderwrittingCaseManagement_caseManagementRequestPreviousQuestionsVal1 = new CbpitaUnderwrittingCaseManagementRequest.PreviousQuestions();
        QuestionDataType _netInsuranteUnderwrittingCaseManagement_caseManagementRequestPreviousQuestionsVal1DataType = QuestionDataType.DATE;
        _netInsuranteUnderwrittingCaseManagement_caseManagementRequestPreviousQuestionsVal1.setDataType(_netInsuranteUnderwrittingCaseManagement_caseManagementRequestPreviousQuestionsVal1DataType);
        _netInsuranteUnderwrittingCaseManagement_caseManagementRequestPreviousQuestionsVal1.setAnswerCode("AnswerCode1063279650");
        _netInsuranteUnderwrittingCaseManagement_caseManagementRequestPreviousQuestionsVal1.setQuestion("Question-55865275");
        _netInsuranteUnderwrittingCaseManagement_caseManagementRequestPreviousQuestionsVal1.setAnswer("Answer-1624427676");
        _netInsuranteUnderwrittingCaseManagement_caseManagementRequestPreviousQuestions.add(_netInsuranteUnderwrittingCaseManagement_caseManagementRequestPreviousQuestionsVal1);
        _netInsuranteUnderwrittingCaseManagement_caseManagementRequest.getPreviousQuestions().addAll(_netInsuranteUnderwrittingCaseManagement_caseManagementRequestPreviousQuestions);
        java.util.List<CbpitaUnderwrittingCaseManagementRequest.Services> _netInsuranteUnderwrittingCaseManagement_caseManagementRequestServices = new java.util.ArrayList<CbpitaUnderwrittingCaseManagementRequest.Services>();
        CbpitaUnderwrittingCaseManagementRequest.Services _netInsuranteUnderwrittingCaseManagement_caseManagementRequestServicesVal1 = new CbpitaUnderwrittingCaseManagementRequest.Services();
        _netInsuranteUnderwrittingCaseManagement_caseManagementRequestServicesVal1.setServiceType("ServiceType-1387742472");
        _netInsuranteUnderwrittingCaseManagement_caseManagementRequestServicesVal1.setServiceCode("ServiceCode-1445698281");
        _netInsuranteUnderwrittingCaseManagement_caseManagementRequestServicesVal1.setServiceDescription("ServiceDescription367311383");
        _netInsuranteUnderwrittingCaseManagement_caseManagementRequestServices.add(_netInsuranteUnderwrittingCaseManagement_caseManagementRequestServicesVal1);
        _netInsuranteUnderwrittingCaseManagement_caseManagementRequest.getServices().addAll(_netInsuranteUnderwrittingCaseManagement_caseManagementRequestServices);
        BenefitsType _netInsuranteUnderwrittingCaseManagement_caseManagementRequestBenefits = new BenefitsType();
        BenefictNameType _netInsuranteUnderwrittingCaseManagement_caseManagementRequestBenefitsBenefictName = BenefictNameType.ACCIDENTAL_DEAD;
        _netInsuranteUnderwrittingCaseManagement_caseManagementRequestBenefits.setBenefictName(_netInsuranteUnderwrittingCaseManagement_caseManagementRequestBenefitsBenefictName);
        _netInsuranteUnderwrittingCaseManagement_caseManagementRequestBenefits.setBenefictCode("BenefictCode-861867375");
        _netInsuranteUnderwrittingCaseManagement_caseManagementRequestBenefits.setBenefictCapital("BenefictCapital1434297639");
        BenefictResultType _netInsuranteUnderwrittingCaseManagement_caseManagementRequestBenefitsBenefictResult = new BenefictResultType();
        _netInsuranteUnderwrittingCaseManagement_caseManagementRequestBenefitsBenefictResult.setDescResult("DescResult-125967409");
        _netInsuranteUnderwrittingCaseManagement_caseManagementRequestBenefitsBenefictResult.setResultCode("ResultCode-2042479030");
        _netInsuranteUnderwrittingCaseManagement_caseManagementRequestBenefitsBenefictResult.setPremiumLoading("PremiumLoading-1349645919");
        _netInsuranteUnderwrittingCaseManagement_caseManagementRequestBenefitsBenefictResult.setCapitalLoading("CapitalLoading-642976562");
        _netInsuranteUnderwrittingCaseManagement_caseManagementRequestBenefitsBenefictResult.setDescPremiumLoading("DescPremiumLoading-122416473");
        _netInsuranteUnderwrittingCaseManagement_caseManagementRequestBenefitsBenefictResult.setDescCapitalLoading("DescCapitalLoading-1195104968");
        java.util.List<String> _netInsuranteUnderwrittingCaseManagement_caseManagementRequestBenefitsBenefictResultTemporalLoading = new java.util.ArrayList<String>();
        _netInsuranteUnderwrittingCaseManagement_caseManagementRequestBenefitsBenefictResult.getTemporalLoading().addAll(_netInsuranteUnderwrittingCaseManagement_caseManagementRequestBenefitsBenefictResultTemporalLoading);
        java.util.List<String> _netInsuranteUnderwrittingCaseManagement_caseManagementRequestBenefitsBenefictResultExclusions = new java.util.ArrayList<String>();
        _netInsuranteUnderwrittingCaseManagement_caseManagementRequestBenefitsBenefictResult.getExclusions().addAll(_netInsuranteUnderwrittingCaseManagement_caseManagementRequestBenefitsBenefictResultExclusions);
        java.util.List<String> _netInsuranteUnderwrittingCaseManagement_caseManagementRequestBenefitsBenefictResultMedicalReports = new java.util.ArrayList<String>();
        _netInsuranteUnderwrittingCaseManagement_caseManagementRequestBenefitsBenefictResult.getMedicalReports().addAll(_netInsuranteUnderwrittingCaseManagement_caseManagementRequestBenefitsBenefictResultMedicalReports);
        java.util.List<String> _netInsuranteUnderwrittingCaseManagement_caseManagementRequestBenefitsBenefictResultMedicalTest = new java.util.ArrayList<String>();
        _netInsuranteUnderwrittingCaseManagement_caseManagementRequestBenefitsBenefictResult.getMedicalTest().addAll(_netInsuranteUnderwrittingCaseManagement_caseManagementRequestBenefitsBenefictResultMedicalTest);
        java.util.List<String> _netInsuranteUnderwrittingCaseManagement_caseManagementRequestBenefitsBenefictResultNotes = new java.util.ArrayList<String>();
        _netInsuranteUnderwrittingCaseManagement_caseManagementRequestBenefitsBenefictResult.getNotes().addAll(_netInsuranteUnderwrittingCaseManagement_caseManagementRequestBenefitsBenefictResultNotes);
        _netInsuranteUnderwrittingCaseManagement_caseManagementRequestBenefits.setBenefictResult(_netInsuranteUnderwrittingCaseManagement_caseManagementRequestBenefitsBenefictResult);
        _netInsuranteUnderwrittingCaseManagement_caseManagementRequest.setBenefits(_netInsuranteUnderwrittingCaseManagement_caseManagementRequestBenefits);
        CbpitaUnderwrittingCaseManagementResponse _netInsuranteUnderwrittingCaseManagement__return = port.netInsuranteUnderwrittingCaseManagement(_netInsuranteUnderwrittingCaseManagement_caseManagementRequest);
        System.out.println("netInsuranteUnderwrittingCaseManagement.result=" + _netInsuranteUnderwrittingCaseManagement__return);


        }

        System.exit(0);
    }

}
