
package com.scortelemed.schemas.cbpita;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 2.1
 * Tue Nov 06 11:23:53 CET 2018
 * Generated source version: 2.1
 * 
 */

@WebServiceClient(name = "CbpitaUnderwrittingCaseManagementServiceService", targetNamespace = "http://www.scortelemed.com/schemas/cbpita", wsdlLocation = "http://localhost:8080/scorWebservice/services/cbpita/CbpitaUnderwrittingCaseManagement?wsdl")
public class CbpitaUnderwrittingCaseManagementServiceService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://www.scortelemed.com/schemas/cbpita", "CbpitaUnderwrittingCaseManagementServiceService");
    public final static QName CbpitaUnderwrittingCaseManagementServicePort = new QName("http://www.scortelemed.com/schemas/cbpita", "CbpitaUnderwrittingCaseManagementServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/scorWebservice/services/cbpita/CbpitaUnderwrittingCaseManagement?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://localhost:8080/scorWebservice/services/cbpita/CbpitaUnderwrittingCaseManagement?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public CbpitaUnderwrittingCaseManagementServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CbpitaUnderwrittingCaseManagementServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CbpitaUnderwrittingCaseManagementServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns CbpitaUnderwrittingCaseManagementService
     */
    @WebEndpoint(name = "CbpitaUnderwrittingCaseManagementServicePort")
    public CbpitaUnderwrittingCaseManagementService getCbpitaUnderwrittingCaseManagementServicePort() {
        return super.getPort(CbpitaUnderwrittingCaseManagementServicePort, CbpitaUnderwrittingCaseManagementService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CbpitaUnderwrittingCaseManagementService
     */
    @WebEndpoint(name = "CbpitaUnderwrittingCaseManagementServicePort")
    public CbpitaUnderwrittingCaseManagementService getCbpitaUnderwrittingCaseManagementServicePort(WebServiceFeature... features) {
        return super.getPort(CbpitaUnderwrittingCaseManagementServicePort, CbpitaUnderwrittingCaseManagementService.class, features);
    }

}
