
package com.scortelemed.schemas.cbpita;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.1
 * Tue Nov 06 11:23:53 CET 2018
 * Generated source version: 2.1
 * 
 */

public final class CbpitaUnderwrittingCaseManagementService_CbpitaUnderwrittingCaseManagementServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://www.scortelemed.com/schemas/cbpita", "CbpitaUnderwrittingCaseManagementServiceService");

    private CbpitaUnderwrittingCaseManagementService_CbpitaUnderwrittingCaseManagementServicePort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = CbpitaUnderwrittingCaseManagementServiceService.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        CbpitaUnderwrittingCaseManagementServiceService ss = new CbpitaUnderwrittingCaseManagementServiceService(wsdlURL, SERVICE_NAME);
        CbpitaUnderwrittingCaseManagementService port = ss.getCbpitaUnderwrittingCaseManagementServicePort();  
        
        {
        System.out.println("Invoking cbpitaUnderwrittingCaseManagement...");
        CbpitaUnderwrittingCaseManagementRequest _cbpitaUnderwrittingCaseManagement_caseManagementRequest = new CbpitaUnderwrittingCaseManagementRequest();
        CbpitaUnderwrittingCaseManagementRequest.CandidateInformation _cbpitaUnderwrittingCaseManagement_caseManagementRequestCandidateInformation = new CbpitaUnderwrittingCaseManagementRequest.CandidateInformation();
        _cbpitaUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setProductCode("ProductCode-1462397543");
        _cbpitaUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setRequestNumber("RequestNumber-560629412");
        _cbpitaUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setPolicyNumber("PolicyNumber-144162082");
        _cbpitaUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setCertificateNumber("CertificateNumber-1126912067");
        _cbpitaUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setRequestDate("RequestDate536781948");
        _cbpitaUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setPassword("Password2046896816");
        _cbpitaUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setRequestState("RequestState335066674");
        _cbpitaUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setName("Name-2120321653");
        _cbpitaUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setSurname("Surname-109834536");
        _cbpitaUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setAddress("Address-498254909");
        _cbpitaUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setPostalCode("PostalCode-1966375287");
        _cbpitaUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setCity("City1825382362");
        _cbpitaUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setProvince("Province-1745334406");
        _cbpitaUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setCountry("Country1758400784");
        _cbpitaUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setPhoneNumber1("PhoneNumber11463451324");
        _cbpitaUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setPhoneNumber2("PhoneNumber2-283160099");
        _cbpitaUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setMobileNumber("MobileNumber-1477744064");
        _cbpitaUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setEmail("Email-225508221");
        _cbpitaUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setBirthDate("BirthDate-1599114290");
        _cbpitaUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setActuarialAge("ActuarialAge2089322561");
        _cbpitaUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setBirthCity("BirthCity193692891");
        _cbpitaUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setFiscalIdentificationNumber("FiscalIdentificationNumber1706658019");
        _cbpitaUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setAgency("Agency1083852113");
        _cbpitaUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setAgent("Agent-1233441851");
        _cbpitaUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setAgentPhone("AgentPhone-509622315");
        _cbpitaUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setAgentEmail("AgentEmail-298151797");
        GenderType _cbpitaUnderwrittingCaseManagement_caseManagementRequestCandidateInformationGender = GenderType.H;
        _cbpitaUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setGender(_cbpitaUnderwrittingCaseManagement_caseManagementRequestCandidateInformationGender);
        CivilStateType _cbpitaUnderwrittingCaseManagement_caseManagementRequestCandidateInformationCivilState = CivilStateType.D;
        _cbpitaUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setCivilState(_cbpitaUnderwrittingCaseManagement_caseManagementRequestCandidateInformationCivilState);
        _cbpitaUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setCustomerType("CustomerType-385758251");
        ContactTimeType _cbpitaUnderwrittingCaseManagement_caseManagementRequestCandidateInformationContactTime = ContactTimeType.T;
        _cbpitaUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setContactTime(_cbpitaUnderwrittingCaseManagement_caseManagementRequestCandidateInformationContactTime);
        _cbpitaUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setComments("Comments1656006350");
        _cbpitaUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setEUWReferenceCode("EUWReferenceCode402395582");
        _cbpitaUnderwrittingCaseManagement_caseManagementRequest.setCandidateInformation(_cbpitaUnderwrittingCaseManagement_caseManagementRequestCandidateInformation);
        java.util.List<CbpitaUnderwrittingCaseManagementRequest.PreviousQuestions> _cbpitaUnderwrittingCaseManagement_caseManagementRequestPreviousQuestions = new java.util.ArrayList<CbpitaUnderwrittingCaseManagementRequest.PreviousQuestions>();
        CbpitaUnderwrittingCaseManagementRequest.PreviousQuestions _cbpitaUnderwrittingCaseManagement_caseManagementRequestPreviousQuestionsVal1 = new CbpitaUnderwrittingCaseManagementRequest.PreviousQuestions();
        QuestionDataType _cbpitaUnderwrittingCaseManagement_caseManagementRequestPreviousQuestionsVal1DataType = QuestionDataType.INTEGER;
        _cbpitaUnderwrittingCaseManagement_caseManagementRequestPreviousQuestionsVal1.setDataType(_cbpitaUnderwrittingCaseManagement_caseManagementRequestPreviousQuestionsVal1DataType);
        _cbpitaUnderwrittingCaseManagement_caseManagementRequestPreviousQuestionsVal1.setAnswerCode("AnswerCode173838334");
        _cbpitaUnderwrittingCaseManagement_caseManagementRequestPreviousQuestionsVal1.setQuestion("Question1115891126");
        _cbpitaUnderwrittingCaseManagement_caseManagementRequestPreviousQuestionsVal1.setAnswer("Answer-1119925573");
        _cbpitaUnderwrittingCaseManagement_caseManagementRequestPreviousQuestions.add(_cbpitaUnderwrittingCaseManagement_caseManagementRequestPreviousQuestionsVal1);
        _cbpitaUnderwrittingCaseManagement_caseManagementRequest.getPreviousQuestions().addAll(_cbpitaUnderwrittingCaseManagement_caseManagementRequestPreviousQuestions);
        java.util.List<CbpitaUnderwrittingCaseManagementRequest.Services> _cbpitaUnderwrittingCaseManagement_caseManagementRequestServices = new java.util.ArrayList<CbpitaUnderwrittingCaseManagementRequest.Services>();
        CbpitaUnderwrittingCaseManagementRequest.Services _cbpitaUnderwrittingCaseManagement_caseManagementRequestServicesVal1 = new CbpitaUnderwrittingCaseManagementRequest.Services();
        _cbpitaUnderwrittingCaseManagement_caseManagementRequestServicesVal1.setServiceType("ServiceType-626495643");
        _cbpitaUnderwrittingCaseManagement_caseManagementRequestServicesVal1.setServiceCode("ServiceCode1333724212");
        _cbpitaUnderwrittingCaseManagement_caseManagementRequestServicesVal1.setServiceDescription("ServiceDescription1289171826");
        _cbpitaUnderwrittingCaseManagement_caseManagementRequestServices.add(_cbpitaUnderwrittingCaseManagement_caseManagementRequestServicesVal1);
        _cbpitaUnderwrittingCaseManagement_caseManagementRequest.getServices().addAll(_cbpitaUnderwrittingCaseManagement_caseManagementRequestServices);
        BenefitsType _cbpitaUnderwrittingCaseManagement_caseManagementRequestBenefits = new BenefitsType();
        BenefictNameType _cbpitaUnderwrittingCaseManagement_caseManagementRequestBenefitsBenefictName = BenefictNameType.DEPENDENCY;
        _cbpitaUnderwrittingCaseManagement_caseManagementRequestBenefits.setBenefictName(_cbpitaUnderwrittingCaseManagement_caseManagementRequestBenefitsBenefictName);
        _cbpitaUnderwrittingCaseManagement_caseManagementRequestBenefits.setBenefictCode("BenefictCode2147025842");
        _cbpitaUnderwrittingCaseManagement_caseManagementRequestBenefits.setBenefictCapital("BenefictCapital-178366286");
        BenefictResultType _cbpitaUnderwrittingCaseManagement_caseManagementRequestBenefitsBenefictResult = new BenefictResultType();
        _cbpitaUnderwrittingCaseManagement_caseManagementRequestBenefitsBenefictResult.setDescResult("DescResult-1739039496");
        _cbpitaUnderwrittingCaseManagement_caseManagementRequestBenefitsBenefictResult.setResultCode("ResultCode1414976651");
        _cbpitaUnderwrittingCaseManagement_caseManagementRequestBenefitsBenefictResult.setPremiumLoading("PremiumLoading-1523338552");
        _cbpitaUnderwrittingCaseManagement_caseManagementRequestBenefitsBenefictResult.setCapitalLoading("CapitalLoading-956371968");
        _cbpitaUnderwrittingCaseManagement_caseManagementRequestBenefitsBenefictResult.setDescPremiumLoading("DescPremiumLoading1371404130");
        _cbpitaUnderwrittingCaseManagement_caseManagementRequestBenefitsBenefictResult.setDescCapitalLoading("DescCapitalLoading-1158890966");
        java.util.List<String> _cbpitaUnderwrittingCaseManagement_caseManagementRequestBenefitsBenefictResultTemporalLoading = new java.util.ArrayList<String>();
        _cbpitaUnderwrittingCaseManagement_caseManagementRequestBenefitsBenefictResult.getTemporalLoading().addAll(_cbpitaUnderwrittingCaseManagement_caseManagementRequestBenefitsBenefictResultTemporalLoading);
        java.util.List<String> _cbpitaUnderwrittingCaseManagement_caseManagementRequestBenefitsBenefictResultExclusions = new java.util.ArrayList<String>();
        _cbpitaUnderwrittingCaseManagement_caseManagementRequestBenefitsBenefictResult.getExclusions().addAll(_cbpitaUnderwrittingCaseManagement_caseManagementRequestBenefitsBenefictResultExclusions);
        java.util.List<String> _cbpitaUnderwrittingCaseManagement_caseManagementRequestBenefitsBenefictResultMedicalReports = new java.util.ArrayList<String>();
        _cbpitaUnderwrittingCaseManagement_caseManagementRequestBenefitsBenefictResult.getMedicalReports().addAll(_cbpitaUnderwrittingCaseManagement_caseManagementRequestBenefitsBenefictResultMedicalReports);
        java.util.List<String> _cbpitaUnderwrittingCaseManagement_caseManagementRequestBenefitsBenefictResultMedicalTest = new java.util.ArrayList<String>();
        _cbpitaUnderwrittingCaseManagement_caseManagementRequestBenefitsBenefictResult.getMedicalTest().addAll(_cbpitaUnderwrittingCaseManagement_caseManagementRequestBenefitsBenefictResultMedicalTest);
        java.util.List<String> _cbpitaUnderwrittingCaseManagement_caseManagementRequestBenefitsBenefictResultNotes = new java.util.ArrayList<String>();
        _cbpitaUnderwrittingCaseManagement_caseManagementRequestBenefitsBenefictResult.getNotes().addAll(_cbpitaUnderwrittingCaseManagement_caseManagementRequestBenefitsBenefictResultNotes);
        _cbpitaUnderwrittingCaseManagement_caseManagementRequestBenefits.setBenefictResult(_cbpitaUnderwrittingCaseManagement_caseManagementRequestBenefitsBenefictResult);
        _cbpitaUnderwrittingCaseManagement_caseManagementRequest.setBenefits(_cbpitaUnderwrittingCaseManagement_caseManagementRequestBenefits);
        CbpitaUnderwrittingCaseManagementResponse _cbpitaUnderwrittingCaseManagement__return = port.cbpitaUnderwrittingCaseManagement(_cbpitaUnderwrittingCaseManagement_caseManagementRequest);
        System.out.println("cbpitaUnderwrittingCaseManagement.result=" + _cbpitaUnderwrittingCaseManagement__return);


        }

        System.exit(0);
    }

}
