
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.scortelemed.schemas.cbpita;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.1
 * Thu Mar 28 12:49:49 CET 2019
 * Generated source version: 2.1
 * 
 */

@WebService(name = "CbpitaUnderwrittingCaseManagementService",
                      serviceName = "CbpitaUnderwrittingCaseManagementServiceService",
                      portName = "CbpitaUnderwrittingCaseManagementServicePort",
                      targetNamespace = "http://www.scortelemed.com/schemas/cbpita", 
                      wsdlLocation = "http://localhost:8080/scorWebservice/services/cbpita/CbpitaUnderwrittingCaseManagement?wsdl",
                      endpointInterface = "com.scortelemed.schemas.cbpita.CbpitaUnderwrittingCaseManagementService")
                      
public class CbpitaUnderwrittingCaseManagementServiceImpl implements CbpitaUnderwrittingCaseManagementService {

    private static final Logger LOG = Logger.getLogger(CbpitaUnderwrittingCaseManagementServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see com.scortelemed.schemas.cbpita.CbpitaUnderwrittingCaseManagementService#cbpitaUnderwrittingCaseManagement(com.scortelemed.schemas.cbpita.CbpitaUnderwrittingCaseManagementRequest  caseManagementRequest )*
     */
    public CbpitaUnderwrittingCaseManagementResponse cbpitaUnderwrittingCaseManagement(CbpitaUnderwrittingCaseManagementRequest caseManagementRequest) {
        LOG.info("Executing operation cbpitaUnderwrittingCaseManagement");
        System.out.println(caseManagementRequest);
        try {
            CbpitaUnderwrittingCaseManagementResponse _return = new CbpitaUnderwrittingCaseManagementResponse();
            StatusType _returnStatus = StatusType.OK;
            _return.setStatus(_returnStatus);
            _return.setDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2019-03-28T12:49:49.821+01:00"));
            _return.setMessage("Message-1923795345");
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.scortelemed.schemas.cbpita.CbpitaUnderwrittingCaseManagementService#cbpitaUnderwrittingCasesResults(com.scortelemed.schemas.cbpita.CbpitaUnderwrittingCasesResultsRequest  caseManagementResultsRequest )*
     */
    public CbpitaUnderwrittingCasesResultsResponse cbpitaUnderwrittingCasesResults(CbpitaUnderwrittingCasesResultsRequest caseManagementResultsRequest) {
        LOG.info("Executing operation cbpitaUnderwrittingCasesResults");
        System.out.println(caseManagementResultsRequest);
        try {
            CbpitaUnderwrittingCasesResultsResponse _return = new CbpitaUnderwrittingCasesResultsResponse();
            _return.setDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2019-03-28T12:49:49.821+01:00"));
            StatusType _returnStatus = StatusType.OK;
            _return.setStatus(_returnStatus);
            _return.setMessage("Message-1862242978");
            _return.setCode(988222317);
            java.util.List<CbpitaUnderwrittingCasesResultsResponse.Expediente> _returnExpediente = new java.util.ArrayList<CbpitaUnderwrittingCasesResultsResponse.Expediente>();
            CbpitaUnderwrittingCasesResultsResponse.Expediente _returnExpedienteVal1 = new CbpitaUnderwrittingCasesResultsResponse.Expediente();
            _returnExpedienteVal1.setRequestDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2019-03-28T12:49:49.822+01:00"));
            _returnExpedienteVal1.setRequestNumber("RequestNumber-1160732970");
            RequestStateType _returnExpedienteVal1RequestState = RequestStateType.CLOSED;
            _returnExpedienteVal1.setRequestState(_returnExpedienteVal1RequestState);
            _returnExpedienteVal1.setCancellationReason("CancellationReason1585888680");
            _returnExpedienteVal1.setProductCode("ProductCode-1283893475");
            _returnExpedienteVal1.setPolicyNumber("PolicyNumber1152438040");
            _returnExpedienteVal1.setCertificateNumber("CertificateNumber-2078435312");
            _returnExpedienteVal1.setFiscalIdentificationNumber("FiscalIdentificationNumber1867860598");
            _returnExpedienteVal1.setMobilePhone("MobilePhone1240887689");
            _returnExpedienteVal1.setPhoneNumber1("PhoneNumber1-882543662");
            _returnExpedienteVal1.setPhoneNumber2("PhoneNumber22033869922");
            java.util.List<BenefitsType> _returnExpedienteVal1BenefitsList = new java.util.ArrayList<BenefitsType>();
            _returnExpedienteVal1.getBenefitsList().addAll(_returnExpedienteVal1BenefitsList);
            byte[] _returnExpedienteVal1Zip = new byte[] {};
            _returnExpedienteVal1.setZip(_returnExpedienteVal1Zip);
            _returnExpedienteVal1.setNotes("Notes-1317305269");
            _returnExpediente.add(_returnExpedienteVal1);
            _return.getExpediente().addAll(_returnExpediente);
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
