
package com.scortelemed.schemas.cbpita;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.1
 * Thu Mar 28 12:49:49 CET 2019
 * Generated source version: 2.1
 * 
 */

public final class CbpitaUnderwrittingCaseManagementService_CbpitaUnderwrittingCaseManagementServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://www.scortelemed.com/schemas/cbpita", "CbpitaUnderwrittingCaseManagementServiceService");

    private CbpitaUnderwrittingCaseManagementService_CbpitaUnderwrittingCaseManagementServicePort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = CbpitaUnderwrittingCaseManagementServiceService.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        CbpitaUnderwrittingCaseManagementServiceService ss = new CbpitaUnderwrittingCaseManagementServiceService(wsdlURL, SERVICE_NAME);
        CbpitaUnderwrittingCaseManagementService port = ss.getCbpitaUnderwrittingCaseManagementServicePort();  
        
        {
        System.out.println("Invoking cbpitaUnderwrittingCaseManagement...");
        CbpitaUnderwrittingCaseManagementRequest _cbpitaUnderwrittingCaseManagement_caseManagementRequest = new CbpitaUnderwrittingCaseManagementRequest();
        CbpitaUnderwrittingCaseManagementRequest.CandidateInformation _cbpitaUnderwrittingCaseManagement_caseManagementRequestCandidateInformation = new CbpitaUnderwrittingCaseManagementRequest.CandidateInformation();
        _cbpitaUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setProductCode("ProductCode1616329520");
        _cbpitaUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setRequestNumber("RequestNumber-1374266344");
        _cbpitaUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setPolicyNumber("PolicyNumber1728489448");
        _cbpitaUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setCertificateNumber("CertificateNumber-558094371");
        _cbpitaUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setRequestDate("RequestDate-1210098423");
        _cbpitaUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setPassword("Password-1410130055");
        _cbpitaUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setRequestState("RequestState-1221792159");
        _cbpitaUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setName("Name-1643976826");
        _cbpitaUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setSurname("Surname1760166885");
        _cbpitaUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setAddress("Address904273196");
        _cbpitaUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setPostalCode("PostalCode-1786019819");
        _cbpitaUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setCity("City-1028096726");
        _cbpitaUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setProvince("Province-1418774549");
        _cbpitaUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setCountry("Country1977030703");
        _cbpitaUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setPhoneNumber1("PhoneNumber11248900602");
        _cbpitaUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setPhoneNumber2("PhoneNumber2-429043437");
        _cbpitaUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setMobileNumber("MobileNumber-1142391130");
        _cbpitaUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setEmail("Email-1620883281");
        _cbpitaUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setBirthDate("BirthDate-2000338527");
        _cbpitaUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setActuarialAge("ActuarialAge-546655123");
        _cbpitaUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setBirthCity("BirthCity401335561");
        _cbpitaUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setFiscalIdentificationNumber("FiscalIdentificationNumber-1131399234");
        _cbpitaUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setAgency("Agency-376999712");
        _cbpitaUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setAgent("Agent-1507588581");
        _cbpitaUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setAgentPhone("AgentPhone-1579211341");
        _cbpitaUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setAgentEmail("AgentEmail337912386");
        GenderType _cbpitaUnderwrittingCaseManagement_caseManagementRequestCandidateInformationGender = GenderType.M;
        _cbpitaUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setGender(_cbpitaUnderwrittingCaseManagement_caseManagementRequestCandidateInformationGender);
        CivilStateType _cbpitaUnderwrittingCaseManagement_caseManagementRequestCandidateInformationCivilState = CivilStateType.O;
        _cbpitaUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setCivilState(_cbpitaUnderwrittingCaseManagement_caseManagementRequestCandidateInformationCivilState);
        _cbpitaUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setCustomerType("CustomerType-1430229131");
        ContactTimeType _cbpitaUnderwrittingCaseManagement_caseManagementRequestCandidateInformationContactTime = ContactTimeType.M;
        _cbpitaUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setContactTime(_cbpitaUnderwrittingCaseManagement_caseManagementRequestCandidateInformationContactTime);
        _cbpitaUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setComments("Comments347296857");
        _cbpitaUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setEUWReferenceCode("EUWReferenceCode-2120600005");
        _cbpitaUnderwrittingCaseManagement_caseManagementRequest.setCandidateInformation(_cbpitaUnderwrittingCaseManagement_caseManagementRequestCandidateInformation);
        java.util.List<CbpitaUnderwrittingCaseManagementRequest.PreviousQuestions> _cbpitaUnderwrittingCaseManagement_caseManagementRequestPreviousQuestions = new java.util.ArrayList<CbpitaUnderwrittingCaseManagementRequest.PreviousQuestions>();
        CbpitaUnderwrittingCaseManagementRequest.PreviousQuestions _cbpitaUnderwrittingCaseManagement_caseManagementRequestPreviousQuestionsVal1 = new CbpitaUnderwrittingCaseManagementRequest.PreviousQuestions();
        QuestionDataType _cbpitaUnderwrittingCaseManagement_caseManagementRequestPreviousQuestionsVal1DataType = QuestionDataType.BOOLEAN;
        _cbpitaUnderwrittingCaseManagement_caseManagementRequestPreviousQuestionsVal1.setDataType(_cbpitaUnderwrittingCaseManagement_caseManagementRequestPreviousQuestionsVal1DataType);
        _cbpitaUnderwrittingCaseManagement_caseManagementRequestPreviousQuestionsVal1.setAnswerCode("AnswerCode-836811526");
        _cbpitaUnderwrittingCaseManagement_caseManagementRequestPreviousQuestionsVal1.setQuestion("Question1579246028");
        _cbpitaUnderwrittingCaseManagement_caseManagementRequestPreviousQuestionsVal1.setAnswer("Answer-2123940881");
        _cbpitaUnderwrittingCaseManagement_caseManagementRequestPreviousQuestions.add(_cbpitaUnderwrittingCaseManagement_caseManagementRequestPreviousQuestionsVal1);
        _cbpitaUnderwrittingCaseManagement_caseManagementRequest.getPreviousQuestions().addAll(_cbpitaUnderwrittingCaseManagement_caseManagementRequestPreviousQuestions);
        java.util.List<CbpitaUnderwrittingCaseManagementRequest.Services> _cbpitaUnderwrittingCaseManagement_caseManagementRequestServices = new java.util.ArrayList<CbpitaUnderwrittingCaseManagementRequest.Services>();
        CbpitaUnderwrittingCaseManagementRequest.Services _cbpitaUnderwrittingCaseManagement_caseManagementRequestServicesVal1 = new CbpitaUnderwrittingCaseManagementRequest.Services();
        _cbpitaUnderwrittingCaseManagement_caseManagementRequestServicesVal1.setServiceType("ServiceType1995605826");
        _cbpitaUnderwrittingCaseManagement_caseManagementRequestServicesVal1.setServiceCode("ServiceCode1267083846");
        _cbpitaUnderwrittingCaseManagement_caseManagementRequestServicesVal1.setServiceDescription("ServiceDescription-1265210289");
        _cbpitaUnderwrittingCaseManagement_caseManagementRequestServices.add(_cbpitaUnderwrittingCaseManagement_caseManagementRequestServicesVal1);
        _cbpitaUnderwrittingCaseManagement_caseManagementRequest.getServices().addAll(_cbpitaUnderwrittingCaseManagement_caseManagementRequestServices);
        BenefitsType _cbpitaUnderwrittingCaseManagement_caseManagementRequestBenefits = new BenefitsType();
        BenefictNameType _cbpitaUnderwrittingCaseManagement_caseManagementRequestBenefitsBenefictName = BenefictNameType.DISABILITY_90;
        _cbpitaUnderwrittingCaseManagement_caseManagementRequestBenefits.setBenefictName(_cbpitaUnderwrittingCaseManagement_caseManagementRequestBenefitsBenefictName);
        _cbpitaUnderwrittingCaseManagement_caseManagementRequestBenefits.setBenefictCode("BenefictCode1778959875");
        _cbpitaUnderwrittingCaseManagement_caseManagementRequestBenefits.setBenefictCapital("BenefictCapital-1446273568");
        BenefictResultType _cbpitaUnderwrittingCaseManagement_caseManagementRequestBenefitsBenefictResult = new BenefictResultType();
        _cbpitaUnderwrittingCaseManagement_caseManagementRequestBenefitsBenefictResult.setDescResult("DescResult1302854751");
        _cbpitaUnderwrittingCaseManagement_caseManagementRequestBenefitsBenefictResult.setResultCode("ResultCode484934828");
        _cbpitaUnderwrittingCaseManagement_caseManagementRequestBenefitsBenefictResult.setPremiumLoading("PremiumLoading176725516");
        _cbpitaUnderwrittingCaseManagement_caseManagementRequestBenefitsBenefictResult.setCapitalLoading("CapitalLoading1951588848");
        _cbpitaUnderwrittingCaseManagement_caseManagementRequestBenefitsBenefictResult.setDescPremiumLoading("DescPremiumLoading-1909371951");
        _cbpitaUnderwrittingCaseManagement_caseManagementRequestBenefitsBenefictResult.setDescCapitalLoading("DescCapitalLoading935499732");
        java.util.List<String> _cbpitaUnderwrittingCaseManagement_caseManagementRequestBenefitsBenefictResultTemporalLoading = new java.util.ArrayList<String>();
        _cbpitaUnderwrittingCaseManagement_caseManagementRequestBenefitsBenefictResult.getTemporalLoading().addAll(_cbpitaUnderwrittingCaseManagement_caseManagementRequestBenefitsBenefictResultTemporalLoading);
        java.util.List<String> _cbpitaUnderwrittingCaseManagement_caseManagementRequestBenefitsBenefictResultExclusions = new java.util.ArrayList<String>();
        _cbpitaUnderwrittingCaseManagement_caseManagementRequestBenefitsBenefictResult.getExclusions().addAll(_cbpitaUnderwrittingCaseManagement_caseManagementRequestBenefitsBenefictResultExclusions);
        java.util.List<String> _cbpitaUnderwrittingCaseManagement_caseManagementRequestBenefitsBenefictResultMedicalReports = new java.util.ArrayList<String>();
        _cbpitaUnderwrittingCaseManagement_caseManagementRequestBenefitsBenefictResult.getMedicalReports().addAll(_cbpitaUnderwrittingCaseManagement_caseManagementRequestBenefitsBenefictResultMedicalReports);
        java.util.List<String> _cbpitaUnderwrittingCaseManagement_caseManagementRequestBenefitsBenefictResultMedicalTest = new java.util.ArrayList<String>();
        _cbpitaUnderwrittingCaseManagement_caseManagementRequestBenefitsBenefictResult.getMedicalTest().addAll(_cbpitaUnderwrittingCaseManagement_caseManagementRequestBenefitsBenefictResultMedicalTest);
        java.util.List<String> _cbpitaUnderwrittingCaseManagement_caseManagementRequestBenefitsBenefictResultNotes = new java.util.ArrayList<String>();
        _cbpitaUnderwrittingCaseManagement_caseManagementRequestBenefitsBenefictResult.getNotes().addAll(_cbpitaUnderwrittingCaseManagement_caseManagementRequestBenefitsBenefictResultNotes);
        _cbpitaUnderwrittingCaseManagement_caseManagementRequestBenefits.setBenefictResult(_cbpitaUnderwrittingCaseManagement_caseManagementRequestBenefitsBenefictResult);
        _cbpitaUnderwrittingCaseManagement_caseManagementRequest.setBenefits(_cbpitaUnderwrittingCaseManagement_caseManagementRequestBenefits);
        CbpitaUnderwrittingCaseManagementResponse _cbpitaUnderwrittingCaseManagement__return = port.cbpitaUnderwrittingCaseManagement(_cbpitaUnderwrittingCaseManagement_caseManagementRequest);
        System.out.println("cbpitaUnderwrittingCaseManagement.result=" + _cbpitaUnderwrittingCaseManagement__return);


        }
        {
        System.out.println("Invoking cbpitaUnderwrittingCasesResults...");
        CbpitaUnderwrittingCasesResultsRequest _cbpitaUnderwrittingCasesResults_caseManagementResultsRequest = new CbpitaUnderwrittingCasesResultsRequest();
        _cbpitaUnderwrittingCasesResults_caseManagementResultsRequest.setDateStart(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2019-03-28T12:49:49.809+01:00"));
        _cbpitaUnderwrittingCasesResults_caseManagementResultsRequest.setDateEnd(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2019-03-28T12:49:49.812+01:00"));
        CbpitaUnderwrittingCasesResultsResponse _cbpitaUnderwrittingCasesResults__return = port.cbpitaUnderwrittingCasesResults(_cbpitaUnderwrittingCasesResults_caseManagementResultsRequest);
        System.out.println("cbpitaUnderwrittingCasesResults.result=" + _cbpitaUnderwrittingCasesResults__return);


        }

        System.exit(0);
    }

}
