
package com.scortelemed.schemas.cbpita;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.1
 * Thu Mar 28 12:49:49 CET 2019
 * Generated source version: 2.1
 *
 */

@WebService(targetNamespace = "http://www.scortelemed.com/schemas/cbpita", name = "CbpitaUnderwrittingCaseManagementService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = ParameterStyle.BARE)

public interface CbpitaUnderwrittingCaseManagementService {

    @SOAPBinding(parameterStyle = ParameterStyle.BARE)
    @WebResult(name = "CaseManagementResponse", targetNamespace = "http://www.scortelemed.com/schemas/cbpita", partName = "CaseManagementResponse")
    @WebMethod
    public CbpitaUnderwrittingCaseManagementResponse cbpitaUnderwrittingCaseManagement(
            @WebParam(partName = "CaseManagementRequest", name = "CaseManagementRequest", targetNamespace = "http://www.scortelemed.com/schemas/cbpita")
                    CbpitaUnderwrittingCaseManagementRequest caseManagementRequest
    );

    @SOAPBinding(parameterStyle = ParameterStyle.BARE)
    @WebResult(name = "CaseManagementResultsResponse", targetNamespace = "http://www.scortelemed.com/schemas/cbpita", partName = "CaseManagementResultsResponse")
    @WebMethod
    public CbpitaUnderwrittingCasesResultsResponse cbpitaUnderwrittingCasesResults(
            @WebParam(partName = "CaseManagementResultsRequest", name = "CaseManagementResultsRequest", targetNamespace = "http://www.scortelemed.com/schemas/cbpita")
                    CbpitaUnderwrittingCasesResultsRequest caseManagementResultsRequest
    );
}
