
package com.scortelemed.schemas.netinsurance;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.1
 * Mon Sep 17 16:10:48 CEST 2018
 * Generated source version: 2.1
 * 
 */

@WebService(targetNamespace = "http://www.scortelemed.com/schemas/netinsurance", name = "NetinsuranceUnderwrittingCaseManagementService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)

public interface NetinsuranceUnderwrittingCaseManagementService {

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "NetinsuranteGetDossierResponse", targetNamespace = "http://www.scortelemed.com/schemas/netinsurance", partName = "netinsuranteGetDossierResponse")
    @WebMethod
    public NetinsuranteGetDossierResponse netinsuranteGetDossier(
        @WebParam(partName = "netinsuranteGetDossierRequest", name = "NetinsuranteGetDossierRequest", targetNamespace = "http://www.scortelemed.com/schemas/netinsurance")
        NetinsuranteGetDossierRequest netinsuranteGetDossierRequest
    );

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "CaseManagementResponse", targetNamespace = "http://www.scortelemed.com/schemas/netinsurance", partName = "CaseManagementResponse")
    @WebMethod
    public NetinsuranteUnderwrittingCaseManagementResponse netInsuranteUnderwrittingCaseManagement(
        @WebParam(partName = "CaseManagementRequest", name = "CaseManagementRequest", targetNamespace = "http://www.scortelemed.com/schemas/netinsurance")
        NetinsuranteUnderwrittingCaseManagementRequest caseManagementRequest
    );

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "CaseManagementResultsResponse", targetNamespace = "http://www.scortelemed.com/schemas/netinsurance", partName = "CaseManagementResultsResponse")
    @WebMethod
    public NetinsuranteUnderwrittingCasesResultsResponse netInsuranteUnderwrittingCasesResults(
        @WebParam(partName = "CaseManagementResultsRequest", name = "CaseManagementResultsRequest", targetNamespace = "http://www.scortelemed.com/schemas/netinsurance")
        NetinsuranteUnderwrittingCasesResultsRequest caseManagementResultsRequest
    );
}
