
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.scortelemed.schemas.netinsurance;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.1
 * Mon Sep 17 16:10:48 CEST 2018
 * Generated source version: 2.1
 * 
 */

@javax.jws.WebService(name = "NetinsuranceUnderwrittingCaseManagementService",
                      serviceName = "NetinsuranceUnderwrittingCaseManagementServiceService",
                      portName = "NetinsuranceUnderwrittingCaseManagementServicePort",
                      targetNamespace = "http://www.scortelemed.com/schemas/netinsurance", 
                      wsdlLocation = "http://localhost:8080/scorWebservice/services/netinsurance/NetinsuranceUnderwrittingCaseManagement?wsdl",
                      endpointInterface = "com.scortelemed.schemas.netinsurance.NetinsuranceUnderwrittingCaseManagementService")
                      
public class NetinsuranceUnderwrittingCaseManagementServiceImpl implements NetinsuranceUnderwrittingCaseManagementService {

    private static final Logger LOG = Logger.getLogger(NetinsuranceUnderwrittingCaseManagementServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see com.scortelemed.schemas.netinsurance.NetinsuranceUnderwrittingCaseManagementService#netinsuranteGetDossier(com.scortelemed.schemas.netinsurance.NetinsuranteGetDossierRequest  netinsuranteGetDossierRequest )*
     */
    public com.scortelemed.schemas.netinsurance.NetinsuranteGetDossierResponse netinsuranteGetDossier(NetinsuranteGetDossierRequest netinsuranteGetDossierRequest) { 
        LOG.info("Executing operation netinsuranteGetDossier");
        System.out.println(netinsuranteGetDossierRequest);
        try {
            com.scortelemed.schemas.netinsurance.NetinsuranteGetDossierResponse _return = new com.scortelemed.schemas.netinsurance.NetinsuranteGetDossierResponse();
            _return.setDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-09-17T16:10:48.179+02:00"));
            com.scortelemed.schemas.netinsurance.StatusType _returnStatus = com.scortelemed.schemas.netinsurance.StatusType.OK;
            _return.setStatus(_returnStatus);
            _return.setNotes("Notes1941772208");
            java.util.List<com.scortelemed.schemas.netinsurance.NetinsuranteGetDossierResponse.ExpedienteConsulta> _returnExpedienteConsulta = new java.util.ArrayList<com.scortelemed.schemas.netinsurance.NetinsuranteGetDossierResponse.ExpedienteConsulta>();
            com.scortelemed.schemas.netinsurance.NetinsuranteGetDossierResponse.ExpedienteConsulta _returnExpedienteConsultaVal1 = new com.scortelemed.schemas.netinsurance.NetinsuranteGetDossierResponse.ExpedienteConsulta();
            _returnExpedienteConsultaVal1.setRequestDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-09-17T16:10:48.179+02:00"));
            _returnExpedienteConsultaVal1.setRequestNumber("RequestNumber1892293497");
            _returnExpedienteConsultaVal1.setRequestState("RequestState-1252584032");
            _returnExpedienteConsultaVal1.setProductCode("ProductCode-1141361285");
            _returnExpedienteConsultaVal1.setPolicyNumber("PolicyNumber-236170979");
            _returnExpedienteConsultaVal1.setCertificateNumber("CertificateNumber160861439");
            _returnExpedienteConsultaVal1.setFiscalIdentificationNumber("FiscalIdentificationNumber1401047417");
            _returnExpedienteConsultaVal1.setMobilePhone("MobilePhone-1985090309");
            _returnExpedienteConsultaVal1.setPhoneNumber1("PhoneNumber1-2144117986");
            _returnExpedienteConsultaVal1.setPhoneNumber2("PhoneNumber21656776496");
            java.util.List<com.scortelemed.schemas.netinsurance.BenefitsType> _returnExpedienteConsultaVal1BenefitsList = new java.util.ArrayList<com.scortelemed.schemas.netinsurance.BenefitsType>();
            _returnExpedienteConsultaVal1.getBenefitsList().addAll(_returnExpedienteConsultaVal1BenefitsList);
            byte[] _returnExpedienteConsultaVal1Zip = new byte[] {};
            _returnExpedienteConsultaVal1.setZip(_returnExpedienteConsultaVal1Zip);
            _returnExpedienteConsultaVal1.setNotes("Notes1034220658");
            _returnExpedienteConsulta.add(_returnExpedienteConsultaVal1);
            _return.getExpedienteConsulta().addAll(_returnExpedienteConsulta);
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.scortelemed.schemas.netinsurance.NetinsuranceUnderwrittingCaseManagementService#netInsuranteUnderwrittingCaseManagement(com.scortelemed.schemas.netinsurance.NetinsuranteUnderwrittingCaseManagementRequest  caseManagementRequest )*
     */
    public com.scortelemed.schemas.netinsurance.NetinsuranteUnderwrittingCaseManagementResponse netInsuranteUnderwrittingCaseManagement(NetinsuranteUnderwrittingCaseManagementRequest caseManagementRequest) { 
        LOG.info("Executing operation netInsuranteUnderwrittingCaseManagement");
        System.out.println(caseManagementRequest);
        try {
            com.scortelemed.schemas.netinsurance.NetinsuranteUnderwrittingCaseManagementResponse _return = new com.scortelemed.schemas.netinsurance.NetinsuranteUnderwrittingCaseManagementResponse();
            com.scortelemed.schemas.netinsurance.StatusType _returnStatus = com.scortelemed.schemas.netinsurance.StatusType.OK;
            _return.setStatus(_returnStatus);
            _return.setDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-09-17T16:10:48.179+02:00"));
            _return.setMessage("Message-839887588");
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.scortelemed.schemas.netinsurance.NetinsuranceUnderwrittingCaseManagementService#netInsuranteUnderwrittingCasesResults(com.scortelemed.schemas.netinsurance.NetinsuranteUnderwrittingCasesResultsRequest  caseManagementResultsRequest )*
     */
    public com.scortelemed.schemas.netinsurance.NetinsuranteUnderwrittingCasesResultsResponse netInsuranteUnderwrittingCasesResults(NetinsuranteUnderwrittingCasesResultsRequest caseManagementResultsRequest) { 
        LOG.info("Executing operation netInsuranteUnderwrittingCasesResults");
        System.out.println(caseManagementResultsRequest);
        try {
            com.scortelemed.schemas.netinsurance.NetinsuranteUnderwrittingCasesResultsResponse _return = new com.scortelemed.schemas.netinsurance.NetinsuranteUnderwrittingCasesResultsResponse();
            _return.setDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-09-17T16:10:48.179+02:00"));
            com.scortelemed.schemas.netinsurance.StatusType _returnStatus = com.scortelemed.schemas.netinsurance.StatusType.OK;
            _return.setStatus(_returnStatus);
            _return.setNotes("Notes1263371715");
            java.util.List<com.scortelemed.schemas.netinsurance.NetinsuranteUnderwrittingCasesResultsResponse.Expediente> _returnExpediente = new java.util.ArrayList<com.scortelemed.schemas.netinsurance.NetinsuranteUnderwrittingCasesResultsResponse.Expediente>();
            com.scortelemed.schemas.netinsurance.NetinsuranteUnderwrittingCasesResultsResponse.Expediente _returnExpedienteVal1 = new com.scortelemed.schemas.netinsurance.NetinsuranteUnderwrittingCasesResultsResponse.Expediente();
            _returnExpedienteVal1.setRequestDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-09-17T16:10:48.179+02:00"));
            _returnExpedienteVal1.setRequestNumber("RequestNumber621812359");
            com.scortelemed.schemas.netinsurance.RequestStateType _returnExpedienteVal1RequestState = com.scortelemed.schemas.netinsurance.RequestStateType.CLOSED;
            _returnExpedienteVal1.setRequestState(_returnExpedienteVal1RequestState);
            _returnExpedienteVal1.setProductCode("ProductCode1690772510");
            _returnExpedienteVal1.setPolicyNumber("PolicyNumber1362632244");
            _returnExpedienteVal1.setCertificateNumber("CertificateNumber432025139");
            _returnExpedienteVal1.setFiscalIdentificationNumber("FiscalIdentificationNumber934724363");
            _returnExpedienteVal1.setMobilePhone("MobilePhone395243958");
            _returnExpedienteVal1.setPhoneNumber1("PhoneNumber1703721221");
            _returnExpedienteVal1.setPhoneNumber2("PhoneNumber21241071255");
            java.util.List<com.scortelemed.schemas.netinsurance.BenefitsType> _returnExpedienteVal1BenefitsList = new java.util.ArrayList<com.scortelemed.schemas.netinsurance.BenefitsType>();
            _returnExpedienteVal1.getBenefitsList().addAll(_returnExpedienteVal1BenefitsList);
            byte[] _returnExpedienteVal1Zip = new byte[] {};
            _returnExpedienteVal1.setZip(_returnExpedienteVal1Zip);
            _returnExpedienteVal1.setNotes("Notes-1925563339");
            _returnExpediente.add(_returnExpedienteVal1);
            _return.getExpediente().addAll(_returnExpediente);
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
