
package com.scortelemed.schemas.netinsurance;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 2.1
 * Mon Sep 17 16:10:48 CEST 2018
 * Generated source version: 2.1
 * 
 */

@WebServiceClient(name = "NetinsuranceUnderwrittingCaseManagementServiceService", targetNamespace = "http://www.scortelemed.com/schemas/netinsurance", wsdlLocation = "http://localhost:8080/scorWebservice/services/netinsurance/NetinsuranceUnderwrittingCaseManagement?wsdl")
public class NetinsuranceUnderwrittingCaseManagementServiceService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://www.scortelemed.com/schemas/netinsurance", "NetinsuranceUnderwrittingCaseManagementServiceService");
    public final static QName NetinsuranceUnderwrittingCaseManagementServicePort = new QName("http://www.scortelemed.com/schemas/netinsurance", "NetinsuranceUnderwrittingCaseManagementServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/scorWebservice/services/netinsurance/NetinsuranceUnderwrittingCaseManagement?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://localhost:8080/scorWebservice/services/netinsurance/NetinsuranceUnderwrittingCaseManagement?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public NetinsuranceUnderwrittingCaseManagementServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public NetinsuranceUnderwrittingCaseManagementServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NetinsuranceUnderwrittingCaseManagementServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns NetinsuranceUnderwrittingCaseManagementService
     */
    @WebEndpoint(name = "NetinsuranceUnderwrittingCaseManagementServicePort")
    public NetinsuranceUnderwrittingCaseManagementService getNetinsuranceUnderwrittingCaseManagementServicePort() {
        return super.getPort(NetinsuranceUnderwrittingCaseManagementServicePort, NetinsuranceUnderwrittingCaseManagementService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns NetinsuranceUnderwrittingCaseManagementService
     */
    @WebEndpoint(name = "NetinsuranceUnderwrittingCaseManagementServicePort")
    public NetinsuranceUnderwrittingCaseManagementService getNetinsuranceUnderwrittingCaseManagementServicePort(WebServiceFeature... features) {
        return super.getPort(NetinsuranceUnderwrittingCaseManagementServicePort, NetinsuranceUnderwrittingCaseManagementService.class, features);
    }

}
