
package com.scortelemed.schemas.netinsurance;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.1
 * Mon Sep 17 16:10:48 CEST 2018
 * Generated source version: 2.1
 * 
 */

public final class NetinsuranceUnderwrittingCaseManagementService_NetinsuranceUnderwrittingCaseManagementServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://www.scortelemed.com/schemas/netinsurance", "NetinsuranceUnderwrittingCaseManagementServiceService");

    private NetinsuranceUnderwrittingCaseManagementService_NetinsuranceUnderwrittingCaseManagementServicePort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = NetinsuranceUnderwrittingCaseManagementServiceService.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        NetinsuranceUnderwrittingCaseManagementServiceService ss = new NetinsuranceUnderwrittingCaseManagementServiceService(wsdlURL, SERVICE_NAME);
        NetinsuranceUnderwrittingCaseManagementService port = ss.getNetinsuranceUnderwrittingCaseManagementServicePort();  
        
        {
        System.out.println("Invoking netinsuranteGetDossier...");
        com.scortelemed.schemas.netinsurance.NetinsuranteGetDossierRequest _netinsuranteGetDossier_netinsuranteGetDossierRequest = new com.scortelemed.schemas.netinsurance.NetinsuranteGetDossierRequest();
        _netinsuranteGetDossier_netinsuranteGetDossierRequest.setRequestNumber("RequestNumber_00201586812395");
        com.scortelemed.schemas.netinsurance.NetinsuranteGetDossierResponse _netinsuranteGetDossier__return = port.netinsuranteGetDossier(_netinsuranteGetDossier_netinsuranteGetDossierRequest);
        System.out.println("netinsuranteGetDossier.result=" + _netinsuranteGetDossier__return);


        }
        {
        System.out.println("Invoking netInsuranteUnderwrittingCaseManagement...");
        com.scortelemed.schemas.netinsurance.NetinsuranteUnderwrittingCaseManagementRequest _netInsuranteUnderwrittingCaseManagement_caseManagementRequest = new com.scortelemed.schemas.netinsurance.NetinsuranteUnderwrittingCaseManagementRequest();
        com.scortelemed.schemas.netinsurance.NetinsuranteUnderwrittingCaseManagementRequest.CandidateInformation _netInsuranteUnderwrittingCaseManagement_caseManagementRequestCandidateInformation = new com.scortelemed.schemas.netinsurance.NetinsuranteUnderwrittingCaseManagementRequest.CandidateInformation();
        _netInsuranteUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setProductCode("ProductCode1928542907");
        _netInsuranteUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setRequestNumber("RequestNumber55041571");
        _netInsuranteUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setPolicyNumber("PolicyNumber-784782524");
        _netInsuranteUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setCertificateNumber("CertificateNumber-1601612582");
        _netInsuranteUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setRequestDate("RequestDate-322068666");
        _netInsuranteUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setPassword("Password1305024458");
        _netInsuranteUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setRequestState("RequestState-1120317337");
        _netInsuranteUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setName("Name1033948122");
        _netInsuranteUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setSurname("Surname-896105252");
        _netInsuranteUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setAddress("Address1456605917");
        _netInsuranteUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setPostalCode("PostalCode1230982484");
        _netInsuranteUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setCity("City307009792");
        _netInsuranteUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setProvince("Province1723600706");
        _netInsuranteUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setCountry("Country1345104855");
        _netInsuranteUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setPhoneNumber1("PhoneNumber1-2092104892");
        _netInsuranteUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setPhoneNumber2("PhoneNumber21451778849");
        _netInsuranteUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setMobileNumber("MobileNumber-1647621952");
        _netInsuranteUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setEmail("Email1787442111");
        _netInsuranteUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setBirthDate("BirthDate1573513969");
        _netInsuranteUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setActuarialAge("ActuarialAge1475362676");
        _netInsuranteUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setBirthCity("BirthCity-622886671");
        _netInsuranteUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setFiscalIdentificationNumber("FiscalIdentificationNumber1938880613");
        _netInsuranteUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setAgency("Agency-1012579956");
        _netInsuranteUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setAgent("Agent-1050604171");
        _netInsuranteUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setAgentPhone("AgentPhone396903643");
        _netInsuranteUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setAgentEmail("AgentEmail1069090027");
        com.scortelemed.schemas.netinsurance.GenderType _netInsuranteUnderwrittingCaseManagement_caseManagementRequestCandidateInformationGender = com.scortelemed.schemas.netinsurance.GenderType.M;
        _netInsuranteUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setGender(_netInsuranteUnderwrittingCaseManagement_caseManagementRequestCandidateInformationGender);
        com.scortelemed.schemas.netinsurance.CivilStateType _netInsuranteUnderwrittingCaseManagement_caseManagementRequestCandidateInformationCivilState = com.scortelemed.schemas.netinsurance.CivilStateType.C;
        _netInsuranteUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setCivilState(_netInsuranteUnderwrittingCaseManagement_caseManagementRequestCandidateInformationCivilState);
        _netInsuranteUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setCustomerType("CustomerType55460926");
        com.scortelemed.schemas.netinsurance.ContactTimeType _netInsuranteUnderwrittingCaseManagement_caseManagementRequestCandidateInformationContactTime = com.scortelemed.schemas.netinsurance.ContactTimeType.M;
        _netInsuranteUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setContactTime(_netInsuranteUnderwrittingCaseManagement_caseManagementRequestCandidateInformationContactTime);
        _netInsuranteUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setComments("Comments1432618788");
        _netInsuranteUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setEUWReferenceCode("EUWReferenceCode964031212");
        _netInsuranteUnderwrittingCaseManagement_caseManagementRequest.setCandidateInformation(_netInsuranteUnderwrittingCaseManagement_caseManagementRequestCandidateInformation);
        java.util.List<com.scortelemed.schemas.netinsurance.NetinsuranteUnderwrittingCaseManagementRequest.PreviousQuestions> _netInsuranteUnderwrittingCaseManagement_caseManagementRequestPreviousQuestions = new java.util.ArrayList<com.scortelemed.schemas.netinsurance.NetinsuranteUnderwrittingCaseManagementRequest.PreviousQuestions>();
        com.scortelemed.schemas.netinsurance.NetinsuranteUnderwrittingCaseManagementRequest.PreviousQuestions _netInsuranteUnderwrittingCaseManagement_caseManagementRequestPreviousQuestionsVal1 = new com.scortelemed.schemas.netinsurance.NetinsuranteUnderwrittingCaseManagementRequest.PreviousQuestions();
        com.scortelemed.schemas.netinsurance.QuestionDataType _netInsuranteUnderwrittingCaseManagement_caseManagementRequestPreviousQuestionsVal1DataType = com.scortelemed.schemas.netinsurance.QuestionDataType.DATE;
        _netInsuranteUnderwrittingCaseManagement_caseManagementRequestPreviousQuestionsVal1.setDataType(_netInsuranteUnderwrittingCaseManagement_caseManagementRequestPreviousQuestionsVal1DataType);
        _netInsuranteUnderwrittingCaseManagement_caseManagementRequestPreviousQuestionsVal1.setAnswerCode("AnswerCode-1756438138");
        _netInsuranteUnderwrittingCaseManagement_caseManagementRequestPreviousQuestionsVal1.setQuestion("Question1333088492");
        _netInsuranteUnderwrittingCaseManagement_caseManagementRequestPreviousQuestionsVal1.setAnswer("Answer-887587008");
        _netInsuranteUnderwrittingCaseManagement_caseManagementRequestPreviousQuestions.add(_netInsuranteUnderwrittingCaseManagement_caseManagementRequestPreviousQuestionsVal1);
        _netInsuranteUnderwrittingCaseManagement_caseManagementRequest.getPreviousQuestions().addAll(_netInsuranteUnderwrittingCaseManagement_caseManagementRequestPreviousQuestions);
        java.util.List<com.scortelemed.schemas.netinsurance.NetinsuranteUnderwrittingCaseManagementRequest.Services> _netInsuranteUnderwrittingCaseManagement_caseManagementRequestServices = new java.util.ArrayList<com.scortelemed.schemas.netinsurance.NetinsuranteUnderwrittingCaseManagementRequest.Services>();
        com.scortelemed.schemas.netinsurance.NetinsuranteUnderwrittingCaseManagementRequest.Services _netInsuranteUnderwrittingCaseManagement_caseManagementRequestServicesVal1 = new com.scortelemed.schemas.netinsurance.NetinsuranteUnderwrittingCaseManagementRequest.Services();
        _netInsuranteUnderwrittingCaseManagement_caseManagementRequestServicesVal1.setServiceType("ServiceType-1644552471");
        _netInsuranteUnderwrittingCaseManagement_caseManagementRequestServicesVal1.setServiceCode("ServiceCode170803859");
        _netInsuranteUnderwrittingCaseManagement_caseManagementRequestServicesVal1.setServiceDescription("ServiceDescription1992879075");
        _netInsuranteUnderwrittingCaseManagement_caseManagementRequestServices.add(_netInsuranteUnderwrittingCaseManagement_caseManagementRequestServicesVal1);
        _netInsuranteUnderwrittingCaseManagement_caseManagementRequest.getServices().addAll(_netInsuranteUnderwrittingCaseManagement_caseManagementRequestServices);
        com.scortelemed.schemas.netinsurance.BenefitsType _netInsuranteUnderwrittingCaseManagement_caseManagementRequestBenefits = new com.scortelemed.schemas.netinsurance.BenefitsType();
        com.scortelemed.schemas.netinsurance.BenefictNameType _netInsuranteUnderwrittingCaseManagement_caseManagementRequestBenefitsBenefictName = com.scortelemed.schemas.netinsurance.BenefictNameType.CRITICAL_ILLNESS;
        _netInsuranteUnderwrittingCaseManagement_caseManagementRequestBenefits.setBenefictName(_netInsuranteUnderwrittingCaseManagement_caseManagementRequestBenefitsBenefictName);
        _netInsuranteUnderwrittingCaseManagement_caseManagementRequestBenefits.setBenefictCode("BenefictCode-1708891941");
        _netInsuranteUnderwrittingCaseManagement_caseManagementRequestBenefits.setBenefictCapital("BenefictCapital18497592");
        com.scortelemed.schemas.netinsurance.BenefictResultType _netInsuranteUnderwrittingCaseManagement_caseManagementRequestBenefitsBenefictResult = new com.scortelemed.schemas.netinsurance.BenefictResultType();
        _netInsuranteUnderwrittingCaseManagement_caseManagementRequestBenefitsBenefictResult.setDescResult("DescResult-347397221");
        _netInsuranteUnderwrittingCaseManagement_caseManagementRequestBenefitsBenefictResult.setResultCode("ResultCode1035893937");
        _netInsuranteUnderwrittingCaseManagement_caseManagementRequestBenefitsBenefictResult.setPremiumLoading("PremiumLoading-370035962");
        _netInsuranteUnderwrittingCaseManagement_caseManagementRequestBenefitsBenefictResult.setCapitalLoading("CapitalLoading-1139130203");
        _netInsuranteUnderwrittingCaseManagement_caseManagementRequestBenefitsBenefictResult.setDescPremiumLoading("DescPremiumLoading721759766");
        _netInsuranteUnderwrittingCaseManagement_caseManagementRequestBenefitsBenefictResult.setDescCapitalLoading("DescCapitalLoading-1165778276");
        java.util.List<java.lang.String> _netInsuranteUnderwrittingCaseManagement_caseManagementRequestBenefitsBenefictResultTemporalLoading = new java.util.ArrayList<java.lang.String>();
        _netInsuranteUnderwrittingCaseManagement_caseManagementRequestBenefitsBenefictResult.getTemporalLoading().addAll(_netInsuranteUnderwrittingCaseManagement_caseManagementRequestBenefitsBenefictResultTemporalLoading);
        java.util.List<java.lang.String> _netInsuranteUnderwrittingCaseManagement_caseManagementRequestBenefitsBenefictResultExclusions = new java.util.ArrayList<java.lang.String>();
        _netInsuranteUnderwrittingCaseManagement_caseManagementRequestBenefitsBenefictResult.getExclusions().addAll(_netInsuranteUnderwrittingCaseManagement_caseManagementRequestBenefitsBenefictResultExclusions);
        java.util.List<java.lang.String> _netInsuranteUnderwrittingCaseManagement_caseManagementRequestBenefitsBenefictResultMedicalReports = new java.util.ArrayList<java.lang.String>();
        _netInsuranteUnderwrittingCaseManagement_caseManagementRequestBenefitsBenefictResult.getMedicalReports().addAll(_netInsuranteUnderwrittingCaseManagement_caseManagementRequestBenefitsBenefictResultMedicalReports);
        java.util.List<java.lang.String> _netInsuranteUnderwrittingCaseManagement_caseManagementRequestBenefitsBenefictResultMedicalTest = new java.util.ArrayList<java.lang.String>();
        _netInsuranteUnderwrittingCaseManagement_caseManagementRequestBenefitsBenefictResult.getMedicalTest().addAll(_netInsuranteUnderwrittingCaseManagement_caseManagementRequestBenefitsBenefictResultMedicalTest);
        java.util.List<java.lang.String> _netInsuranteUnderwrittingCaseManagement_caseManagementRequestBenefitsBenefictResultNotes = new java.util.ArrayList<java.lang.String>();
        _netInsuranteUnderwrittingCaseManagement_caseManagementRequestBenefitsBenefictResult.getNotes().addAll(_netInsuranteUnderwrittingCaseManagement_caseManagementRequestBenefitsBenefictResultNotes);
        _netInsuranteUnderwrittingCaseManagement_caseManagementRequestBenefits.setBenefictResult(_netInsuranteUnderwrittingCaseManagement_caseManagementRequestBenefitsBenefictResult);
        _netInsuranteUnderwrittingCaseManagement_caseManagementRequest.setBenefits(_netInsuranteUnderwrittingCaseManagement_caseManagementRequestBenefits);
        com.scortelemed.schemas.netinsurance.NetinsuranteUnderwrittingCaseManagementResponse _netInsuranteUnderwrittingCaseManagement__return = port.netInsuranteUnderwrittingCaseManagement(_netInsuranteUnderwrittingCaseManagement_caseManagementRequest);
        System.out.println("netInsuranteUnderwrittingCaseManagement.result=" + _netInsuranteUnderwrittingCaseManagement__return);


        }
        {
        System.out.println("Invoking netInsuranteUnderwrittingCasesResults...");
        com.scortelemed.schemas.netinsurance.NetinsuranteUnderwrittingCasesResultsRequest _netInsuranteUnderwrittingCasesResults_caseManagementResultsRequest = new com.scortelemed.schemas.netinsurance.NetinsuranteUnderwrittingCasesResultsRequest();
        _netInsuranteUnderwrittingCasesResults_caseManagementResultsRequest.setDateStart(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-09-17T16:10:48.169+02:00"));
        _netInsuranteUnderwrittingCasesResults_caseManagementResultsRequest.setDateEnd(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-09-17T16:10:48.169+02:00"));
        com.scortelemed.schemas.netinsurance.NetinsuranteUnderwrittingCasesResultsResponse _netInsuranteUnderwrittingCasesResults__return = port.netInsuranteUnderwrittingCasesResults(_netInsuranteUnderwrittingCasesResults_caseManagementResultsRequest);
        System.out.println("netInsuranteUnderwrittingCasesResults.result=" + _netInsuranteUnderwrittingCasesResults__return);


        }

        System.exit(0);
    }

}
