
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.scortelemed.schemas.methislab;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.1
 * Tue Aug 07 14:17:46 CEST 2018
 * Generated source version: 2.1
 * 
 */

@javax.jws.WebService(name = "MethislabUnderwrittingCaseManagementService",
                      serviceName = "MethislabUnderwrittingCaseManagementServiceService",
                      portName = "MethislabUnderwrittingCaseManagementServicePort",
                      targetNamespace = "http://www.scortelemed.com/schemas/methislab", 
                      wsdlLocation = "http://localhost:8080/scorWebservice/services/methislab/MethislabUnderwrittingCaseManagement?wsdl",
                      endpointInterface = "com.scortelemed.schemas.methislab.MethislabUnderwrittingCaseManagementService")
                      
public class MethislabUnderwrittingCaseManagementServiceImpl implements MethislabUnderwrittingCaseManagementService {

    private static final Logger LOG = Logger.getLogger(MethislabUnderwrittingCaseManagementServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see com.scortelemed.schemas.methislab.MethislabUnderwrittingCaseManagementService#methislabUnderwrittingCasesResults(com.scortelemed.schemas.methislab.MethislabUnderwrittingCasesResultsRequest  caseManagementResultsRequest )*
     */
    public com.scortelemed.schemas.methislab.MethislabUnderwrittingCasesResultsResponse methislabUnderwrittingCasesResults(MethislabUnderwrittingCasesResultsRequest caseManagementResultsRequest) { 
        LOG.info("Executing operation methislabUnderwrittingCasesResults");
        System.out.println(caseManagementResultsRequest);
        try {
            com.scortelemed.schemas.methislab.MethislabUnderwrittingCasesResultsResponse _return = new com.scortelemed.schemas.methislab.MethislabUnderwrittingCasesResultsResponse();
            _return.setDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-08-07T14:17:46.949+02:00"));
            com.scortelemed.schemas.methislab.StatusType _returnStatus = com.scortelemed.schemas.methislab.StatusType.ERROR;
            _return.setStatus(_returnStatus);
            _return.setNotes("Notes-1861618103");
            java.util.List<com.scortelemed.schemas.methislab.MethislabUnderwrittingCasesResultsResponse.Expediente> _returnExpediente = new java.util.ArrayList<com.scortelemed.schemas.methislab.MethislabUnderwrittingCasesResultsResponse.Expediente>();
            com.scortelemed.schemas.methislab.MethislabUnderwrittingCasesResultsResponse.Expediente _returnExpedienteVal1 = new com.scortelemed.schemas.methislab.MethislabUnderwrittingCasesResultsResponse.Expediente();
            _returnExpedienteVal1.setRequestDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-08-07T14:17:46.950+02:00"));
            _returnExpedienteVal1.setRequestNumber("RequestNumber-1265789471");
            com.scortelemed.schemas.methislab.RequestStateType _returnExpedienteVal1RequestState = com.scortelemed.schemas.methislab.RequestStateType.CLOSED;
            _returnExpedienteVal1.setRequestState(_returnExpedienteVal1RequestState);
            _returnExpedienteVal1.setProductCode("ProductCode-1179312157");
            _returnExpedienteVal1.setPolicyNumber("PolicyNumber-977016184");
            _returnExpedienteVal1.setCertificateNumber("CertificateNumber-1230153576");
            _returnExpedienteVal1.setFiscalIdentificationNumber("FiscalIdentificationNumber375364618");
            _returnExpedienteVal1.setMobilePhone("MobilePhone168405872");
            _returnExpedienteVal1.setPhoneNumber1("PhoneNumber1-611394670");
            _returnExpedienteVal1.setPhoneNumber2("PhoneNumber2-1268284865");
            java.util.List<com.scortelemed.schemas.methislab.BenefitsType> _returnExpedienteVal1BenefitsList = new java.util.ArrayList<com.scortelemed.schemas.methislab.BenefitsType>();
            _returnExpedienteVal1.getBenefitsList().addAll(_returnExpedienteVal1BenefitsList);
            byte[] _returnExpedienteVal1Zip = new byte[] {};
            _returnExpedienteVal1.setZip(_returnExpedienteVal1Zip);
            _returnExpedienteVal1.setNotes("Notes294129718");
            _returnExpediente.add(_returnExpedienteVal1);
            _return.getExpediente().addAll(_returnExpediente);
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.scortelemed.schemas.methislab.MethislabUnderwrittingCaseManagementService#methislabUnderwrittingCaseManagement(com.scortelemed.schemas.methislab.MethislabUnderwrittingCaseManagementRequest  caseManagementRequest )*
     */
    public com.scortelemed.schemas.methislab.MethislabUnderwrittingCaseManagementResponse methislabUnderwrittingCaseManagement(MethislabUnderwrittingCaseManagementRequest caseManagementRequest) { 
        LOG.info("Executing operation methislabUnderwrittingCaseManagement");
        System.out.println(caseManagementRequest);
        try {
            com.scortelemed.schemas.methislab.MethislabUnderwrittingCaseManagementResponse _return = new com.scortelemed.schemas.methislab.MethislabUnderwrittingCaseManagementResponse();
            com.scortelemed.schemas.methislab.StatusType _returnStatus = com.scortelemed.schemas.methislab.StatusType.OK;
            _return.setStatus(_returnStatus);
            _return.setDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-08-07T14:17:46.951+02:00"));
            _return.setMessage("Message1775959609");
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
