
package com.scortelemed.schemas.methislab;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.1
 * Tue Aug 07 14:17:46 CEST 2018
 * Generated source version: 2.1
 * 
 */

@WebService(targetNamespace = "http://www.scortelemed.com/schemas/methislab", name = "MethislabUnderwrittingCaseManagementService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)

public interface MethislabUnderwrittingCaseManagementService {

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "CaseManagementResultsResponse", targetNamespace = "http://www.scortelemed.com/schemas/methislab", partName = "CaseManagementResultsResponse")
    @WebMethod
    public MethislabUnderwrittingCasesResultsResponse methislabUnderwrittingCasesResults(
        @WebParam(partName = "CaseManagementResultsRequest", name = "CaseManagementResultsRequest", targetNamespace = "http://www.scortelemed.com/schemas/methislab")
        MethislabUnderwrittingCasesResultsRequest caseManagementResultsRequest
    );

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "CaseManagementResponse", targetNamespace = "http://www.scortelemed.com/schemas/methislab", partName = "CaseManagementResponse")
    @WebMethod
    public MethislabUnderwrittingCaseManagementResponse methislabUnderwrittingCaseManagement(
        @WebParam(partName = "CaseManagementRequest", name = "CaseManagementRequest", targetNamespace = "http://www.scortelemed.com/schemas/methislab")
        MethislabUnderwrittingCaseManagementRequest caseManagementRequest
    );
}
