
package com.scortelemed.schemas.methislab;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 2.1
 * Tue Aug 07 14:17:46 CEST 2018
 * Generated source version: 2.1
 * 
 */

@WebServiceClient(name = "MethislabUnderwrittingCaseManagementServiceService", targetNamespace = "http://www.scortelemed.com/schemas/methislab", wsdlLocation = "http://localhost:8080/scorWebservice/services/methislab/MethislabUnderwrittingCaseManagement?wsdl")
public class MethislabUnderwrittingCaseManagementServiceService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://www.scortelemed.com/schemas/methislab", "MethislabUnderwrittingCaseManagementServiceService");
    public final static QName MethislabUnderwrittingCaseManagementServicePort = new QName("http://www.scortelemed.com/schemas/methislab", "MethislabUnderwrittingCaseManagementServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/scorWebservice/services/methislab/MethislabUnderwrittingCaseManagement?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://localhost:8080/scorWebservice/services/methislab/MethislabUnderwrittingCaseManagement?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public MethislabUnderwrittingCaseManagementServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public MethislabUnderwrittingCaseManagementServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MethislabUnderwrittingCaseManagementServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns MethislabUnderwrittingCaseManagementService
     */
    @WebEndpoint(name = "MethislabUnderwrittingCaseManagementServicePort")
    public MethislabUnderwrittingCaseManagementService getMethislabUnderwrittingCaseManagementServicePort() {
        return super.getPort(MethislabUnderwrittingCaseManagementServicePort, MethislabUnderwrittingCaseManagementService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MethislabUnderwrittingCaseManagementService
     */
    @WebEndpoint(name = "MethislabUnderwrittingCaseManagementServicePort")
    public MethislabUnderwrittingCaseManagementService getMethislabUnderwrittingCaseManagementServicePort(WebServiceFeature... features) {
        return super.getPort(MethislabUnderwrittingCaseManagementServicePort, MethislabUnderwrittingCaseManagementService.class, features);
    }

}
