
package com.scortelemed.schemas.methislabCF;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.1
 * Tue Aug 07 14:17:46 CEST 2018
 * Generated source version: 2.1
 * 
 */

@WebService(targetNamespace = "http://www.scortelemed.com/schemas/methislabCF", name = "MethislabCFUnderwrittingCaseManagementService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = ParameterStyle.BARE)

public interface MethislabCFUnderwrittingCaseManagementService {

    @SOAPBinding(parameterStyle = ParameterStyle.BARE)
    @WebResult(name = "CaseManagementResultsResponse", targetNamespace = "http://www.scortelemed.com/schemas/methislabCF", partName = "CaseManagementResultsResponse")
    @WebMethod
    public MethislabCFUnderwrittingCasesResultsResponse methislabCFUnderwrittingCasesResults(
            @WebParam(partName = "CaseManagementResultsRequest", name = "CaseManagementResultsRequest", targetNamespace = "http://www.scortelemed.com/schemas/methislabCF")
                    MethislabCFUnderwrittingCasesResultsRequest caseManagementResultsRequest
    );

    @SOAPBinding(parameterStyle = ParameterStyle.BARE)
    @WebResult(name = "CaseManagementResponse", targetNamespace = "http://www.scortelemed.com/schemas/methislabCF", partName = "CaseManagementResponse")
    @WebMethod
    public MethislabCFUnderwrittingCaseManagementResponse methislabCFUnderwrittingCaseManagement(
            @WebParam(partName = "CaseManagementRequest", name = "CaseManagementRequest", targetNamespace = "http://www.scortelemed.com/schemas/methislabCF")
                    MethislabCFUnderwrittingCaseManagementRequest caseManagementRequest
    );
}
