
package com.scortelemed.schemas.methislabCF;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 2.1
 * Tue Aug 07 14:17:46 CEST 2018
 * Generated source version: 2.1
 * 
 */

@WebServiceClient(name = "MethislabCFUnderwrittingCaseManagementServiceService", targetNamespace = "http://www.scortelemed.com/schemas/methislabCF", wsdlLocation = "http://localhost:8080/scorWebservice/services/methislabCF/MethislabCFUnderwrittingCaseManagement?wsdl")
public class MethislabCFUnderwrittingCaseManagementServiceService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://www.scortelemed.com/schemas/methislabCF", "MethislabCFUnderwrittingCaseManagementServiceService");
    public final static QName MethislabCFUnderwrittingCaseManagementServicePort = new QName("http://www.scortelemed.com/schemas/methislabCF", "MethislabCFUnderwrittingCaseManagementServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/scorWebservice/services/methislabCF/MethislabCFUnderwrittingCaseManagement?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://localhost:8080/scorWebservice/services/methislabCF/MethislabCFUnderwrittingCaseManagement?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public MethislabCFUnderwrittingCaseManagementServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public MethislabCFUnderwrittingCaseManagementServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MethislabCFUnderwrittingCaseManagementServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns MethislabCFUnderwrittingCaseManagementService
     */
    @WebEndpoint(name = "MethislabCFUnderwrittingCaseManagementServicePort")
    public MethislabCFUnderwrittingCaseManagementService getMethislabUnderwrittingCaseManagementServicePort() {
        return super.getPort(MethislabCFUnderwrittingCaseManagementServicePort, MethislabCFUnderwrittingCaseManagementService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MethislabCFUnderwrittingCaseManagementService
     */
    @WebEndpoint(name = "MethislabCFUnderwrittingCaseManagementServicePort")
    public MethislabCFUnderwrittingCaseManagementService getMethislabUnderwrittingCaseManagementServicePort(WebServiceFeature... features) {
        return super.getPort(MethislabCFUnderwrittingCaseManagementServicePort, MethislabCFUnderwrittingCaseManagementService.class, features);
    }

}
