
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.scortelemed.schemas.methislabCF;

import javax.jws.WebService;
import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 2.1
 * Tue Aug 07 14:17:46 CEST 2018
 * Generated source version: 2.1
 * 
 */

@WebService(name = "MethislabCFUnderwrittingCaseManagementService",
                      serviceName = "MethislabCFUnderwrittingCaseManagementServiceService",
                      portName = "MethislabCFUnderwrittingCaseManagementServicePort",
                      targetNamespace = "http://www.scortelemed.com/schemas/methislabCF",
                      wsdlLocation = "http://localhost:8080/scorWebservice/services/methislabCF/MethislabCFUnderwrittingCaseManagement?wsdl",
                      endpointInterface = "com.scortelemed.schemas.methislabCF.MethislabCFUnderwrittingCaseManagementService")
                      
public class MethislabCFUnderwrittingCaseManagementServiceImpl implements MethislabCFUnderwrittingCaseManagementService {

    private static final Logger LOG = Logger.getLogger(MethislabCFUnderwrittingCaseManagementServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see com.scortelemed.schemas.methislab.MethislabCFUnderwrittingCaseManagementService#methislabUnderwrittingCasesResults(com.scortelemed.schemas.methislab.MethislabCFUnderwrittingCasesResultsRequest  caseManagementResultsRequest )*
     */
    public MethislabCFUnderwrittingCasesResultsResponse methislabCFUnderwrittingCasesResults(MethislabCFUnderwrittingCasesResultsRequest caseManagementResultsRequest) {
        LOG.info("Executing operation methislabCFUnderwrittingCasesResults");
        System.out.println(caseManagementResultsRequest);
        try {
            MethislabCFUnderwrittingCasesResultsResponse _return = new MethislabCFUnderwrittingCasesResultsResponse();
            _return.setDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-08-07T14:17:46.949+02:00"));
            StatusType _returnStatus = StatusType.ERROR;
            _return.setStatus(_returnStatus);
            _return.setMessages("Notes-1861618103");
            java.util.List<MethislabCFUnderwrittingCasesResultsResponse.Expediente> _returnExpediente = new java.util.ArrayList<MethislabCFUnderwrittingCasesResultsResponse.Expediente>();
            MethislabCFUnderwrittingCasesResultsResponse.Expediente _returnExpedienteVal1 = new MethislabCFUnderwrittingCasesResultsResponse.Expediente();
            _returnExpedienteVal1.setRequestDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-08-07T14:17:46.950+02:00"));
            _returnExpedienteVal1.setRequestNumber("RequestNumber-1265789471");
            RequestStateType _returnExpedienteVal1RequestState = RequestStateType.CLOSED;
            _returnExpedienteVal1.setRequestState(_returnExpedienteVal1RequestState);
            _returnExpedienteVal1.setProductCode("ProductCode-1179312157");
            _returnExpedienteVal1.setPolicyNumber("PolicyNumber-977016184");
            _returnExpedienteVal1.setCertificateNumber("CertificateNumber-1230153576");
            _returnExpedienteVal1.setFiscalIdentificationNumber("FiscalIdentificationNumber375364618");
            _returnExpedienteVal1.setMobilePhone("MobilePhone168405872");
            _returnExpedienteVal1.setPhoneNumber1("PhoneNumber1-611394670");
            _returnExpedienteVal1.setPhoneNumber2("PhoneNumber2-1268284865");
            java.util.List<BenefitsType> _returnExpedienteVal1BenefitsList = new java.util.ArrayList<BenefitsType>();
            _returnExpedienteVal1.getBenefitsList().addAll(_returnExpedienteVal1BenefitsList);
            byte[] _returnExpedienteVal1Zip = new byte[] {};
            _returnExpedienteVal1.setZip(_returnExpedienteVal1Zip);
            _returnExpedienteVal1.setNotes("Notes294129718");
            _returnExpediente.add(_returnExpedienteVal1);
            _return.getExpediente().addAll(_returnExpediente);
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.scortelemed.schemas.methislab.MethislabCFUnderwrittingCaseManagementService#methislabUnderwrittingCaseManagement(com.scortelemed.schemas.methislab.MethislabCFUnderwrittingCaseManagementRequest  caseManagementRequest )*
     */
    public MethislabCFUnderwrittingCaseManagementResponse methislabCFUnderwrittingCaseManagement(MethislabCFUnderwrittingCaseManagementRequest caseManagementRequest) {
        LOG.info("Executing operation methislabCFUnderwrittingCaseManagement");
        System.out.println(caseManagementRequest);
        try {
            MethislabCFUnderwrittingCaseManagementResponse _return = new MethislabCFUnderwrittingCaseManagementResponse();
            StatusType _returnStatus = StatusType.OK;
            _return.setStatus(_returnStatus);
            _return.setDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-08-07T14:17:46.951+02:00"));
            _return.setMessage("Message1775959609");
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
