
package com.scortelemed.schemas.methislabCF;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import javax.xml.namespace.QName;
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 2.1
 * Tue Aug 07 14:17:46 CEST 2018
 * Generated source version: 2.1
 * 
 */

public final class MethislabCFUnderwrittingCaseManagementService_MethislabCFUnderwrittingCaseManagementServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://www.scortelemed.com/schemas/methislab", "MethislabCFUnderwrittingCaseManagementServiceService");

    private MethislabCFUnderwrittingCaseManagementService_MethislabCFUnderwrittingCaseManagementServicePort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = MethislabCFUnderwrittingCaseManagementServiceService.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        MethislabCFUnderwrittingCaseManagementServiceService ss = new MethislabCFUnderwrittingCaseManagementServiceService(wsdlURL, SERVICE_NAME);
        MethislabCFUnderwrittingCaseManagementService port = ss.getMethislabUnderwrittingCaseManagementServicePort();
        
        {
        System.out.println("Invoking methislabUnderwrittingCasesResults...");
        MethislabCFUnderwrittingCasesResultsRequest _methislabUnderwrittingCasesResults_caseManagementResultsRequest = new MethislabCFUnderwrittingCasesResultsRequest();
        _methislabUnderwrittingCasesResults_caseManagementResultsRequest.setDateStart(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-08-07T14:17:46.936+02:00"));
        _methislabUnderwrittingCasesResults_caseManagementResultsRequest.setDateEnd(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-08-07T14:17:46.937+02:00"));
        MethislabCFUnderwrittingCasesResultsResponse _methislabUnderwrittingCasesResults__return = port.methislabUnderwrittingCasesResults(_methislabUnderwrittingCasesResults_caseManagementResultsRequest);
        System.out.println("methislabUnderwrittingCasesResults.result=" + _methislabUnderwrittingCasesResults__return);


        }
        {
        System.out.println("Invoking methislabUnderwrittingCaseManagement...");
        MethislabCFUnderwrittingCaseManagementRequest _methislabUnderwrittingCaseManagement_caseManagementRequest = new MethislabCFUnderwrittingCaseManagementRequest();
        MethislabCFUnderwrittingCaseManagementRequest.CandidateInformation _methislabUnderwrittingCaseManagement_caseManagementRequestCandidateInformation = new MethislabCFUnderwrittingCaseManagementRequest.CandidateInformation();
        _methislabUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setProductCode("ProductCode552966720");
        _methislabUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setRequestNumber("RequestNumber536419523");
        _methislabUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setPolicyNumber("PolicyNumber-1045213038");
        _methislabUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setCertificateNumber("CertificateNumber-1740352435");
        _methislabUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setRequestDate("RequestDate1412071139");
        _methislabUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setPassword("Password-876213241");
        _methislabUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setRequestState("RequestState868115282");
        _methislabUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setName("Name563299164");
        _methislabUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setSurname("Surname1385370235");
        _methislabUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setAddress("Address49061535");
        _methislabUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setPostalCode("PostalCode161684724");
        _methislabUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setCity("City1866067532");
        _methislabUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setProvince("Province-1089269968");
        _methislabUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setCountry("Country-1194770840");
        _methislabUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setPhoneNumber1("PhoneNumber1885781441");
        _methislabUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setPhoneNumber2("PhoneNumber2200399811");
        _methislabUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setMobileNumber("MobileNumber397231642");
        _methislabUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setEmail("Email447882798");
        _methislabUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setBirthDate("BirthDate-610200519");
        _methislabUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setActuarialAge("ActuarialAge126661083");
        _methislabUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setBirthCity("BirthCity1638561763");
        _methislabUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setFiscalIdentificationNumber("FiscalIdentificationNumber-1303054459");
        _methislabUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setAgency("Agency124626008");
        _methislabUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setAgent("Agent-156175851");
        _methislabUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setAgentPhone("AgentPhone2059572138");
        _methislabUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setAgentEmail("AgentEmail-1258858024");
        GenderType _methislabUnderwrittingCaseManagement_caseManagementRequestCandidateInformationGender = GenderType.H;
        _methislabUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setGender(_methislabUnderwrittingCaseManagement_caseManagementRequestCandidateInformationGender);
        CivilStateType _methislabUnderwrittingCaseManagement_caseManagementRequestCandidateInformationCivilState = CivilStateType.P;
        _methislabUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setCivilState(_methislabUnderwrittingCaseManagement_caseManagementRequestCandidateInformationCivilState);
        _methislabUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setCustomerType("CustomerType-1772060630");
        ContactTimeType _methislabUnderwrittingCaseManagement_caseManagementRequestCandidateInformationContactTime = ContactTimeType.N;
        _methislabUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setContactTime(_methislabUnderwrittingCaseManagement_caseManagementRequestCandidateInformationContactTime);
        _methislabUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setComments("Comments1091564609");
        _methislabUnderwrittingCaseManagement_caseManagementRequestCandidateInformation.setEUWReferenceCode("EUWReferenceCode1019538029");
        _methislabUnderwrittingCaseManagement_caseManagementRequest.setCandidateInformation(_methislabUnderwrittingCaseManagement_caseManagementRequestCandidateInformation);
        java.util.List<MethislabCFUnderwrittingCaseManagementRequest.PreviousQuestions> _methislabUnderwrittingCaseManagement_caseManagementRequestPreviousQuestions = new java.util.ArrayList<MethislabCFUnderwrittingCaseManagementRequest.PreviousQuestions>();
        MethislabCFUnderwrittingCaseManagementRequest.PreviousQuestions _methislabUnderwrittingCaseManagement_caseManagementRequestPreviousQuestionsVal1 = new MethislabCFUnderwrittingCaseManagementRequest.PreviousQuestions();
        QuestionDataType _methislabUnderwrittingCaseManagement_caseManagementRequestPreviousQuestionsVal1DataType = QuestionDataType.STRING;
        _methislabUnderwrittingCaseManagement_caseManagementRequestPreviousQuestionsVal1.setDataType(_methislabUnderwrittingCaseManagement_caseManagementRequestPreviousQuestionsVal1DataType);
        _methislabUnderwrittingCaseManagement_caseManagementRequestPreviousQuestionsVal1.setAnswerCode("AnswerCode1461610396");
        _methislabUnderwrittingCaseManagement_caseManagementRequestPreviousQuestionsVal1.setQuestion("Question1043150933");
        _methislabUnderwrittingCaseManagement_caseManagementRequestPreviousQuestionsVal1.setAnswer("Answer-1921605722");
        _methislabUnderwrittingCaseManagement_caseManagementRequestPreviousQuestions.add(_methislabUnderwrittingCaseManagement_caseManagementRequestPreviousQuestionsVal1);
        _methislabUnderwrittingCaseManagement_caseManagementRequest.getPreviousQuestions().addAll(_methislabUnderwrittingCaseManagement_caseManagementRequestPreviousQuestions);
        java.util.List<MethislabCFUnderwrittingCaseManagementRequest.Services> _methislabUnderwrittingCaseManagement_caseManagementRequestServices = new java.util.ArrayList<MethislabCFUnderwrittingCaseManagementRequest.Services>();
        MethislabCFUnderwrittingCaseManagementRequest.Services _methislabUnderwrittingCaseManagement_caseManagementRequestServicesVal1 = new MethislabCFUnderwrittingCaseManagementRequest.Services();
        _methislabUnderwrittingCaseManagement_caseManagementRequestServicesVal1.setServiceType("ServiceType-505537832");
        _methislabUnderwrittingCaseManagement_caseManagementRequestServicesVal1.setServiceCode("ServiceCode1225123926");
        _methislabUnderwrittingCaseManagement_caseManagementRequestServicesVal1.setServiceDescription("ServiceDescription-1312378644");
        _methislabUnderwrittingCaseManagement_caseManagementRequestServices.add(_methislabUnderwrittingCaseManagement_caseManagementRequestServicesVal1);
        _methislabUnderwrittingCaseManagement_caseManagementRequest.getServices().addAll(_methislabUnderwrittingCaseManagement_caseManagementRequestServices);
        BenefitsType _methislabUnderwrittingCaseManagement_caseManagementRequestBenefits = new BenefitsType();
        BenefictNameType _methislabUnderwrittingCaseManagement_caseManagementRequestBenefitsBenefictName = BenefictNameType.DISABILITY_30_90;
        _methislabUnderwrittingCaseManagement_caseManagementRequestBenefits.setBenefictName(_methislabUnderwrittingCaseManagement_caseManagementRequestBenefitsBenefictName);
        _methislabUnderwrittingCaseManagement_caseManagementRequestBenefits.setBenefictCode("BenefictCode10198593");
        _methislabUnderwrittingCaseManagement_caseManagementRequestBenefits.setBenefictCapital("BenefictCapital1499980682");
        BenefictResultType _methislabUnderwrittingCaseManagement_caseManagementRequestBenefitsBenefictResult = new BenefictResultType();
        _methislabUnderwrittingCaseManagement_caseManagementRequestBenefitsBenefictResult.setDescResult("DescResult-957302485");
        _methislabUnderwrittingCaseManagement_caseManagementRequestBenefitsBenefictResult.setResultCode("ResultCode1025243811");
        _methislabUnderwrittingCaseManagement_caseManagementRequestBenefitsBenefictResult.setPremiumLoading("PremiumLoading-419842334");
        _methislabUnderwrittingCaseManagement_caseManagementRequestBenefitsBenefictResult.setCapitalLoading("CapitalLoading895265742");
        _methislabUnderwrittingCaseManagement_caseManagementRequestBenefitsBenefictResult.setDescPremiumLoading("DescPremiumLoading782695052");
        _methislabUnderwrittingCaseManagement_caseManagementRequestBenefitsBenefictResult.setDescCapitalLoading("DescCapitalLoading2119111401");
        java.util.List<String> _methislabUnderwrittingCaseManagement_caseManagementRequestBenefitsBenefictResultTemporalLoading = new java.util.ArrayList<String>();
        _methislabUnderwrittingCaseManagement_caseManagementRequestBenefitsBenefictResult.getTemporalLoading().addAll(_methislabUnderwrittingCaseManagement_caseManagementRequestBenefitsBenefictResultTemporalLoading);
        java.util.List<String> _methislabUnderwrittingCaseManagement_caseManagementRequestBenefitsBenefictResultExclusions = new java.util.ArrayList<String>();
        _methislabUnderwrittingCaseManagement_caseManagementRequestBenefitsBenefictResult.getExclusions().addAll(_methislabUnderwrittingCaseManagement_caseManagementRequestBenefitsBenefictResultExclusions);
        java.util.List<String> _methislabUnderwrittingCaseManagement_caseManagementRequestBenefitsBenefictResultMedicalReports = new java.util.ArrayList<String>();
        _methislabUnderwrittingCaseManagement_caseManagementRequestBenefitsBenefictResult.getMedicalReports().addAll(_methislabUnderwrittingCaseManagement_caseManagementRequestBenefitsBenefictResultMedicalReports);
        java.util.List<String> _methislabUnderwrittingCaseManagement_caseManagementRequestBenefitsBenefictResultMedicalTest = new java.util.ArrayList<String>();
        _methislabUnderwrittingCaseManagement_caseManagementRequestBenefitsBenefictResult.getMedicalTest().addAll(_methislabUnderwrittingCaseManagement_caseManagementRequestBenefitsBenefictResultMedicalTest);
        java.util.List<String> _methislabUnderwrittingCaseManagement_caseManagementRequestBenefitsBenefictResultNotes = new java.util.ArrayList<String>();
        _methislabUnderwrittingCaseManagement_caseManagementRequestBenefitsBenefictResult.getNotes().addAll(_methislabUnderwrittingCaseManagement_caseManagementRequestBenefitsBenefictResultNotes);
        _methislabUnderwrittingCaseManagement_caseManagementRequestBenefits.setBenefictResult(_methislabUnderwrittingCaseManagement_caseManagementRequestBenefitsBenefictResult);
        _methislabUnderwrittingCaseManagement_caseManagementRequest.setBenefits(_methislabUnderwrittingCaseManagement_caseManagementRequestBenefits);
        MethislabCFUnderwrittingCaseManagementResponse _methislabUnderwrittingCaseManagement__return = port.methislabUnderwrittingCaseManagement(_methislabUnderwrittingCaseManagement_caseManagementRequest);
        System.out.println("methislabUnderwrittingCaseManagement.result=" + _methislabUnderwrittingCaseManagement__return);


        }

        System.exit(0);
    }

}
