
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.scortelemed.schemas.enginyers;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.1
 * Mon Feb 04 15:37:02 CET 2019
 * Generated source version: 2.1
 * 
 */

@WebService(name = "GestionReconocimientosMedicosService",
                      serviceName = "GestionReconocimientosMedicosServiceService",
                      portName = "GestionReconocimientosMedicosServicePort",
                      targetNamespace = "http://www.scortelemed.com/schemas/enginyers", 
                      wsdlLocation = "http://localhost:8080/scorWebservice/services/enginyers/GestionReconocimientosMedicos?wsdl",
                      endpointInterface = "com.scortelemed.schemas.enginyers.GestionReconocimientosMedicosService")
                      
public class GestionReconocimientosMedicosServiceImpl implements GestionReconocimientosMedicosService {

    private static final Logger LOG = Logger.getLogger(GestionReconocimientosMedicosServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see com.scortelemed.schemas.enginyers.GestionReconocimientosMedicosService#updateSurvey(long  surveyNumber ,)com.scortelemed.schemas.enginyers.SurveyData  d ,)com.scortelemed.schemas.enginyers.ArrayOfRiskTypeElement  risks ,)com.scortelemed.schemas.enginyers.SurveyGeneralProperties  gen ,)com.scortelemed.schemas.enginyers.ArrayOfGroups  questionsArray ,)com.scortelemed.schemas.enginyers.SurveyAdditionalFields  additional )*
     */
    public Survey updateSurvey(long surveyNumber, SurveyData d, ArrayOfRiskTypeElement risks, com.scortelemed.schemas.enginyers.SurveyGeneralProperties gen, ArrayOfGroups questionsArray, SurveyAdditionalFields additional) {
        LOG.info("Executing operation updateSurvey");
        System.out.println(surveyNumber);
        System.out.println(d);
        System.out.println(risks);
        System.out.println(gen);
        System.out.println(questionsArray);
        System.out.println(additional);
        try {
            Survey _return = new Survey();
            _return.setSurveyNumber(90692942);
            com.scortelemed.schemas.enginyers.SurveyGeneralProperties _returnGeneralData = new com.scortelemed.schemas.enginyers.SurveyGeneralProperties();
            _returnGeneralData.setProduct("Product-30590460");
            _returnGeneralData.setBonsaiVersion("BonsaiVersion-1005275464");
            _returnGeneralData.setCompanyCode(177387498);
            _returnGeneralData.setLang("Lang-1880999141");
            _return.setGeneralData(_returnGeneralData);
            SurveyData _returnPersonData = new SurveyData();
            _returnPersonData.setName("Name671614381");
            _returnPersonData.setSurname("Surname-304526507");
            _returnPersonData.setNif("Nif1792719385");
            _returnPersonData.setBirthDate("BirthDate-1856715087");
            GenderType _returnPersonDataGender = GenderType.M;
            _returnPersonData.setGender(_returnPersonDataGender);
            _returnPersonData.setTown("Town-1253402849");
            _returnPersonData.setCity("City-682105072");
            _returnPersonData.setPostalCode("PostalCode412617195");
            _returnPersonData.setCountry("Country1581047061");
            _returnPersonData.setNationality("Nationality-1190838251");
            _returnPersonData.setPhone("Phone-109116520");
            _returnPersonData.setCellPhone("CellPhone-22177368");
            _returnPersonData.setEmail("Email-1848090319");
            _returnPersonData.setAddress("Address1778479569");
            _returnPersonData.setPolicyNumber("PolicyNumber1937263789");
            _returnPersonData.setProfessionCode("ProfessionCode-2043617913");
            _returnPersonData.setRetain(Boolean.valueOf(true));
            _returnPersonData.setRetainResponse("RetainResponse-1843235603");
            _return.setPersonData(_returnPersonData);
            ArrayOfRiskTypeElement _returnRiskTypeArray = new ArrayOfRiskTypeElement();
            java.util.List<com.scortelemed.schemas.enginyers.RiskTypeElement> _returnRiskTypeArrayRiskTypeElement = new java.util.ArrayList<com.scortelemed.schemas.enginyers.RiskTypeElement>();
            com.scortelemed.schemas.enginyers.RiskTypeElement _returnRiskTypeArrayRiskTypeElementVal1 = new com.scortelemed.schemas.enginyers.RiskTypeElement();
            _returnRiskTypeArrayRiskTypeElementVal1.setIdRisk(1970717961);
            _returnRiskTypeArrayRiskTypeElementVal1.setRiskName("RiskName1034293233");
            _returnRiskTypeArrayRiskTypeElementVal1.setRiskValue(0.760306448566063);
            RiskSelectionElement _returnRiskTypeArrayRiskTypeElementVal1RiskSelection = new RiskSelectionElement();
            _returnRiskTypeArrayRiskTypeElementVal1RiskSelection.setRetain(false);
            _returnRiskTypeArrayRiskTypeElementVal1RiskSelection.setRetainResponse("RetainResponse879409755");
            _returnRiskTypeArrayRiskTypeElementVal1RiskSelection.setOverchargeMotive("OverchargeMotive-1975027629");
            _returnRiskTypeArrayRiskTypeElementVal1RiskSelection.setPremiumLoadings(0.32215992259249526);
            _returnRiskTypeArrayRiskTypeElementVal1RiskSelection.setExtraPremiumLoadings(0.7050048087409153);
            _returnRiskTypeArrayRiskTypeElementVal1RiskSelection.setRiskSelectionComment("RiskSelectionComment-706299511");
            ArrayOfExclusionsElement _returnRiskTypeArrayRiskTypeElementVal1RiskSelectionExclusions = new ArrayOfExclusionsElement();
            java.util.List<ExclusionElement> _returnRiskTypeArrayRiskTypeElementVal1RiskSelectionExclusionsExclusion = new java.util.ArrayList<ExclusionElement>();
            _returnRiskTypeArrayRiskTypeElementVal1RiskSelectionExclusions.getExclusion().addAll(_returnRiskTypeArrayRiskTypeElementVal1RiskSelectionExclusionsExclusion);
            _returnRiskTypeArrayRiskTypeElementVal1RiskSelection.setExclusions(_returnRiskTypeArrayRiskTypeElementVal1RiskSelectionExclusions);
            _returnRiskTypeArrayRiskTypeElementVal1.setRiskSelection(_returnRiskTypeArrayRiskTypeElementVal1RiskSelection);
            _returnRiskTypeArrayRiskTypeElement.add(_returnRiskTypeArrayRiskTypeElementVal1);
            _returnRiskTypeArray.getRiskTypeElement().addAll(_returnRiskTypeArrayRiskTypeElement);
            _return.setRiskTypeArray(_returnRiskTypeArray);
            ArrayOfGroups _returnQuestionsArray = new ArrayOfGroups();
            java.util.List<com.scortelemed.schemas.enginyers.GroupElement> _returnQuestionsArrayGroupElement = new java.util.ArrayList<com.scortelemed.schemas.enginyers.GroupElement>();
            com.scortelemed.schemas.enginyers.GroupElement _returnQuestionsArrayGroupElementVal1 = new com.scortelemed.schemas.enginyers.GroupElement();
            _returnQuestionsArrayGroupElementVal1.setNumber(1993198467);
            _returnQuestionsArrayGroupElementVal1.setTitle("Title-1535846499");
            ArrayOfQuestionsElement _returnQuestionsArrayGroupElementVal1QuestionElementArray = new ArrayOfQuestionsElement();
            java.util.List<QuestionsElement> _returnQuestionsArrayGroupElementVal1QuestionElementArrayQuestionsElement = new java.util.ArrayList<QuestionsElement>();
            _returnQuestionsArrayGroupElementVal1QuestionElementArray.getQuestionsElement().addAll(_returnQuestionsArrayGroupElementVal1QuestionElementArrayQuestionsElement);
            _returnQuestionsArrayGroupElementVal1.setQuestionElementArray(_returnQuestionsArrayGroupElementVal1QuestionElementArray);
            _returnQuestionsArrayGroupElement.add(_returnQuestionsArrayGroupElementVal1);
            _returnQuestionsArray.getGroupElement().addAll(_returnQuestionsArrayGroupElement);
            _return.setQuestionsArray(_returnQuestionsArray);
            SurveyAdditionalFields _returnAdditional = new SurveyAdditionalFields();
            java.util.List<AdditionalFieldElement> _returnAdditionalAdditionalField = new java.util.ArrayList<AdditionalFieldElement>();
            AdditionalFieldElement _returnAdditionalAdditionalFieldVal1 = new AdditionalFieldElement();
            _returnAdditionalAdditionalFieldVal1.setName("Name-1580833346");
            _returnAdditionalAdditionalFieldVal1.setValue("Value1950006430");
            _returnAdditionalAdditionalField.add(_returnAdditionalAdditionalFieldVal1);
            _returnAdditional.getAdditionalField().addAll(_returnAdditionalAdditionalField);
            _return.setAdditional(_returnAdditional);
            ArrayOfFaultElement _returnFaultArray = new ArrayOfFaultElement();
            java.util.List<com.scortelemed.schemas.enginyers.FaultElement> _returnFaultArrayFaultElement = new java.util.ArrayList<com.scortelemed.schemas.enginyers.FaultElement>();
            com.scortelemed.schemas.enginyers.FaultElement _returnFaultArrayFaultElementVal1 = new com.scortelemed.schemas.enginyers.FaultElement();
            _returnFaultArrayFaultElementVal1.setFaultCode("FaultCode1204125847");
            _returnFaultArrayFaultElementVal1.setFaultString("FaultString494215807");
            _returnFaultArrayFaultElementVal1.setFaultActor("FaultActor-57262289");
            ErrorElement _returnFaultArrayFaultElementVal1Detail = new ErrorElement();
            _returnFaultArrayFaultElementVal1Detail.setErrorNumber(-826327266);
            _returnFaultArrayFaultElementVal1Detail.setErrorMessage("ErrorMessage-1577323610");
            _returnFaultArrayFaultElementVal1Detail.setErrorSource("ErrorSource-1947094078");
            _returnFaultArrayFaultElementVal1.setDetail(_returnFaultArrayFaultElementVal1Detail);
            _returnFaultArrayFaultElement.add(_returnFaultArrayFaultElementVal1);
            _returnFaultArray.getFaultElement().addAll(_returnFaultArrayFaultElement);
            _return.setFaultArray(_returnFaultArray);
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.scortelemed.schemas.enginyers.GestionReconocimientosMedicosService#addSurveyExtern(com.scortelemed.schemas.enginyers.SurveyData  d ,)com.scortelemed.schemas.enginyers.ArrayOfRiskTypeElement  risks ,)com.scortelemed.schemas.enginyers.SurveyGeneralProperties  gen ,)com.scortelemed.schemas.enginyers.SurveyAdditionalFields  additional )*
     */
    public Peticio addSurveyExtern(SurveyData d, ArrayOfRiskTypeElement risks, com.scortelemed.schemas.enginyers.SurveyGeneralProperties gen, SurveyAdditionalFields additional) {
        LOG.info("Executing operation addSurveyExtern");
        System.out.println(d);
        System.out.println(risks);
        System.out.println(gen);
        System.out.println(additional);
        try {
            Peticio _return = new Peticio();
            _return.setUrlPeticio("UrlPeticio-1462582699");
            ArrayOfFaultElement _returnFaultArray = new ArrayOfFaultElement();
            java.util.List<com.scortelemed.schemas.enginyers.FaultElement> _returnFaultArrayFaultElement = new java.util.ArrayList<com.scortelemed.schemas.enginyers.FaultElement>();
            com.scortelemed.schemas.enginyers.FaultElement _returnFaultArrayFaultElementVal1 = new com.scortelemed.schemas.enginyers.FaultElement();
            _returnFaultArrayFaultElementVal1.setFaultCode("FaultCode-14026550");
            _returnFaultArrayFaultElementVal1.setFaultString("FaultString-1184971499");
            _returnFaultArrayFaultElementVal1.setFaultActor("FaultActor1369832660");
            ErrorElement _returnFaultArrayFaultElementVal1Detail = new ErrorElement();
            _returnFaultArrayFaultElementVal1Detail.setErrorNumber(-1483852330);
            _returnFaultArrayFaultElementVal1Detail.setErrorMessage("ErrorMessage739000607");
            _returnFaultArrayFaultElementVal1Detail.setErrorSource("ErrorSource-1877807849");
            _returnFaultArrayFaultElementVal1.setDetail(_returnFaultArrayFaultElementVal1Detail);
            _returnFaultArrayFaultElement.add(_returnFaultArrayFaultElementVal1);
            _returnFaultArray.getFaultElement().addAll(_returnFaultArrayFaultElement);
            _return.setFaultArray(_returnFaultArray);
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.scortelemed.schemas.enginyers.GestionReconocimientosMedicosService#addSurvey(com.scortelemed.schemas.enginyers.SurveyData  d ,)com.scortelemed.schemas.enginyers.ArrayOfRiskTypeElement  risks ,)com.scortelemed.schemas.enginyers.SurveyGeneralProperties  gen ,)com.scortelemed.schemas.enginyers.SurveyAdditionalFields  additional )*
     */
    public Survey addSurvey(SurveyData d, ArrayOfRiskTypeElement risks, com.scortelemed.schemas.enginyers.SurveyGeneralProperties gen, SurveyAdditionalFields additional) {
        LOG.info("Executing operation addSurvey");
        System.out.println(d);
        System.out.println(risks);
        System.out.println(gen);
        System.out.println(additional);
        try {
            Survey _return = new Survey();
            _return.setSurveyNumber(-2055784185);
            com.scortelemed.schemas.enginyers.SurveyGeneralProperties _returnGeneralData = new com.scortelemed.schemas.enginyers.SurveyGeneralProperties();
            _returnGeneralData.setProduct("Product-168564730");
            _returnGeneralData.setBonsaiVersion("BonsaiVersion-1634326344");
            _returnGeneralData.setCompanyCode(-1551473854);
            _returnGeneralData.setLang("Lang1425522582");
            _return.setGeneralData(_returnGeneralData);
            SurveyData _returnPersonData = new SurveyData();
            _returnPersonData.setName("Name563196575");
            _returnPersonData.setSurname("Surname1948730608");
            _returnPersonData.setNif("Nif-1858327713");
            _returnPersonData.setBirthDate("BirthDate775877097");
            GenderType _returnPersonDataGender = GenderType.F;
            _returnPersonData.setGender(_returnPersonDataGender);
            _returnPersonData.setTown("Town1622020555");
            _returnPersonData.setCity("City-2121540735");
            _returnPersonData.setPostalCode("PostalCode945506839");
            _returnPersonData.setCountry("Country-497275433");
            _returnPersonData.setNationality("Nationality-880734699");
            _returnPersonData.setPhone("Phone-1467289768");
            _returnPersonData.setCellPhone("CellPhone-2131210835");
            _returnPersonData.setEmail("Email-1319253589");
            _returnPersonData.setAddress("Address-580192821");
            _returnPersonData.setPolicyNumber("PolicyNumber-907576122");
            _returnPersonData.setProfessionCode("ProfessionCode1865050285");
            _returnPersonData.setRetain(Boolean.valueOf(true));
            _returnPersonData.setRetainResponse("RetainResponse2119548602");
            _return.setPersonData(_returnPersonData);
            ArrayOfRiskTypeElement _returnRiskTypeArray = new ArrayOfRiskTypeElement();
            java.util.List<com.scortelemed.schemas.enginyers.RiskTypeElement> _returnRiskTypeArrayRiskTypeElement = new java.util.ArrayList<com.scortelemed.schemas.enginyers.RiskTypeElement>();
            com.scortelemed.schemas.enginyers.RiskTypeElement _returnRiskTypeArrayRiskTypeElementVal1 = new com.scortelemed.schemas.enginyers.RiskTypeElement();
            _returnRiskTypeArrayRiskTypeElementVal1.setIdRisk(-119464525);
            _returnRiskTypeArrayRiskTypeElementVal1.setRiskName("RiskName-1980828455");
            _returnRiskTypeArrayRiskTypeElementVal1.setRiskValue(0.25736022423876237);
            RiskSelectionElement _returnRiskTypeArrayRiskTypeElementVal1RiskSelection = new RiskSelectionElement();
            _returnRiskTypeArrayRiskTypeElementVal1RiskSelection.setRetain(false);
            _returnRiskTypeArrayRiskTypeElementVal1RiskSelection.setRetainResponse("RetainResponse84865329");
            _returnRiskTypeArrayRiskTypeElementVal1RiskSelection.setOverchargeMotive("OverchargeMotive-1531006786");
            _returnRiskTypeArrayRiskTypeElementVal1RiskSelection.setPremiumLoadings(0.8264851635413825);
            _returnRiskTypeArrayRiskTypeElementVal1RiskSelection.setExtraPremiumLoadings(0.1443966373995328);
            _returnRiskTypeArrayRiskTypeElementVal1RiskSelection.setRiskSelectionComment("RiskSelectionComment1219208874");
            ArrayOfExclusionsElement _returnRiskTypeArrayRiskTypeElementVal1RiskSelectionExclusions = new ArrayOfExclusionsElement();
            java.util.List<ExclusionElement> _returnRiskTypeArrayRiskTypeElementVal1RiskSelectionExclusionsExclusion = new java.util.ArrayList<ExclusionElement>();
            _returnRiskTypeArrayRiskTypeElementVal1RiskSelectionExclusions.getExclusion().addAll(_returnRiskTypeArrayRiskTypeElementVal1RiskSelectionExclusionsExclusion);
            _returnRiskTypeArrayRiskTypeElementVal1RiskSelection.setExclusions(_returnRiskTypeArrayRiskTypeElementVal1RiskSelectionExclusions);
            _returnRiskTypeArrayRiskTypeElementVal1.setRiskSelection(_returnRiskTypeArrayRiskTypeElementVal1RiskSelection);
            _returnRiskTypeArrayRiskTypeElement.add(_returnRiskTypeArrayRiskTypeElementVal1);
            _returnRiskTypeArray.getRiskTypeElement().addAll(_returnRiskTypeArrayRiskTypeElement);
            _return.setRiskTypeArray(_returnRiskTypeArray);
            ArrayOfGroups _returnQuestionsArray = new ArrayOfGroups();
            java.util.List<com.scortelemed.schemas.enginyers.GroupElement> _returnQuestionsArrayGroupElement = new java.util.ArrayList<com.scortelemed.schemas.enginyers.GroupElement>();
            com.scortelemed.schemas.enginyers.GroupElement _returnQuestionsArrayGroupElementVal1 = new com.scortelemed.schemas.enginyers.GroupElement();
            _returnQuestionsArrayGroupElementVal1.setNumber(-1520548319);
            _returnQuestionsArrayGroupElementVal1.setTitle("Title-1174343810");
            ArrayOfQuestionsElement _returnQuestionsArrayGroupElementVal1QuestionElementArray = new ArrayOfQuestionsElement();
            java.util.List<QuestionsElement> _returnQuestionsArrayGroupElementVal1QuestionElementArrayQuestionsElement = new java.util.ArrayList<QuestionsElement>();
            _returnQuestionsArrayGroupElementVal1QuestionElementArray.getQuestionsElement().addAll(_returnQuestionsArrayGroupElementVal1QuestionElementArrayQuestionsElement);
            _returnQuestionsArrayGroupElementVal1.setQuestionElementArray(_returnQuestionsArrayGroupElementVal1QuestionElementArray);
            _returnQuestionsArrayGroupElement.add(_returnQuestionsArrayGroupElementVal1);
            _returnQuestionsArray.getGroupElement().addAll(_returnQuestionsArrayGroupElement);
            _return.setQuestionsArray(_returnQuestionsArray);
            SurveyAdditionalFields _returnAdditional = new SurveyAdditionalFields();
            java.util.List<AdditionalFieldElement> _returnAdditionalAdditionalField = new java.util.ArrayList<AdditionalFieldElement>();
            AdditionalFieldElement _returnAdditionalAdditionalFieldVal1 = new AdditionalFieldElement();
            _returnAdditionalAdditionalFieldVal1.setName("Name714117255");
            _returnAdditionalAdditionalFieldVal1.setValue("Value635235166");
            _returnAdditionalAdditionalField.add(_returnAdditionalAdditionalFieldVal1);
            _returnAdditional.getAdditionalField().addAll(_returnAdditionalAdditionalField);
            _return.setAdditional(_returnAdditional);
            ArrayOfFaultElement _returnFaultArray = new ArrayOfFaultElement();
            java.util.List<com.scortelemed.schemas.enginyers.FaultElement> _returnFaultArrayFaultElement = new java.util.ArrayList<com.scortelemed.schemas.enginyers.FaultElement>();
            com.scortelemed.schemas.enginyers.FaultElement _returnFaultArrayFaultElementVal1 = new com.scortelemed.schemas.enginyers.FaultElement();
            _returnFaultArrayFaultElementVal1.setFaultCode("FaultCode1763292782");
            _returnFaultArrayFaultElementVal1.setFaultString("FaultString1372737755");
            _returnFaultArrayFaultElementVal1.setFaultActor("FaultActor-810418422");
            ErrorElement _returnFaultArrayFaultElementVal1Detail = new ErrorElement();
            _returnFaultArrayFaultElementVal1Detail.setErrorNumber(647635341);
            _returnFaultArrayFaultElementVal1Detail.setErrorMessage("ErrorMessage1554536325");
            _returnFaultArrayFaultElementVal1Detail.setErrorSource("ErrorSource1781391864");
            _returnFaultArrayFaultElementVal1.setDetail(_returnFaultArrayFaultElementVal1Detail);
            _returnFaultArrayFaultElement.add(_returnFaultArrayFaultElementVal1);
            _returnFaultArray.getFaultElement().addAll(_returnFaultArrayFaultElement);
            _return.setFaultArray(_returnFaultArray);
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.scortelemed.schemas.enginyers.GestionReconocimientosMedicosService#addExp(com.scortelemed.schemas.enginyers.SurveyData  d ,)com.scortelemed.schemas.enginyers.ArrayOfRiskTypeElement  risks ,)com.scortelemed.schemas.enginyers.SurveyGeneralProperties  gen ,)com.scortelemed.schemas.enginyers.SurveyAdditionalFields  additional )*
     */
    public Expedient addExp(SurveyData d, ArrayOfRiskTypeElement risks, com.scortelemed.schemas.enginyers.SurveyGeneralProperties gen, SurveyAdditionalFields additional) {
        LOG.info("Executing operation addExp");
        System.out.println(d);
        System.out.println(risks);
        System.out.println(gen);
        System.out.println(additional);
        try {
            Expedient _return = new Expedient();
            _return.setAddExpResultCode(278975472);
            _return.setIdExpedient(Integer.valueOf(968067429));
            ArrayOfFaultElement _returnFaultArray = new ArrayOfFaultElement();
            java.util.List<com.scortelemed.schemas.enginyers.FaultElement> _returnFaultArrayFaultElement = new java.util.ArrayList<com.scortelemed.schemas.enginyers.FaultElement>();
            com.scortelemed.schemas.enginyers.FaultElement _returnFaultArrayFaultElementVal1 = new com.scortelemed.schemas.enginyers.FaultElement();
            _returnFaultArrayFaultElementVal1.setFaultCode("FaultCode151848914");
            _returnFaultArrayFaultElementVal1.setFaultString("FaultString-805483117");
            _returnFaultArrayFaultElementVal1.setFaultActor("FaultActor-416681955");
            ErrorElement _returnFaultArrayFaultElementVal1Detail = new ErrorElement();
            _returnFaultArrayFaultElementVal1Detail.setErrorNumber(-2136664987);
            _returnFaultArrayFaultElementVal1Detail.setErrorMessage("ErrorMessage1532260751");
            _returnFaultArrayFaultElementVal1Detail.setErrorSource("ErrorSource1339753986");
            _returnFaultArrayFaultElementVal1.setDetail(_returnFaultArrayFaultElementVal1Detail);
            _returnFaultArrayFaultElement.add(_returnFaultArrayFaultElementVal1);
            _returnFaultArray.getFaultElement().addAll(_returnFaultArrayFaultElement);
            _return.setFaultArray(_returnFaultArray);
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.scortelemed.schemas.enginyers.GestionReconocimientosMedicosService#addSurveyFromExp(long  expId )*
     */
    public Survey addSurveyFromExp(long expId) {
        LOG.info("Executing operation addSurveyFromExp");
        System.out.println(expId);
        try {
            Survey _return = new Survey();
            _return.setSurveyNumber(1183644104);
            com.scortelemed.schemas.enginyers.SurveyGeneralProperties _returnGeneralData = new com.scortelemed.schemas.enginyers.SurveyGeneralProperties();
            _returnGeneralData.setProduct("Product-900692996");
            _returnGeneralData.setBonsaiVersion("BonsaiVersion-1802801506");
            _returnGeneralData.setCompanyCode(521879160);
            _returnGeneralData.setLang("Lang-1494116751");
            _return.setGeneralData(_returnGeneralData);
            SurveyData _returnPersonData = new SurveyData();
            _returnPersonData.setName("Name1256738416");
            _returnPersonData.setSurname("Surname1553421720");
            _returnPersonData.setNif("Nif-1651198842");
            _returnPersonData.setBirthDate("BirthDate715247634");
            GenderType _returnPersonDataGender = GenderType.M;
            _returnPersonData.setGender(_returnPersonDataGender);
            _returnPersonData.setTown("Town-761428955");
            _returnPersonData.setCity("City-1251078683");
            _returnPersonData.setPostalCode("PostalCode1399396756");
            _returnPersonData.setCountry("Country-1908375986");
            _returnPersonData.setNationality("Nationality-492258675");
            _returnPersonData.setPhone("Phone-1489187214");
            _returnPersonData.setCellPhone("CellPhone8038020");
            _returnPersonData.setEmail("Email446221302");
            _returnPersonData.setAddress("Address-602923889");
            _returnPersonData.setPolicyNumber("PolicyNumber974072441");
            _returnPersonData.setProfessionCode("ProfessionCode-2076636666");
            _returnPersonData.setRetain(Boolean.valueOf(false));
            _returnPersonData.setRetainResponse("RetainResponse1477241713");
            _return.setPersonData(_returnPersonData);
            ArrayOfRiskTypeElement _returnRiskTypeArray = new ArrayOfRiskTypeElement();
            java.util.List<com.scortelemed.schemas.enginyers.RiskTypeElement> _returnRiskTypeArrayRiskTypeElement = new java.util.ArrayList<com.scortelemed.schemas.enginyers.RiskTypeElement>();
            com.scortelemed.schemas.enginyers.RiskTypeElement _returnRiskTypeArrayRiskTypeElementVal1 = new com.scortelemed.schemas.enginyers.RiskTypeElement();
            _returnRiskTypeArrayRiskTypeElementVal1.setIdRisk(1355430197);
            _returnRiskTypeArrayRiskTypeElementVal1.setRiskName("RiskName-396078839");
            _returnRiskTypeArrayRiskTypeElementVal1.setRiskValue(0.8838675376703808);
            RiskSelectionElement _returnRiskTypeArrayRiskTypeElementVal1RiskSelection = new RiskSelectionElement();
            _returnRiskTypeArrayRiskTypeElementVal1RiskSelection.setRetain(true);
            _returnRiskTypeArrayRiskTypeElementVal1RiskSelection.setRetainResponse("RetainResponse1037241276");
            _returnRiskTypeArrayRiskTypeElementVal1RiskSelection.setOverchargeMotive("OverchargeMotive-1746298380");
            _returnRiskTypeArrayRiskTypeElementVal1RiskSelection.setPremiumLoadings(0.4844316207917061);
            _returnRiskTypeArrayRiskTypeElementVal1RiskSelection.setExtraPremiumLoadings(0.11788904993810057);
            _returnRiskTypeArrayRiskTypeElementVal1RiskSelection.setRiskSelectionComment("RiskSelectionComment-2054700081");
            ArrayOfExclusionsElement _returnRiskTypeArrayRiskTypeElementVal1RiskSelectionExclusions = new ArrayOfExclusionsElement();
            java.util.List<ExclusionElement> _returnRiskTypeArrayRiskTypeElementVal1RiskSelectionExclusionsExclusion = new java.util.ArrayList<ExclusionElement>();
            _returnRiskTypeArrayRiskTypeElementVal1RiskSelectionExclusions.getExclusion().addAll(_returnRiskTypeArrayRiskTypeElementVal1RiskSelectionExclusionsExclusion);
            _returnRiskTypeArrayRiskTypeElementVal1RiskSelection.setExclusions(_returnRiskTypeArrayRiskTypeElementVal1RiskSelectionExclusions);
            _returnRiskTypeArrayRiskTypeElementVal1.setRiskSelection(_returnRiskTypeArrayRiskTypeElementVal1RiskSelection);
            _returnRiskTypeArrayRiskTypeElement.add(_returnRiskTypeArrayRiskTypeElementVal1);
            _returnRiskTypeArray.getRiskTypeElement().addAll(_returnRiskTypeArrayRiskTypeElement);
            _return.setRiskTypeArray(_returnRiskTypeArray);
            ArrayOfGroups _returnQuestionsArray = new ArrayOfGroups();
            java.util.List<com.scortelemed.schemas.enginyers.GroupElement> _returnQuestionsArrayGroupElement = new java.util.ArrayList<com.scortelemed.schemas.enginyers.GroupElement>();
            com.scortelemed.schemas.enginyers.GroupElement _returnQuestionsArrayGroupElementVal1 = new com.scortelemed.schemas.enginyers.GroupElement();
            _returnQuestionsArrayGroupElementVal1.setNumber(842810855);
            _returnQuestionsArrayGroupElementVal1.setTitle("Title1231900830");
            ArrayOfQuestionsElement _returnQuestionsArrayGroupElementVal1QuestionElementArray = new ArrayOfQuestionsElement();
            java.util.List<QuestionsElement> _returnQuestionsArrayGroupElementVal1QuestionElementArrayQuestionsElement = new java.util.ArrayList<QuestionsElement>();
            _returnQuestionsArrayGroupElementVal1QuestionElementArray.getQuestionsElement().addAll(_returnQuestionsArrayGroupElementVal1QuestionElementArrayQuestionsElement);
            _returnQuestionsArrayGroupElementVal1.setQuestionElementArray(_returnQuestionsArrayGroupElementVal1QuestionElementArray);
            _returnQuestionsArrayGroupElement.add(_returnQuestionsArrayGroupElementVal1);
            _returnQuestionsArray.getGroupElement().addAll(_returnQuestionsArrayGroupElement);
            _return.setQuestionsArray(_returnQuestionsArray);
            SurveyAdditionalFields _returnAdditional = new SurveyAdditionalFields();
            java.util.List<AdditionalFieldElement> _returnAdditionalAdditionalField = new java.util.ArrayList<AdditionalFieldElement>();
            AdditionalFieldElement _returnAdditionalAdditionalFieldVal1 = new AdditionalFieldElement();
            _returnAdditionalAdditionalFieldVal1.setName("Name-28550031");
            _returnAdditionalAdditionalFieldVal1.setValue("Value997632110");
            _returnAdditionalAdditionalField.add(_returnAdditionalAdditionalFieldVal1);
            _returnAdditional.getAdditionalField().addAll(_returnAdditionalAdditionalField);
            _return.setAdditional(_returnAdditional);
            ArrayOfFaultElement _returnFaultArray = new ArrayOfFaultElement();
            java.util.List<com.scortelemed.schemas.enginyers.FaultElement> _returnFaultArrayFaultElement = new java.util.ArrayList<com.scortelemed.schemas.enginyers.FaultElement>();
            com.scortelemed.schemas.enginyers.FaultElement _returnFaultArrayFaultElementVal1 = new com.scortelemed.schemas.enginyers.FaultElement();
            _returnFaultArrayFaultElementVal1.setFaultCode("FaultCode1828587678");
            _returnFaultArrayFaultElementVal1.setFaultString("FaultString-1320040966");
            _returnFaultArrayFaultElementVal1.setFaultActor("FaultActor1013071270");
            ErrorElement _returnFaultArrayFaultElementVal1Detail = new ErrorElement();
            _returnFaultArrayFaultElementVal1Detail.setErrorNumber(-282694760);
            _returnFaultArrayFaultElementVal1Detail.setErrorMessage("ErrorMessage-1386745901");
            _returnFaultArrayFaultElementVal1Detail.setErrorSource("ErrorSource-234691832");
            _returnFaultArrayFaultElementVal1.setDetail(_returnFaultArrayFaultElementVal1Detail);
            _returnFaultArrayFaultElement.add(_returnFaultArrayFaultElementVal1);
            _returnFaultArray.getFaultElement().addAll(_returnFaultArrayFaultElement);
            _return.setFaultArray(_returnFaultArray);
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
