
package com.scortelemed.schemas.enginyers;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.1
 * Mon Feb 04 15:37:02 CET 2019
 * Generated source version: 2.1
 * 
 */

public final class GestionReconocimientosMedicosService_GestionReconocimientosMedicosServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://www.scortelemed.com/schemas/enginyers", "GestionReconocimientosMedicosServiceService");

    private GestionReconocimientosMedicosService_GestionReconocimientosMedicosServicePort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = GestionReconocimientosMedicosServiceService.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        GestionReconocimientosMedicosServiceService ss = new GestionReconocimientosMedicosServiceService(wsdlURL, SERVICE_NAME);
        GestionReconocimientosMedicosService port = ss.getGestionReconocimientosMedicosServicePort();  
        
        {
        System.out.println("Invoking updateSurvey...");
        long _updateSurvey_surveyNumber = 8242922428020625622l;
        com.scortelemed.schemas.enginyers.SurveyData _updateSurvey_d = new com.scortelemed.schemas.enginyers.SurveyData();
        _updateSurvey_d.setName("Name36679843");
        _updateSurvey_d.setSurname("Surname878475428");
        _updateSurvey_d.setNif("Nif-399807371");
        _updateSurvey_d.setBirthDate("BirthDate-1402324068");
        com.scortelemed.schemas.enginyers.GenderType _updateSurvey_dGender = com.scortelemed.schemas.enginyers.GenderType.M;
        _updateSurvey_d.setGender(_updateSurvey_dGender);
        _updateSurvey_d.setTown("Town-1543409540");
        _updateSurvey_d.setCity("City2131815279");
        _updateSurvey_d.setPostalCode("PostalCode1099075959");
        _updateSurvey_d.setCountry("Country-1545837027");
        _updateSurvey_d.setNationality("Nationality-136976656");
        _updateSurvey_d.setPhone("Phone1561559747");
        _updateSurvey_d.setCellPhone("CellPhone1209575393");
        _updateSurvey_d.setEmail("Email-859449268");
        _updateSurvey_d.setAddress("Address114253884");
        _updateSurvey_d.setPolicyNumber("PolicyNumber-1382483454");
        _updateSurvey_d.setProfessionCode("ProfessionCode1197316807");
        _updateSurvey_d.setRetain(Boolean.valueOf(false));
        _updateSurvey_d.setRetainResponse("RetainResponse1634278198");
        ArrayOfRiskTypeElement _updateSurvey_risks = new ArrayOfRiskTypeElement();
        java.util.List<com.scortelemed.schemas.enginyers.RiskTypeElement> _updateSurvey_risksRiskTypeElement = new java.util.ArrayList<com.scortelemed.schemas.enginyers.RiskTypeElement>();
        com.scortelemed.schemas.enginyers.RiskTypeElement _updateSurvey_risksRiskTypeElementVal1 = new com.scortelemed.schemas.enginyers.RiskTypeElement();
        _updateSurvey_risksRiskTypeElementVal1.setIdRisk(747269796);
        _updateSurvey_risksRiskTypeElementVal1.setRiskName("RiskName1767765664");
        _updateSurvey_risksRiskTypeElementVal1.setRiskValue(0.5370570222723602);
        com.scortelemed.schemas.enginyers.RiskSelectionElement _updateSurvey_risksRiskTypeElementVal1RiskSelection = new com.scortelemed.schemas.enginyers.RiskSelectionElement();
        _updateSurvey_risksRiskTypeElementVal1RiskSelection.setRetain(false);
        _updateSurvey_risksRiskTypeElementVal1RiskSelection.setRetainResponse("RetainResponse-70078527");
        _updateSurvey_risksRiskTypeElementVal1RiskSelection.setOverchargeMotive("OverchargeMotive-1244901633");
        _updateSurvey_risksRiskTypeElementVal1RiskSelection.setPremiumLoadings(0.40871637735601707);
        _updateSurvey_risksRiskTypeElementVal1RiskSelection.setExtraPremiumLoadings(0.09463089314852935);
        _updateSurvey_risksRiskTypeElementVal1RiskSelection.setRiskSelectionComment("RiskSelectionComment817368664");
        ArrayOfExclusionsElement _updateSurvey_risksRiskTypeElementVal1RiskSelectionExclusions = new ArrayOfExclusionsElement();
        java.util.List<ExclusionElement> _updateSurvey_risksRiskTypeElementVal1RiskSelectionExclusionsExclusion = new java.util.ArrayList<ExclusionElement>();
        _updateSurvey_risksRiskTypeElementVal1RiskSelectionExclusions.getExclusion().addAll(_updateSurvey_risksRiskTypeElementVal1RiskSelectionExclusionsExclusion);
        _updateSurvey_risksRiskTypeElementVal1RiskSelection.setExclusions(_updateSurvey_risksRiskTypeElementVal1RiskSelectionExclusions);
        _updateSurvey_risksRiskTypeElementVal1.setRiskSelection(_updateSurvey_risksRiskTypeElementVal1RiskSelection);
        _updateSurvey_risksRiskTypeElement.add(_updateSurvey_risksRiskTypeElementVal1);
        _updateSurvey_risks.getRiskTypeElement().addAll(_updateSurvey_risksRiskTypeElement);
        com.scortelemed.schemas.enginyers.SurveyGeneralProperties _updateSurvey_gen = new com.scortelemed.schemas.enginyers.SurveyGeneralProperties();
        _updateSurvey_gen.setProduct("Product-456837462");
        _updateSurvey_gen.setBonsaiVersion("BonsaiVersion-209249483");
        _updateSurvey_gen.setCompanyCode(-1145586319);
        _updateSurvey_gen.setLang("Lang-2070722182");
        ArrayOfGroups _updateSurvey_questionsArray = new ArrayOfGroups();
        java.util.List<com.scortelemed.schemas.enginyers.GroupElement> _updateSurvey_questionsArrayGroupElement = new java.util.ArrayList<com.scortelemed.schemas.enginyers.GroupElement>();
        com.scortelemed.schemas.enginyers.GroupElement _updateSurvey_questionsArrayGroupElementVal1 = new com.scortelemed.schemas.enginyers.GroupElement();
        _updateSurvey_questionsArrayGroupElementVal1.setNumber(198601121);
        _updateSurvey_questionsArrayGroupElementVal1.setTitle("Title-914851592");
        com.scortelemed.schemas.enginyers.ArrayOfQuestionsElement _updateSurvey_questionsArrayGroupElementVal1QuestionElementArray = new com.scortelemed.schemas.enginyers.ArrayOfQuestionsElement();
        java.util.List<com.scortelemed.schemas.enginyers.QuestionsElement> _updateSurvey_questionsArrayGroupElementVal1QuestionElementArrayQuestionsElement = new java.util.ArrayList<com.scortelemed.schemas.enginyers.QuestionsElement>();
        _updateSurvey_questionsArrayGroupElementVal1QuestionElementArray.getQuestionsElement().addAll(_updateSurvey_questionsArrayGroupElementVal1QuestionElementArrayQuestionsElement);
        _updateSurvey_questionsArrayGroupElementVal1.setQuestionElementArray(_updateSurvey_questionsArrayGroupElementVal1QuestionElementArray);
        _updateSurvey_questionsArrayGroupElement.add(_updateSurvey_questionsArrayGroupElementVal1);
        _updateSurvey_questionsArray.getGroupElement().addAll(_updateSurvey_questionsArrayGroupElement);
        SurveyAdditionalFields _updateSurvey_additional = new SurveyAdditionalFields();
        java.util.List<AdditionalFieldElement> _updateSurvey_additionalAdditionalField = new java.util.ArrayList<AdditionalFieldElement>();
        AdditionalFieldElement _updateSurvey_additionalAdditionalFieldVal1 = new AdditionalFieldElement();
        _updateSurvey_additionalAdditionalFieldVal1.setName("Name-261295805");
        _updateSurvey_additionalAdditionalFieldVal1.setValue("Value1361628709");
        _updateSurvey_additionalAdditionalField.add(_updateSurvey_additionalAdditionalFieldVal1);
        _updateSurvey_additional.getAdditionalField().addAll(_updateSurvey_additionalAdditionalField);
        com.scortelemed.schemas.enginyers.Survey _updateSurvey__return = port.updateSurvey(_updateSurvey_surveyNumber, _updateSurvey_d, _updateSurvey_risks, _updateSurvey_gen, _updateSurvey_questionsArray, _updateSurvey_additional);
        System.out.println("updateSurvey.result=" + _updateSurvey__return);


        }
        {
        System.out.println("Invoking addSurveyExtern...");
        com.scortelemed.schemas.enginyers.SurveyData _addSurveyExtern_d = new com.scortelemed.schemas.enginyers.SurveyData();
        _addSurveyExtern_d.setName("Name104513910");
        _addSurveyExtern_d.setSurname("Surname-979200440");
        _addSurveyExtern_d.setNif("Nif582076891");
        _addSurveyExtern_d.setBirthDate("BirthDate-1147116867");
        com.scortelemed.schemas.enginyers.GenderType _addSurveyExtern_dGender = com.scortelemed.schemas.enginyers.GenderType.F;
        _addSurveyExtern_d.setGender(_addSurveyExtern_dGender);
        _addSurveyExtern_d.setTown("Town-2047789960");
        _addSurveyExtern_d.setCity("City403716186");
        _addSurveyExtern_d.setPostalCode("PostalCode-834597911");
        _addSurveyExtern_d.setCountry("Country-561457121");
        _addSurveyExtern_d.setNationality("Nationality2093432560");
        _addSurveyExtern_d.setPhone("Phone-1783287699");
        _addSurveyExtern_d.setCellPhone("CellPhone416212358");
        _addSurveyExtern_d.setEmail("Email-1637777826");
        _addSurveyExtern_d.setAddress("Address1299599168");
        _addSurveyExtern_d.setPolicyNumber("PolicyNumber980278481");
        _addSurveyExtern_d.setProfessionCode("ProfessionCode-533129506");
        _addSurveyExtern_d.setRetain(Boolean.valueOf(true));
        _addSurveyExtern_d.setRetainResponse("RetainResponse1235345017");
        ArrayOfRiskTypeElement _addSurveyExtern_risks = new ArrayOfRiskTypeElement();
        java.util.List<com.scortelemed.schemas.enginyers.RiskTypeElement> _addSurveyExtern_risksRiskTypeElement = new java.util.ArrayList<com.scortelemed.schemas.enginyers.RiskTypeElement>();
        com.scortelemed.schemas.enginyers.RiskTypeElement _addSurveyExtern_risksRiskTypeElementVal1 = new com.scortelemed.schemas.enginyers.RiskTypeElement();
        _addSurveyExtern_risksRiskTypeElementVal1.setIdRisk(1369774105);
        _addSurveyExtern_risksRiskTypeElementVal1.setRiskName("RiskName-71936487");
        _addSurveyExtern_risksRiskTypeElementVal1.setRiskValue(0.9536950305672957);
        com.scortelemed.schemas.enginyers.RiskSelectionElement _addSurveyExtern_risksRiskTypeElementVal1RiskSelection = new com.scortelemed.schemas.enginyers.RiskSelectionElement();
        _addSurveyExtern_risksRiskTypeElementVal1RiskSelection.setRetain(true);
        _addSurveyExtern_risksRiskTypeElementVal1RiskSelection.setRetainResponse("RetainResponse-1671319821");
        _addSurveyExtern_risksRiskTypeElementVal1RiskSelection.setOverchargeMotive("OverchargeMotive-367526781");
        _addSurveyExtern_risksRiskTypeElementVal1RiskSelection.setPremiumLoadings(0.8273391858088308);
        _addSurveyExtern_risksRiskTypeElementVal1RiskSelection.setExtraPremiumLoadings(0.5598221124664455);
        _addSurveyExtern_risksRiskTypeElementVal1RiskSelection.setRiskSelectionComment("RiskSelectionComment-1250662569");
        ArrayOfExclusionsElement _addSurveyExtern_risksRiskTypeElementVal1RiskSelectionExclusions = new ArrayOfExclusionsElement();
        java.util.List<ExclusionElement> _addSurveyExtern_risksRiskTypeElementVal1RiskSelectionExclusionsExclusion = new java.util.ArrayList<ExclusionElement>();
        _addSurveyExtern_risksRiskTypeElementVal1RiskSelectionExclusions.getExclusion().addAll(_addSurveyExtern_risksRiskTypeElementVal1RiskSelectionExclusionsExclusion);
        _addSurveyExtern_risksRiskTypeElementVal1RiskSelection.setExclusions(_addSurveyExtern_risksRiskTypeElementVal1RiskSelectionExclusions);
        _addSurveyExtern_risksRiskTypeElementVal1.setRiskSelection(_addSurveyExtern_risksRiskTypeElementVal1RiskSelection);
        _addSurveyExtern_risksRiskTypeElement.add(_addSurveyExtern_risksRiskTypeElementVal1);
        _addSurveyExtern_risks.getRiskTypeElement().addAll(_addSurveyExtern_risksRiskTypeElement);
        com.scortelemed.schemas.enginyers.SurveyGeneralProperties _addSurveyExtern_gen = new com.scortelemed.schemas.enginyers.SurveyGeneralProperties();
        _addSurveyExtern_gen.setProduct("Product524364155");
        _addSurveyExtern_gen.setBonsaiVersion("BonsaiVersion-600447157");
        _addSurveyExtern_gen.setCompanyCode(-1289066474);
        _addSurveyExtern_gen.setLang("Lang-1560455423");
        SurveyAdditionalFields _addSurveyExtern_additional = new SurveyAdditionalFields();
        java.util.List<AdditionalFieldElement> _addSurveyExtern_additionalAdditionalField = new java.util.ArrayList<AdditionalFieldElement>();
        AdditionalFieldElement _addSurveyExtern_additionalAdditionalFieldVal1 = new AdditionalFieldElement();
        _addSurveyExtern_additionalAdditionalFieldVal1.setName("Name-1545230493");
        _addSurveyExtern_additionalAdditionalFieldVal1.setValue("Value859243508");
        _addSurveyExtern_additionalAdditionalField.add(_addSurveyExtern_additionalAdditionalFieldVal1);
        _addSurveyExtern_additional.getAdditionalField().addAll(_addSurveyExtern_additionalAdditionalField);
        com.scortelemed.schemas.enginyers.Peticio _addSurveyExtern__return = port.addSurveyExtern(_addSurveyExtern_d, _addSurveyExtern_risks, _addSurveyExtern_gen, _addSurveyExtern_additional);
        System.out.println("addSurveyExtern.result=" + _addSurveyExtern__return);


        }
        {
        System.out.println("Invoking addSurvey...");
        com.scortelemed.schemas.enginyers.SurveyData _addSurvey_d = new com.scortelemed.schemas.enginyers.SurveyData();
        _addSurvey_d.setName("Name-1673504974");
        _addSurvey_d.setSurname("Surname898183468");
        _addSurvey_d.setNif("Nif654142147");
        _addSurvey_d.setBirthDate("BirthDate1591138491");
        com.scortelemed.schemas.enginyers.GenderType _addSurvey_dGender = com.scortelemed.schemas.enginyers.GenderType.F;
        _addSurvey_d.setGender(_addSurvey_dGender);
        _addSurvey_d.setTown("Town-1615071813");
        _addSurvey_d.setCity("City1850260282");
        _addSurvey_d.setPostalCode("PostalCode-904418423");
        _addSurvey_d.setCountry("Country-1925701604");
        _addSurvey_d.setNationality("Nationality-1429544872");
        _addSurvey_d.setPhone("Phone-1172560744");
        _addSurvey_d.setCellPhone("CellPhone979051600");
        _addSurvey_d.setEmail("Email303171113");
        _addSurvey_d.setAddress("Address-1743334451");
        _addSurvey_d.setPolicyNumber("PolicyNumber1509794209");
        _addSurvey_d.setProfessionCode("ProfessionCode-1352033661");
        _addSurvey_d.setRetain(Boolean.valueOf(false));
        _addSurvey_d.setRetainResponse("RetainResponse-391010670");
        ArrayOfRiskTypeElement _addSurvey_risks = new ArrayOfRiskTypeElement();
        java.util.List<com.scortelemed.schemas.enginyers.RiskTypeElement> _addSurvey_risksRiskTypeElement = new java.util.ArrayList<com.scortelemed.schemas.enginyers.RiskTypeElement>();
        com.scortelemed.schemas.enginyers.RiskTypeElement _addSurvey_risksRiskTypeElementVal1 = new com.scortelemed.schemas.enginyers.RiskTypeElement();
        _addSurvey_risksRiskTypeElementVal1.setIdRisk(1403203344);
        _addSurvey_risksRiskTypeElementVal1.setRiskName("RiskName899433927");
        _addSurvey_risksRiskTypeElementVal1.setRiskValue(0.7618299579524189);
        com.scortelemed.schemas.enginyers.RiskSelectionElement _addSurvey_risksRiskTypeElementVal1RiskSelection = new com.scortelemed.schemas.enginyers.RiskSelectionElement();
        _addSurvey_risksRiskTypeElementVal1RiskSelection.setRetain(false);
        _addSurvey_risksRiskTypeElementVal1RiskSelection.setRetainResponse("RetainResponse-1918024214");
        _addSurvey_risksRiskTypeElementVal1RiskSelection.setOverchargeMotive("OverchargeMotive-195901890");
        _addSurvey_risksRiskTypeElementVal1RiskSelection.setPremiumLoadings(0.8368508039543803);
        _addSurvey_risksRiskTypeElementVal1RiskSelection.setExtraPremiumLoadings(0.30633105250406545);
        _addSurvey_risksRiskTypeElementVal1RiskSelection.setRiskSelectionComment("RiskSelectionComment852557322");
        ArrayOfExclusionsElement _addSurvey_risksRiskTypeElementVal1RiskSelectionExclusions = new ArrayOfExclusionsElement();
        java.util.List<ExclusionElement> _addSurvey_risksRiskTypeElementVal1RiskSelectionExclusionsExclusion = new java.util.ArrayList<ExclusionElement>();
        _addSurvey_risksRiskTypeElementVal1RiskSelectionExclusions.getExclusion().addAll(_addSurvey_risksRiskTypeElementVal1RiskSelectionExclusionsExclusion);
        _addSurvey_risksRiskTypeElementVal1RiskSelection.setExclusions(_addSurvey_risksRiskTypeElementVal1RiskSelectionExclusions);
        _addSurvey_risksRiskTypeElementVal1.setRiskSelection(_addSurvey_risksRiskTypeElementVal1RiskSelection);
        _addSurvey_risksRiskTypeElement.add(_addSurvey_risksRiskTypeElementVal1);
        _addSurvey_risks.getRiskTypeElement().addAll(_addSurvey_risksRiskTypeElement);
        com.scortelemed.schemas.enginyers.SurveyGeneralProperties _addSurvey_gen = new com.scortelemed.schemas.enginyers.SurveyGeneralProperties();
        _addSurvey_gen.setProduct("Product1223261437");
        _addSurvey_gen.setBonsaiVersion("BonsaiVersion1841381179");
        _addSurvey_gen.setCompanyCode(-98688589);
        _addSurvey_gen.setLang("Lang-140638490");
        SurveyAdditionalFields _addSurvey_additional = new SurveyAdditionalFields();
        java.util.List<AdditionalFieldElement> _addSurvey_additionalAdditionalField = new java.util.ArrayList<AdditionalFieldElement>();
        AdditionalFieldElement _addSurvey_additionalAdditionalFieldVal1 = new AdditionalFieldElement();
        _addSurvey_additionalAdditionalFieldVal1.setName("Name2085849679");
        _addSurvey_additionalAdditionalFieldVal1.setValue("Value-2091262500");
        _addSurvey_additionalAdditionalField.add(_addSurvey_additionalAdditionalFieldVal1);
        _addSurvey_additional.getAdditionalField().addAll(_addSurvey_additionalAdditionalField);
        com.scortelemed.schemas.enginyers.Survey _addSurvey__return = port.addSurvey(_addSurvey_d, _addSurvey_risks, _addSurvey_gen, _addSurvey_additional);
        System.out.println("addSurvey.result=" + _addSurvey__return);


        }
        {
        System.out.println("Invoking addExp...");
        com.scortelemed.schemas.enginyers.SurveyData _addExp_d = new com.scortelemed.schemas.enginyers.SurveyData();
        _addExp_d.setName("Name-706289074");
        _addExp_d.setSurname("Surname-2036478320");
        _addExp_d.setNif("Nif-1572157364");
        _addExp_d.setBirthDate("BirthDate521522919");
        com.scortelemed.schemas.enginyers.GenderType _addExp_dGender = com.scortelemed.schemas.enginyers.GenderType.M;
        _addExp_d.setGender(_addExp_dGender);
        _addExp_d.setTown("Town527845327");
        _addExp_d.setCity("City94049493");
        _addExp_d.setPostalCode("PostalCode-210184198");
        _addExp_d.setCountry("Country1758483611");
        _addExp_d.setNationality("Nationality1131357221");
        _addExp_d.setPhone("Phone1749257183");
        _addExp_d.setCellPhone("CellPhone-2016846126");
        _addExp_d.setEmail("Email1548675177");
        _addExp_d.setAddress("Address1453128293");
        _addExp_d.setPolicyNumber("PolicyNumber1341058169");
        _addExp_d.setProfessionCode("ProfessionCode-1983577091");
        _addExp_d.setRetain(Boolean.valueOf(false));
        _addExp_d.setRetainResponse("RetainResponse-998260088");
        ArrayOfRiskTypeElement _addExp_risks = new ArrayOfRiskTypeElement();
        java.util.List<com.scortelemed.schemas.enginyers.RiskTypeElement> _addExp_risksRiskTypeElement = new java.util.ArrayList<com.scortelemed.schemas.enginyers.RiskTypeElement>();
        com.scortelemed.schemas.enginyers.RiskTypeElement _addExp_risksRiskTypeElementVal1 = new com.scortelemed.schemas.enginyers.RiskTypeElement();
        _addExp_risksRiskTypeElementVal1.setIdRisk(2017805);
        _addExp_risksRiskTypeElementVal1.setRiskName("RiskName-2097695532");
        _addExp_risksRiskTypeElementVal1.setRiskValue(0.6458386491823896);
        com.scortelemed.schemas.enginyers.RiskSelectionElement _addExp_risksRiskTypeElementVal1RiskSelection = new com.scortelemed.schemas.enginyers.RiskSelectionElement();
        _addExp_risksRiskTypeElementVal1RiskSelection.setRetain(false);
        _addExp_risksRiskTypeElementVal1RiskSelection.setRetainResponse("RetainResponse-1256363864");
        _addExp_risksRiskTypeElementVal1RiskSelection.setOverchargeMotive("OverchargeMotive1686837051");
        _addExp_risksRiskTypeElementVal1RiskSelection.setPremiumLoadings(0.6056066678401181);
        _addExp_risksRiskTypeElementVal1RiskSelection.setExtraPremiumLoadings(0.6983335720341015);
        _addExp_risksRiskTypeElementVal1RiskSelection.setRiskSelectionComment("RiskSelectionComment-962874740");
        ArrayOfExclusionsElement _addExp_risksRiskTypeElementVal1RiskSelectionExclusions = new ArrayOfExclusionsElement();
        java.util.List<ExclusionElement> _addExp_risksRiskTypeElementVal1RiskSelectionExclusionsExclusion = new java.util.ArrayList<ExclusionElement>();
        _addExp_risksRiskTypeElementVal1RiskSelectionExclusions.getExclusion().addAll(_addExp_risksRiskTypeElementVal1RiskSelectionExclusionsExclusion);
        _addExp_risksRiskTypeElementVal1RiskSelection.setExclusions(_addExp_risksRiskTypeElementVal1RiskSelectionExclusions);
        _addExp_risksRiskTypeElementVal1.setRiskSelection(_addExp_risksRiskTypeElementVal1RiskSelection);
        _addExp_risksRiskTypeElement.add(_addExp_risksRiskTypeElementVal1);
        _addExp_risks.getRiskTypeElement().addAll(_addExp_risksRiskTypeElement);
        com.scortelemed.schemas.enginyers.SurveyGeneralProperties _addExp_gen = new com.scortelemed.schemas.enginyers.SurveyGeneralProperties();
        _addExp_gen.setProduct("Product321238470");
        _addExp_gen.setBonsaiVersion("BonsaiVersion552986226");
        _addExp_gen.setCompanyCode(-1934800272);
        _addExp_gen.setLang("Lang894610648");
        SurveyAdditionalFields _addExp_additional = new SurveyAdditionalFields();
        java.util.List<AdditionalFieldElement> _addExp_additionalAdditionalField = new java.util.ArrayList<AdditionalFieldElement>();
        AdditionalFieldElement _addExp_additionalAdditionalFieldVal1 = new AdditionalFieldElement();
        _addExp_additionalAdditionalFieldVal1.setName("Name952933098");
        _addExp_additionalAdditionalFieldVal1.setValue("Value318088519");
        _addExp_additionalAdditionalField.add(_addExp_additionalAdditionalFieldVal1);
        _addExp_additional.getAdditionalField().addAll(_addExp_additionalAdditionalField);
        Expedient _addExp__return = port.addExp(_addExp_d, _addExp_risks, _addExp_gen, _addExp_additional);
        System.out.println("addExp.result=" + _addExp__return);


        }
        {
        System.out.println("Invoking addSurveyFromExp...");
        long _addSurveyFromExp_expId = 7722283293349001102l;
        com.scortelemed.schemas.enginyers.Survey _addSurveyFromExp__return = port.addSurveyFromExp(_addSurveyFromExp_expId);
        System.out.println("addSurveyFromExp.result=" + _addSurveyFromExp__return);


        }

        System.exit(0);
    }

}
