
package com.scortelemed.schemas.enginyers;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.1
 * Mon Feb 04 15:37:02 CET 2019
 * Generated source version: 2.1
 * 
 */

@WebService(targetNamespace = "http://www.scortelemed.com/schemas/enginyers", name = "GestionReconocimientosMedicosService")
@XmlSeeAlso({ObjectFactory.class})

public interface GestionReconocimientosMedicosService {

    @WebResult(name = "updateSurveyResult", targetNamespace = "http://www.scortelemed.com/schemas/enginyers")
    @RequestWrapper(localName = "updateSurvey", targetNamespace = "http://www.scortelemed.com/schemas/enginyers", className = "com.scortelemed.schemas.enginyers.UpdateSurvey")
    @ResponseWrapper(localName = "updateSurveyResponse", targetNamespace = "http://www.scortelemed.com/schemas/enginyers", className = "com.scortelemed.schemas.enginyers.UpdateSurveyResponse")
    @WebMethod(action = "http://www.scortelemed.com/schemas/enginyers/updateSurvey")
    public com.scortelemed.schemas.enginyers.Survey updateSurvey(
            @WebParam(name = "surveyNumber", targetNamespace = "http://www.scortelemed.com/schemas/enginyers")
                    long surveyNumber,
            @WebParam(name = "d", targetNamespace = "http://www.scortelemed.com/schemas/enginyers")
                    com.scortelemed.schemas.enginyers.SurveyData d,
            @WebParam(name = "risks", targetNamespace = "http://www.scortelemed.com/schemas/enginyers")
                    com.scortelemed.schemas.enginyers.ArrayOfRiskTypeElement risks,
            @WebParam(name = "gen", targetNamespace = "http://www.scortelemed.com/schemas/enginyers")
                    com.scortelemed.schemas.enginyers.SurveyGeneralProperties gen,
            @WebParam(name = "questionsArray", targetNamespace = "http://www.scortelemed.com/schemas/enginyers")
                    com.scortelemed.schemas.enginyers.ArrayOfGroups questionsArray,
            @WebParam(name = "additional", targetNamespace = "http://www.scortelemed.com/schemas/enginyers")
                    SurveyAdditionalFields additional
    );

    @WebResult(name = "addSurveyExternResult", targetNamespace = "http://www.scortelemed.com/schemas/enginyers")
    @RequestWrapper(localName = "addSurveyExtern", targetNamespace = "http://www.scortelemed.com/schemas/enginyers", className = "com.scortelemed.schemas.enginyers.AddSurveyExtern")
    @ResponseWrapper(localName = "addSurveyExternResponse", targetNamespace = "http://www.scortelemed.com/schemas/enginyers", className = "com.scortelemed.schemas.enginyers.AddSurveyExternResponse")
    @WebMethod(action = "http://www.scortelemed.com/schemas/enginyers/addSurveyExtern")
    public com.scortelemed.schemas.enginyers.Peticio addSurveyExtern(
            @WebParam(name = "d", targetNamespace = "http://www.scortelemed.com/schemas/enginyers")
                    com.scortelemed.schemas.enginyers.SurveyData d,
            @WebParam(name = "risks", targetNamespace = "http://www.scortelemed.com/schemas/enginyers")
                    com.scortelemed.schemas.enginyers.ArrayOfRiskTypeElement risks,
            @WebParam(name = "gen", targetNamespace = "http://www.scortelemed.com/schemas/enginyers")
                    com.scortelemed.schemas.enginyers.SurveyGeneralProperties gen,
            @WebParam(name = "additional", targetNamespace = "http://www.scortelemed.com/schemas/enginyers")
                    SurveyAdditionalFields additional
    );

    @WebResult(name = "addSurveyResult", targetNamespace = "http://www.scortelemed.com/schemas/enginyers")
    @RequestWrapper(localName = "addSurvey", targetNamespace = "http://www.scortelemed.com/schemas/enginyers", className = "com.scortelemed.schemas.enginyers.AddSurvey")
    @ResponseWrapper(localName = "addSurveyResponse", targetNamespace = "http://www.scortelemed.com/schemas/enginyers", className = "com.scortelemed.schemas.enginyers.AddSurveyResponse")
    @WebMethod(action = "http://www.scortelemed.com/schemas/enginyers/addSurvey")
    public com.scortelemed.schemas.enginyers.Survey addSurvey(
            @WebParam(name = "d", targetNamespace = "http://www.scortelemed.com/schemas/enginyers")
                    com.scortelemed.schemas.enginyers.SurveyData d,
            @WebParam(name = "risks", targetNamespace = "http://www.scortelemed.com/schemas/enginyers")
                    com.scortelemed.schemas.enginyers.ArrayOfRiskTypeElement risks,
            @WebParam(name = "gen", targetNamespace = "http://www.scortelemed.com/schemas/enginyers")
                    com.scortelemed.schemas.enginyers.SurveyGeneralProperties gen,
            @WebParam(name = "additional", targetNamespace = "http://www.scortelemed.com/schemas/enginyers")
                    SurveyAdditionalFields additional
    );

    @WebResult(name = "addExpResult", targetNamespace = "http://www.scortelemed.com/schemas/enginyers")
    @RequestWrapper(localName = "addExp", targetNamespace = "http://www.scortelemed.com/schemas/enginyers", className = "com.scortelemed.schemas.enginyers.AddExp")
    @ResponseWrapper(localName = "addExpResponse", targetNamespace = "http://www.scortelemed.com/schemas/enginyers", className = "com.scortelemed.schemas.enginyers.AddExpResponse")
    @WebMethod(action = "http://www.scortelemed.com/schemas/enginyers/addExp")
    public com.scortelemed.schemas.enginyers.Expedient addExp(
            @WebParam(name = "d", targetNamespace = "http://www.scortelemed.com/schemas/enginyers")
                    com.scortelemed.schemas.enginyers.SurveyData d,
            @WebParam(name = "risks", targetNamespace = "http://www.scortelemed.com/schemas/enginyers")
                    com.scortelemed.schemas.enginyers.ArrayOfRiskTypeElement risks,
            @WebParam(name = "gen", targetNamespace = "http://www.scortelemed.com/schemas/enginyers")
                    com.scortelemed.schemas.enginyers.SurveyGeneralProperties gen,
            @WebParam(name = "additional", targetNamespace = "http://www.scortelemed.com/schemas/enginyers")
                    SurveyAdditionalFields additional
    );

    @WebResult(name = "addSurveyFromExpResult", targetNamespace = "http://www.scortelemed.com/schemas/enginyers")
    @RequestWrapper(localName = "addSurveyFromExp", targetNamespace = "http://www.scortelemed.com/schemas/enginyers", className = "com.scortelemed.schemas.enginyers.AddSurveyFromExp")
    @ResponseWrapper(localName = "addSurveyFromExpResponse", targetNamespace = "http://www.scortelemed.com/schemas/enginyers", className = "com.scortelemed.schemas.enginyers.AddSurveyFromExpResponse")
    @WebMethod(action = "http://www.scortelemed.com/schemas/enginyers/addSurveyFromExp")
    public com.scortelemed.schemas.enginyers.Survey addSurveyFromExp(
            @WebParam(name = "expId", targetNamespace = "http://www.scortelemed.com/schemas/enginyers")
                    long expId
    );
}
