
package com.scortelemed.schemas.enginyers;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 2.1
 * Mon Feb 04 15:37:02 CET 2019
 * Generated source version: 2.1
 * 
 */

@WebServiceClient(name = "GestionReconocimientosMedicosServiceService", targetNamespace = "http://www.scortelemed.com/schemas/enginyers", wsdlLocation = "http://localhost:8080/scorWebservice/services/enginyers/GestionReconocimientosMedicos?wsdl")
public class GestionReconocimientosMedicosServiceService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://www.scortelemed.com/schemas/enginyers", "GestionReconocimientosMedicosServiceService");
    public final static QName GestionReconocimientosMedicosServicePort = new QName("http://www.scortelemed.com/schemas/enginyers", "GestionReconocimientosMedicosServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/scorWebservice/services/enginyers/GestionReconocimientosMedicos?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://localhost:8080/scorWebservice/services/enginyers/GestionReconocimientosMedicos?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public GestionReconocimientosMedicosServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public GestionReconocimientosMedicosServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GestionReconocimientosMedicosServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns GestionReconocimientosMedicosService
     */
    @WebEndpoint(name = "GestionReconocimientosMedicosServicePort")
    public GestionReconocimientosMedicosService getGestionReconocimientosMedicosServicePort() {
        return super.getPort(GestionReconocimientosMedicosServicePort, GestionReconocimientosMedicosService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GestionReconocimientosMedicosService
     */
    @WebEndpoint(name = "GestionReconocimientosMedicosServicePort")
    public GestionReconocimientosMedicosService getGestionReconocimientosMedicosServicePort(WebServiceFeature... features) {
        return super.getPort(GestionReconocimientosMedicosServicePort, GestionReconocimientosMedicosService.class, features);
    }

}
